BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
CREATE TABLE dbo.tCustomerAccounts
	(
	Id uniqueidentifier NOT NULL,
	PAN bigint NOT NULL,
	Type int NOT NULL,
	Provider int NOT NULL,
	DTCreate datetime NOT NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.tCustomerAccounts ADD CONSTRAINT
	PK_tCustomerAccounts PRIMARY KEY CLUSTERED 
	(
	Id
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.tCustomerAccounts SET (LOCK_ESCALATION = TABLE)
GO
COMMIT