<?xml version="1.0" encoding="UTF-8"?>
<definitions name="HeartBeatService" targetNamespace="http://www.westernunion.com/HeartBeat" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.westernunion.com/HeartBeat" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <xsd:documentation>WSDL for HeartBeat Service
		Version : 1.0 
		Authors : Western Union 
		Created : 17 November 2010
		
		Revision History:
		1.0 11/17/2010 update port address</xsd:documentation>
  <import namespace="http://www.westernunion.com/HeartBeat" location="HeartBeatBinding.wsdl"/>
  <service name="HeartBeatSOAP_HTTP_Service">
    <port name="HeartBeat_SOAP_HTTP_Port" binding="tns:HeartBeatSOAP_HTTP_Binding">
      <soap:address location="http://www.westernunion.com/HeartBeat"/>
    </port>
  </service>
</definitions>