--- ===============================================================================
-- Author:		<Abhijith>
-- Create date: <11-09-2016>
-- Description:	 Alter Trigger for tWUnion_Trx audit table
-- Jira ID:		<AL-8324>
-- ================================================================================

IF OBJECT_ID(N'tWUnion_TrxAud', N'TR') IS NOT NULL
DROP TRIGGER tWUnion_TrxAud
GO

IF OBJECT_ID(N'tr_tWUnion_Trx_Aud', N'TR') IS NOT NULL
DROP TRIGGER tr_tWUnion_Trx_Aud
GO


CREATE TRIGGER [dbo].[tr_tWUnion_Trx_Aud] ON tWUnion_Trx
AFTER INSERT, UPDATE, DELETE
AS
		SET NOCOUNT ON;
		DECLARE @RevisionNo BIGINT
		DECLARE @AuditEvent SMALLINT	
	
		IF ((SELECT COUNT(1) FROM INSERTED) > 0 AND (SELECT COUNT(1) FROM DELETED) > 0)
		BEGIN
			-- UPDATE
			SET @AuditEvent = 2
		END
		ELSE IF ((SELECT COUNT(1) FROM INSERTED) > 0)
		BEGIN
			-- INSERT
			SET @AuditEvent = 1
		END	 
		ELSE IF ((SELECT COUNT(1) FROM DELETED) > 0)
		BEGIN
			-- DELETE
			SET @AuditEvent = 3
		END     

		IF(@AuditEvent != 3)
		BEGIN
			
			SELECT 
			  @RevisionNo = ISNULL(MAX(RevisionNo), 0) + 1 
			FROM 
			  tWUnion_Trx_Aud wt
			  INNER JOIN INSERTED i ON wt.WUTrxID = i.WUTrxID

         INSERT INTO [dbo].[tWUnion_Trx_Aud]
           ([WUTrxID]
           ,[OriginatorsPrincipalAmount]
           ,[OriginatingCountryCode]
           ,[OriginatingCurrencyCode]
           ,[TranascationType]
           ,[PromotionsCode]
           ,[ExchangeRate]
           ,[DestinationPrincipalAmount]
           ,[GrossTotalAmount]
           ,[Charges]
           ,[TaxAmount]
           ,[Mtcn]
           ,[DTTerminalCreate]
           ,[DTTerminalLastModified]
           ,[PromotionDiscount]
           ,[OtherCharges]
           ,[MoneyTransferKey]
           ,[AdditionalCharges]
           ,[DestinationCountryCode]
           ,[DestinationCurrencyCode]
           ,[DestinationState]
           ,[IsDomesticTransfer]
           ,[IsFixedOnSend]
           ,[PhoneNumber]
           ,[Url]
           ,[AgencyName]
           ,[ChannelPartnerId]
           ,[ProviderId]
           ,[TestQuestion]
           ,[TempMTCN]
           ,[ExpectedPayoutStateCode]
           ,[ExpectedPayoutCityName]
           ,[TestAnswer]
           ,[TestQuestionAvaliable]
           ,[GCNumber]
           ,[SenderName]
           ,[PdsRequiredFlag]
           ,[DfTransactionFlag]
           ,[DeliveryServiceName]
           ,[DTAvailableForPickup]
           ,[RecieverFirstName]
           ,[RecieverLastName]
           ,[RecieverSecondLastName]
           ,[DTServerCreate]
           ,[DTServerLastModified]
           ,[PromoCodeDescription]
           ,[PromoName]
           ,[PromoMessage]
           ,[PromotionError]
           ,[Sender_ComplianceDetails_ComplianceData_Buffer]
           ,[recordingCountryCode]
           ,[recordingCurrencyCode]
           ,[originating_city]
           ,[originating_state]
           ,[municipal_tax]
           ,[state_tax]
           ,[county_tax]
           ,[plus_charges_amount]
           ,[message_charge]
           ,[total_undiscounted_charges]
           ,[total_discount]
           ,[total_discounted_charges]
           ,[instant_notification_addl_service_charges]
           ,[PaySideCharges]
           ,[PaySideTax]
           ,[AmountToReceiver]
           ,[SMSNotificationFlag]
           ,[PersonalMessage]
           ,[DeliveryServiceDesc]
           ,[ReferenceNo]
           ,[WUCard_TotalPointsEarned]
           ,[OriginalTransactionID]
           ,[TransactionSubType]
           ,[ReasonCode]
           ,[ReasonDescription]
           ,[Comments]
           ,[pay_or_do_not_pay_indicator]
           ,[OriginalDestinationCountryCode]
           ,[OriginalDestinationCurrencyCode]
           ,[FilingDate]
           ,[FilingTime]
           ,[PaidDateTime]
           ,[AvailableForPickup]
           ,[DelayHours]
           ,[AvailableForPickupEST]
           ,[DeliveryOption]
           ,[DeliveryOptionDesc]
           ,[PromotionSequenceNo]
           ,[PrincipalAmount]
           ,[Receiver_unv_Buffer]
           ,[Sender_unv_Buffer]
           ,[CounterId]
           ,[TransalatedDeliveryServiceName]
           ,[WUReceiverID]
           ,[WUAccountID]
		   ,[AuditEvent]
           ,[DTAudit]
           ,[RevisionNo])
           SELECT 
			    [WUTrxID]
			   ,[OriginatorsPrincipalAmount]
			   ,[OriginatingCountryCode]
			   ,[OriginatingCurrencyCode]
			   ,[TranascationType]
			   ,[PromotionsCode]
			   ,[ExchangeRate]
			   ,[DestinationPrincipalAmount]
			   ,[GrossTotalAmount]
			   ,[Charges]
			   ,[TaxAmount]
			   ,[Mtcn]
			   ,[DTTerminalCreate]
			   ,[DTTerminalLastModified]
			   ,[PromotionDiscount]
			   ,[OtherCharges]
			   ,[MoneyTransferKey]
			   ,[AdditionalCharges]
			   ,[DestinationCountryCode]
			   ,[DestinationCurrencyCode]
			   ,[DestinationState]
			   ,[IsDomesticTransfer]
			   ,[IsFixedOnSend]
			   ,[PhoneNumber]
			   ,[Url]
			   ,[AgencyName]
			   ,[ChannelPartnerId]
			   ,[ProviderId]
			   ,[TestQuestion]
			   ,[TempMTCN]
			   ,[ExpectedPayoutStateCode]
			   ,[ExpectedPayoutCityName]
			   ,[TestAnswer]
			   ,[TestQuestionAvaliable]
			   ,[GCNumber]
			   ,[SenderName]
			   ,[PdsRequiredFlag]
			   ,[DfTransactionFlag]
			   ,[DeliveryServiceName]
			   ,[DTAvailableForPickup]
			   ,[RecieverFirstName]
			   ,[RecieverLastName]
			   ,[RecieverSecondLastName]
			   ,[DTServerCreate]
			   ,[DTServerLastModified]
			   ,[PromoCodeDescription]
			   ,[PromoName]
			   ,[PromoMessage]
			   ,[PromotionError]
			   ,[Sender_ComplianceDetails_ComplianceData_Buffer]
			   ,[recordingCountryCode]
			   ,[recordingCurrencyCode]
			   ,[originating_city]
			   ,[originating_state]
			   ,[municipal_tax]
			   ,[state_tax]
			   ,[county_tax]
			   ,[plus_charges_amount]
			   ,[message_charge]
			   ,[total_undiscounted_charges]
			   ,[total_discount]
			   ,[total_discounted_charges]
			   ,[instant_notification_addl_service_charges]
			   ,[PaySideCharges]
			   ,[PaySideTax]
			   ,[AmountToReceiver]
			   ,[SMSNotificationFlag]
			   ,[PersonalMessage]
			   ,[DeliveryServiceDesc]
			   ,[ReferenceNo]
			   ,[WUCard_TotalPointsEarned]
			   ,[OriginalTransactionID]
			   ,[TransactionSubType]
			   ,[ReasonCode]
			   ,[ReasonDescription]
			   ,[Comments]
			   ,[pay_or_do_not_pay_indicator]
			   ,[OriginalDestinationCountryCode]
			   ,[OriginalDestinationCurrencyCode]
			   ,[FilingDate]
			   ,[FilingTime]
			   ,[PaidDateTime]
			   ,[AvailableForPickup]
			   ,[DelayHours]
			   ,[AvailableForPickupEST]
			   ,[DeliveryOption]
			   ,[DeliveryOptionDesc]
			   ,[PromotionSequenceNo]
			   ,[PrincipalAmount]
			   ,[Receiver_unv_Buffer]
			   ,[Sender_unv_Buffer]
			   ,[CounterId]
			   ,[TransalatedDeliveryServiceName]
			   ,[WUReceiverID]
			   ,[WUAccountID]
			   ,@AuditEvent
			   ,GETDATE()
			   ,@RevisionNo
			FROM INSERTED

       END
		ELSE
		BEGIN

			SELECT 
			  @RevisionNo = ISNULL(MAX(RevisionNo), 0) + 1 
			FROM 
			  tWUnion_Trx_Aud
			WHERE 
			  WUTrxID = (SELECT WUTrxID FROM DELETED)

			 INSERT INTO [dbo].[tWUnion_Trx_Aud]
			   ([WUTrxID]
			   ,[OriginatorsPrincipalAmount]
			   ,[OriginatingCountryCode]
			   ,[OriginatingCurrencyCode]
			   ,[TranascationType]
			   ,[PromotionsCode]
			   ,[ExchangeRate]
			   ,[DestinationPrincipalAmount]
			   ,[GrossTotalAmount]
			   ,[Charges]
			   ,[TaxAmount]
			   ,[Mtcn]
			   ,[DTTerminalCreate]
			   ,[DTTerminalLastModified]
			   ,[PromotionDiscount]
			   ,[OtherCharges]
			   ,[MoneyTransferKey]
			   ,[AdditionalCharges]
			   ,[DestinationCountryCode]
			   ,[DestinationCurrencyCode]
			   ,[DestinationState]
			   ,[IsDomesticTransfer]
			   ,[IsFixedOnSend]
			   ,[PhoneNumber]
			   ,[Url]
			   ,[AgencyName]
			   ,[ChannelPartnerId]
			   ,[ProviderId]
			   ,[TestQuestion]
			   ,[TempMTCN]
			   ,[ExpectedPayoutStateCode]
			   ,[ExpectedPayoutCityName]
			   ,[TestAnswer]
			   ,[TestQuestionAvaliable]
			   ,[GCNumber]
			   ,[SenderName]
			   ,[PdsRequiredFlag]
			   ,[DfTransactionFlag]
			   ,[DeliveryServiceName]
			   ,[DTAvailableForPickup]
			   ,[RecieverFirstName]
			   ,[RecieverLastName]
			   ,[RecieverSecondLastName]
			   ,[DTServerCreate]
			   ,[DTServerLastModified]
			   ,[PromoCodeDescription]
			   ,[PromoName]
			   ,[PromoMessage]
			   ,[PromotionError]
			   ,[Sender_ComplianceDetails_ComplianceData_Buffer]
			   ,[recordingCountryCode]
			   ,[recordingCurrencyCode]
			   ,[originating_city]
			   ,[originating_state]
			   ,[municipal_tax]
			   ,[state_tax]
			   ,[county_tax]
			   ,[plus_charges_amount]
			   ,[message_charge]
			   ,[total_undiscounted_charges]
			   ,[total_discount]
			   ,[total_discounted_charges]
			   ,[instant_notification_addl_service_charges]
			   ,[PaySideCharges]
			   ,[PaySideTax]
			   ,[AmountToReceiver]
			   ,[SMSNotificationFlag]
			   ,[PersonalMessage]
			   ,[DeliveryServiceDesc]
			   ,[ReferenceNo]
			   ,[WUCard_TotalPointsEarned]
			   ,[OriginalTransactionID]
			   ,[TransactionSubType]
			   ,[ReasonCode]
			   ,[ReasonDescription]
			   ,[Comments]
			   ,[pay_or_do_not_pay_indicator]
			   ,[OriginalDestinationCountryCode]
			   ,[OriginalDestinationCurrencyCode]
			   ,[FilingDate]
			   ,[FilingTime]
			   ,[PaidDateTime]
			   ,[AvailableForPickup]
			   ,[DelayHours]
			   ,[AvailableForPickupEST]
			   ,[DeliveryOption]
			   ,[DeliveryOptionDesc]
			   ,[PromotionSequenceNo]
			   ,[PrincipalAmount]
			   ,[Receiver_unv_Buffer]
			   ,[Sender_unv_Buffer]
			   ,[CounterId]
			   ,[TransalatedDeliveryServiceName]
			   ,[WUReceiverID]
			   ,[WUAccountID]
			   ,[AuditEvent]
			   ,[DTAudit]
			   ,[RevisionNo])
           SELECT 
				[WUTrxID]
			   ,[OriginatorsPrincipalAmount]
			   ,[OriginatingCountryCode]
			   ,[OriginatingCurrencyCode]
			   ,[TranascationType]
			   ,[PromotionsCode]
			   ,[ExchangeRate]
			   ,[DestinationPrincipalAmount]
			   ,[GrossTotalAmount]
			   ,[Charges]
			   ,[TaxAmount]
			   ,[Mtcn]
			   ,[DTTerminalCreate]
			   ,[DTTerminalLastModified]
			   ,[PromotionDiscount]
			   ,[OtherCharges]
			   ,[MoneyTransferKey]
			   ,[AdditionalCharges]
			   ,[DestinationCountryCode]
			   ,[DestinationCurrencyCode]
			   ,[DestinationState]
			   ,[IsDomesticTransfer]
			   ,[IsFixedOnSend]
			   ,[PhoneNumber]
			   ,[Url]
			   ,[AgencyName]
			   ,[ChannelPartnerId]
			   ,[ProviderId]
			   ,[TestQuestion]
			   ,[TempMTCN]
			   ,[ExpectedPayoutStateCode]
			   ,[ExpectedPayoutCityName]
			   ,[TestAnswer]
			   ,[TestQuestionAvaliable]
			   ,[GCNumber]
			   ,[SenderName]
			   ,[PdsRequiredFlag]
			   ,[DfTransactionFlag]
			   ,[DeliveryServiceName]
			   ,[DTAvailableForPickup]
			   ,[RecieverFirstName]
			   ,[RecieverLastName]
			   ,[RecieverSecondLastName]
			   ,[DTServerCreate]
			   ,[DTServerLastModified]
			   ,[PromoCodeDescription]
			   ,[PromoName]
			   ,[PromoMessage]
			   ,[PromotionError]
			   ,[Sender_ComplianceDetails_ComplianceData_Buffer]
			   ,[recordingCountryCode]
			   ,[recordingCurrencyCode]
			   ,[originating_city]
			   ,[originating_state]
			   ,[municipal_tax]
			   ,[state_tax]
			   ,[county_tax]
			   ,[plus_charges_amount]
			   ,[message_charge]
			   ,[total_undiscounted_charges]
			   ,[total_discount]
			   ,[total_discounted_charges]
			   ,[instant_notification_addl_service_charges]
			   ,[PaySideCharges]
			   ,[PaySideTax]
			   ,[AmountToReceiver]
			   ,[SMSNotificationFlag]
			   ,[PersonalMessage]
			   ,[DeliveryServiceDesc]
			   ,[ReferenceNo]
			   ,[WUCard_TotalPointsEarned]
			   ,[OriginalTransactionID]
			   ,[TransactionSubType]
			   ,[ReasonCode]
			   ,[ReasonDescription]
			   ,[Comments]
			   ,[pay_or_do_not_pay_indicator]
			   ,[OriginalDestinationCountryCode]
			   ,[OriginalDestinationCurrencyCode]
			   ,[FilingDate]
			   ,[FilingTime]
			   ,[PaidDateTime]
			   ,[AvailableForPickup]
			   ,[DelayHours]
			   ,[AvailableForPickupEST]
			   ,[DeliveryOption]
			   ,[DeliveryOptionDesc]
			   ,[PromotionSequenceNo]
			   ,[PrincipalAmount]
			   ,[Receiver_unv_Buffer]
			   ,[Sender_unv_Buffer]
			   ,[CounterId]
			   ,[TransalatedDeliveryServiceName]
			   ,[WUReceiverID]
			   ,[WUAccountID]
			   ,@AuditEvent
			   ,GETDATE()
			   ,@RevisionNo
			FROM DELETED

       END
GO


