//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MGI.Cxn.Fund.TSys.TSysFeeSvc {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://api.tsysprepaid.com/fee/type")]
    public partial class chargeFeeException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private chargeFeeError errorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public chargeFeeError error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
                this.RaisePropertyChanged("error");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.tsysprepaid.com/fee")]
    public enum chargeFeeError {
        
        /// <remarks/>
        INVALID_PARAMETER_VALUE,
        
        /// <remarks/>
        PERMISSION_DENIED,
        
        /// <remarks/>
        OPERATION_NOT_ALLOWED,
        
        /// <remarks/>
        OPERATION_NOT_IMPLEMENTED,
        
        /// <remarks/>
        SYSTEM_ERROR,
        
        /// <remarks/>
        INVALID_ACCOUNT_ID,
        
        /// <remarks/>
        INSUFFICIENT_FUNDS,
        
        /// <remarks/>
        INVALID_AMOUNT,
        
        /// <remarks/>
        ACCOUNT_NOT_USEABLE,
        
        /// <remarks/>
        FEE_NOT_FOUND,
        
        /// <remarks/>
        FEE_POLICY_NOT_DEFINED,
        
        /// <remarks/>
        ACCOUNT_MARKED_FRAUD,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://api.tsysprepaid.com/fee/type")]
    public partial class refundFeeException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private refundFeeError errorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public refundFeeError error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
                this.RaisePropertyChanged("error");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.tsysprepaid.com/fee")]
    public enum refundFeeError {
        
        /// <remarks/>
        INVALID_PARAMETER_VALUE,
        
        /// <remarks/>
        PERMISSION_DENIED,
        
        /// <remarks/>
        OPERATION_NOT_ALLOWED,
        
        /// <remarks/>
        OPERATION_NOT_IMPLEMENTED,
        
        /// <remarks/>
        SYSTEM_ERROR,
        
        /// <remarks/>
        INSUFFICIENT_FUNDS,
        
        /// <remarks/>
        INVALID_TRANSACTION_ID,
        
        /// <remarks/>
        FEE_ALREADY_REFUNDED,
        
        /// <remarks/>
        ACCOUNT_MARKED_FRAUD,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://api.tsysprepaid.com/fee/type")]
    public partial class applyFeeException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private applyFeeError errorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public applyFeeError error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
                this.RaisePropertyChanged("error");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.tsysprepaid.com/fee")]
    public enum applyFeeError {
        
        /// <remarks/>
        INVALID_PARAMETER_VALUE,
        
        /// <remarks/>
        PERMISSION_DENIED,
        
        /// <remarks/>
        OPERATION_NOT_ALLOWED,
        
        /// <remarks/>
        OPERATION_NOT_IMPLEMENTED,
        
        /// <remarks/>
        SYSTEM_ERROR,
        
        /// <remarks/>
        INVALID_ACCOUNT_ID,
        
        /// <remarks/>
        INSUFFICIENT_FUNDS,
        
        /// <remarks/>
        INVALID_AMOUNT,
        
        /// <remarks/>
        ACCOUNT_NOT_USEABLE,
        
        /// <remarks/>
        FEE_NOT_FOUND,
        
        /// <remarks/>
        FEE_POLICY_NOT_DEFINED,
        
        /// <remarks/>
        ACCOUNT_MARKED_FRAUD,
        
        /// <remarks/>
        MULTIPLE_FEE_POLICIES_EXIST,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://api.tsysprepaid.com/fee/type")]
    public partial class getAccountFeeDetailsException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private getAccountFeeDetailsError errorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public getAccountFeeDetailsError error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
                this.RaisePropertyChanged("error");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.tsysprepaid.com/fee")]
    public enum getAccountFeeDetailsError {
        
        /// <remarks/>
        OPERATION_NOT_ALLOWED,
        
        /// <remarks/>
        INVALID_ACCOUNT_ID,
        
        /// <remarks/>
        PERMISSION_DENIED,
        
        /// <remarks/>
        SYSTEM_ERROR,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://api.tsysprepaid.com/fee/wsdl", ConfigurationName="TSysFeeSvc.feeService")]
    public interface feeService {
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://api.tsysprepaid.com/fee/type) of message chargeFeeRequest does not match the default value (http://api.tsysprepaid.com/fee/wsdl)
        [System.ServiceModel.OperationContractAttribute(Action="urn:#chargeFee", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(MGI.Cxn.Fund.TSys.TSysFeeSvc.chargeFeeException), Action="urn:#chargeFee", Name="chargeFeeException", Namespace="http://api.tsysprepaid.com/fee/type")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MGI.Cxn.Fund.TSys.TSysFeeSvc.chargeFeeResponse chargeFee(MGI.Cxn.Fund.TSys.TSysFeeSvc.chargeFeeRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://api.tsysprepaid.com/fee/type) of message refundFeeRequest does not match the default value (http://api.tsysprepaid.com/fee/wsdl)
        [System.ServiceModel.OperationContractAttribute(Action="urn:#refundFee", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(MGI.Cxn.Fund.TSys.TSysFeeSvc.refundFeeException), Action="urn:#refundFee", Name="refundFeeException", Namespace="http://api.tsysprepaid.com/fee/type")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MGI.Cxn.Fund.TSys.TSysFeeSvc.refundFeeResponse refundFee(MGI.Cxn.Fund.TSys.TSysFeeSvc.refundFeeRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://api.tsysprepaid.com/fee/type) of message applyFeeRequest does not match the default value (http://api.tsysprepaid.com/fee/wsdl)
        [System.ServiceModel.OperationContractAttribute(Action="urn:#applyFee", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(MGI.Cxn.Fund.TSys.TSysFeeSvc.applyFeeException), Action="urn:#applyFee", Name="applyFeeException", Namespace="http://api.tsysprepaid.com/fee/type")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MGI.Cxn.Fund.TSys.TSysFeeSvc.applyFeeResponse applyFee(MGI.Cxn.Fund.TSys.TSysFeeSvc.applyFeeRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://api.tsysprepaid.com/fee/type) of message getAccountFeeDetailsRequest does not match the default value (http://api.tsysprepaid.com/fee/wsdl)
        [System.ServiceModel.OperationContractAttribute(Action="urn:#getAccountFeeDetails", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(MGI.Cxn.Fund.TSys.TSysFeeSvc.getAccountFeeDetailsException), Action="urn:#getAccountFeeDetails", Name="getAccountFeeDetailsException", Namespace="http://api.tsysprepaid.com/fee/type")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MGI.Cxn.Fund.TSys.TSysFeeSvc.getAccountFeeDetailsResponse getAccountFeeDetails(MGI.Cxn.Fund.TSys.TSysFeeSvc.getAccountFeeDetailsRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.tsysprepaid.com/fee")]
    public enum feeType {
        
        /// <remarks/>
        ISSUE_CARD,
        
        /// <remarks/>
        REPLACE_CARD,
        
        /// <remarks/>
        ACH_STOP_PAYMENT_ACTIVITY,
        
        /// <remarks/>
        PRIMARY_ISSUE_CARD,
        
        /// <remarks/>
        DEPENDENT_ISSUE_CARD,
        
        /// <remarks/>
        LOAD,
        
        /// <remarks/>
        TRANSFER,
        
        /// <remarks/>
        GIFT,
        
        /// <remarks/>
        INACTIVITY,
        
        /// <remarks/>
        PIN_DISTRIBUTION,
        
        /// <remarks/>
        CLOSE_ACCOUNT,
        
        /// <remarks/>
        OVERDRAFT,
        
        /// <remarks/>
        MAINTENANCE,
        
        /// <remarks/>
        IVR,
        
        /// <remarks/>
        CONTACT,
        
        /// <remarks/>
        EXPRESS_DELIVERY,
        
        /// <remarks/>
        OVERNIGHT_DELIVERY,
        
        /// <remarks/>
        BILL_PAYMENT,
        
        /// <remarks/>
        BILLPAY_MONTHLY,
        
        /// <remarks/>
        BILLPAY_REGISTRATION,
        
        /// <remarks/>
        ISSUE_CARD_EXPEDITE,
        
        /// <remarks/>
        DAMAGED_CARD,
        
        /// <remarks/>
        CARD_NAME_CHANGED,
        
        /// <remarks/>
        PLASTIC_CHANGED,
        
        /// <remarks/>
        LOST_STOLEN_CARD,
        
        /// <remarks/>
        RENEW_CARD,
        
        /// <remarks/>
        DAMAGED_CARD_EXPEDITE,
        
        /// <remarks/>
        CARD_NAME_CHANGED_EXPEDITE,
        
        /// <remarks/>
        PLASTIC_CHANGED_EXPEDITE,
        
        /// <remarks/>
        LOST_STOLEN_CARD_EXPEDITE,
        
        /// <remarks/>
        RENEW_CARD_EXPEDITE,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="chargeFee", WrapperNamespace="http://api.tsysprepaid.com/fee/type", IsWrapped=true)]
    public partial class chargeFeeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.tsysprepaid.com/fee", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://api.tsysprepaid.com/fee")]
        public long accountId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.tsysprepaid.com/fee", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://api.tsysprepaid.com/fee")]
        public MGI.Cxn.Fund.TSys.TSysFeeSvc.feeType feeType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.tsysprepaid.com/fee", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://api.tsysprepaid.com/fee")]
        public long amount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.tsysprepaid.com/fee", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://api.tsysprepaid.com/fee")]
        public string description;
        
        public chargeFeeRequest() {
        }
        
        public chargeFeeRequest(long accountId, MGI.Cxn.Fund.TSys.TSysFeeSvc.feeType feeType, long amount, string description) {
            this.accountId = accountId;
            this.feeType = feeType;
            this.amount = amount;
            this.description = description;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="chargeFeeResponse", WrapperNamespace="http://api.tsysprepaid.com/fee/type", IsWrapped=true)]
    public partial class chargeFeeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.tsysprepaid.com/fee", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://api.tsysprepaid.com/fee")]
        public long feeTransactionId;
        
        public chargeFeeResponse() {
        }
        
        public chargeFeeResponse(long feeTransactionId) {
            this.feeTransactionId = feeTransactionId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="refundFee", WrapperNamespace="http://api.tsysprepaid.com/fee/type", IsWrapped=true)]
    public partial class refundFeeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.tsysprepaid.com/fee", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://api.tsysprepaid.com/fee")]
        public long transactionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.tsysprepaid.com/fee", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://api.tsysprepaid.com/fee")]
        public string description;
        
        public refundFeeRequest() {
        }
        
        public refundFeeRequest(long transactionId, string description) {
            this.transactionId = transactionId;
            this.description = description;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="refundFeeResponse", WrapperNamespace="http://api.tsysprepaid.com/fee/type", IsWrapped=true)]
    public partial class refundFeeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.tsysprepaid.com/fee", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://api.tsysprepaid.com/fee")]
        public long reversalFeeTransactionId;
        
        public refundFeeResponse() {
        }
        
        public refundFeeResponse(long reversalFeeTransactionId) {
            this.reversalFeeTransactionId = reversalFeeTransactionId;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.tsysprepaid.com/fee")]
    public enum feeSubClass {
        
        /// <remarks/>
        ISSUE_CARD_FEE,
        
        /// <remarks/>
        ISSUE_CHECK_FEE,
        
        /// <remarks/>
        ACH_STOP_PAYMENT_ACTIVITY_FEE,
        
        /// <remarks/>
        REPLACE_CARD_FEE,
        
        /// <remarks/>
        PRIMARY_ISSUE_CARD_FEE,
        
        /// <remarks/>
        DEPENDENT_ISSUE_CARD_FEE,
        
        /// <remarks/>
        LOAD_FEE,
        
        /// <remarks/>
        TRANSFER_FEE,
        
        /// <remarks/>
        GIFT_FEE,
        
        /// <remarks/>
        INACTIVITY_FEE,
        
        /// <remarks/>
        PIN_DISTRIBUTION_FEE,
        
        /// <remarks/>
        CLOSE_ACCOUNT_FEE,
        
        /// <remarks/>
        OVERDRAFT_FEE,
        
        /// <remarks/>
        MAINTENANCE_FEE,
        
        /// <remarks/>
        IVR_FEE,
        
        /// <remarks/>
        CONTACT_FEE,
        
        /// <remarks/>
        EXPRESS_DELIVERY_FEE,
        
        /// <remarks/>
        OVERNIGHT_DELIVERY_FEE,
        
        /// <remarks/>
        BILL_PAYMENT_FEE,
        
        /// <remarks/>
        BILLPAY_MONTHLY_FEE,
        
        /// <remarks/>
        BILLPAY_REGISTRATION_FEE,
        
        /// <remarks/>
        ISSUE_CARD_EXPEDITE_FEE,
        
        /// <remarks/>
        DAMAGED_CARD_FEE,
        
        /// <remarks/>
        CARD_NAME_CHANGED_FEE,
        
        /// <remarks/>
        PLASTIC_CHANGED_FEE,
        
        /// <remarks/>
        LOST_STOLEN_CARD_FEE,
        
        /// <remarks/>
        RENEW_CARD_FEE,
        
        /// <remarks/>
        DAMAGED_CARD_EXPEDITE_FEE,
        
        /// <remarks/>
        CARD_NAME_CHANGED_EXPEDITE_FEE,
        
        /// <remarks/>
        PLASTIC_CHANGED_EXPEDITE_FEE,
        
        /// <remarks/>
        LOST_STOLEN_CARD_EXPEDITE_FEE,
        
        /// <remarks/>
        RENEW_CARD_EXPEDITE_FEE,
        
        /// <remarks/>
        TRANSFER_TO_BANK_ACCOUNT_FEE,
        
        /// <remarks/>
        PRIMARY_REPLACE_CARD_FEE,
        
        /// <remarks/>
        CARD_PURCHASE_FEE,
        
        /// <remarks/>
        CORP_TRANSFER_MANUAL_REPLACEMENT_CARD_FEE,
        
        /// <remarks/>
        ONLINE_STATEMENT_FEE,
        
        /// <remarks/>
        PAPER_STATEMENT_FEE,
        
        /// <remarks/>
        ON_DEMAND_STATEMENT_FEE,
        
        /// <remarks/>
        LIVE_AGENT_FEE,
        
        /// <remarks/>
        PERIODIC_FEE,
        
        /// <remarks/>
        ACCOUNT_CYCLE_FEE,
        
        /// <remarks/>
        ADDITIONAL_USER_FEE,
        
        /// <remarks/>
        ADDITIONAL_USER_EXPEDITE_FEE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.tsysprepaid.com/fee")]
    public partial class feeTransactionDetail : object, System.ComponentModel.INotifyPropertyChanged {
        
        private feeTransactionData[] feeTransactionListField;
        
        private capData capDetailsField;
        
        private tierData tierDetailsField;
        
        private System.Nullable<bool> waivedField;
        
        private bool waivedFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("feeTransactions")]
        public feeTransactionData[] feeTransactionList {
            get {
                return this.feeTransactionListField;
            }
            set {
                this.feeTransactionListField = value;
                this.RaisePropertyChanged("feeTransactionList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public capData capDetails {
            get {
                return this.capDetailsField;
            }
            set {
                this.capDetailsField = value;
                this.RaisePropertyChanged("capDetails");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public tierData tierDetails {
            get {
                return this.tierDetailsField;
            }
            set {
                this.tierDetailsField = value;
                this.RaisePropertyChanged("tierDetails");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<bool> waived {
            get {
                return this.waivedField;
            }
            set {
                this.waivedField = value;
                this.RaisePropertyChanged("waived");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool waivedSpecified {
            get {
                return this.waivedFieldSpecified;
            }
            set {
                this.waivedFieldSpecified = value;
                this.RaisePropertyChanged("waivedSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.tsysprepaid.com/fee")]
    public partial class feeTransactionData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long transactionIdField;
        
        private long amountField;
        
        private string transaction_statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long transactionId {
            get {
                return this.transactionIdField;
            }
            set {
                this.transactionIdField = value;
                this.RaisePropertyChanged("transactionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
                this.RaisePropertyChanged("amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string transaction_status {
            get {
                return this.transaction_statusField;
            }
            set {
                this.transaction_statusField = value;
                this.RaisePropertyChanged("transaction_status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.tsysprepaid.com/fee")]
    public partial class capData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool capReachedField;
        
        private long capAmountField;
        
        private bool capAmountFieldSpecified;
        
        private long capUnassessedAmountField;
        
        private bool capUnassessedAmountFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool capReached {
            get {
                return this.capReachedField;
            }
            set {
                this.capReachedField = value;
                this.RaisePropertyChanged("capReached");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long capAmount {
            get {
                return this.capAmountField;
            }
            set {
                this.capAmountField = value;
                this.RaisePropertyChanged("capAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool capAmountSpecified {
            get {
                return this.capAmountFieldSpecified;
            }
            set {
                this.capAmountFieldSpecified = value;
                this.RaisePropertyChanged("capAmountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public long capUnassessedAmount {
            get {
                return this.capUnassessedAmountField;
            }
            set {
                this.capUnassessedAmountField = value;
                this.RaisePropertyChanged("capUnassessedAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool capUnassessedAmountSpecified {
            get {
                return this.capUnassessedAmountFieldSpecified;
            }
            set {
                this.capUnassessedAmountFieldSpecified = value;
                this.RaisePropertyChanged("capUnassessedAmountSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.tsysprepaid.com/fee")]
    public partial class tierData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool tieredFeeAppliedField;
        
        private string tierFactorField;
        
        private long minTierValueField;
        
        private bool minTierValueFieldSpecified;
        
        private long maxTierValueField;
        
        private bool maxTierValueFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool tieredFeeApplied {
            get {
                return this.tieredFeeAppliedField;
            }
            set {
                this.tieredFeeAppliedField = value;
                this.RaisePropertyChanged("tieredFeeApplied");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string tierFactor {
            get {
                return this.tierFactorField;
            }
            set {
                this.tierFactorField = value;
                this.RaisePropertyChanged("tierFactor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public long minTierValue {
            get {
                return this.minTierValueField;
            }
            set {
                this.minTierValueField = value;
                this.RaisePropertyChanged("minTierValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool minTierValueSpecified {
            get {
                return this.minTierValueFieldSpecified;
            }
            set {
                this.minTierValueFieldSpecified = value;
                this.RaisePropertyChanged("minTierValueSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public long maxTierValue {
            get {
                return this.maxTierValueField;
            }
            set {
                this.maxTierValueField = value;
                this.RaisePropertyChanged("maxTierValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maxTierValueSpecified {
            get {
                return this.maxTierValueFieldSpecified;
            }
            set {
                this.maxTierValueFieldSpecified = value;
                this.RaisePropertyChanged("maxTierValueSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="applyFee", WrapperNamespace="http://api.tsysprepaid.com/fee/type", IsWrapped=true)]
    public partial class applyFeeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.tsysprepaid.com/fee", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://api.tsysprepaid.com/fee")]
        public long accountId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.tsysprepaid.com/fee", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://api.tsysprepaid.com/fee")]
        public MGI.Cxn.Fund.TSys.TSysFeeSvc.feeSubClass feeSubClass;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.tsysprepaid.com/fee", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://api.tsysprepaid.com/fee")]
        public long amount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.tsysprepaid.com/fee", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://api.tsysprepaid.com/fee")]
        public string description;
        
        public applyFeeRequest() {
        }
        
        public applyFeeRequest(long accountId, MGI.Cxn.Fund.TSys.TSysFeeSvc.feeSubClass feeSubClass, long amount, string description) {
            this.accountId = accountId;
            this.feeSubClass = feeSubClass;
            this.amount = amount;
            this.description = description;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="applyFeeResponse", WrapperNamespace="http://api.tsysprepaid.com/fee/type", IsWrapped=true)]
    public partial class applyFeeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.tsysprepaid.com/fee", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://api.tsysprepaid.com/fee", IsNullable=true)]
        public MGI.Cxn.Fund.TSys.TSysFeeSvc.feeTransactionDetail feeDetailTransaction;
        
        public applyFeeResponse() {
        }
        
        public applyFeeResponse(MGI.Cxn.Fund.TSys.TSysFeeSvc.feeTransactionDetail feeDetailTransaction) {
            this.feeDetailTransaction = feeDetailTransaction;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.tsysprepaid.com/fee")]
    public partial class accountFeeData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private pendingRecaptureFeeDetails[] pendingRecaptureFeeDetailsField;
        
        private periodicFeeDetails[] periodicFeeDetailsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("pendingRecaptureFeeDetails", IsNullable=true, Order=0)]
        public pendingRecaptureFeeDetails[] pendingRecaptureFeeDetails {
            get {
                return this.pendingRecaptureFeeDetailsField;
            }
            set {
                this.pendingRecaptureFeeDetailsField = value;
                this.RaisePropertyChanged("pendingRecaptureFeeDetails");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("periodicFeeDetails", IsNullable=true, Order=1)]
        public periodicFeeDetails[] periodicFeeDetails {
            get {
                return this.periodicFeeDetailsField;
            }
            set {
                this.periodicFeeDetailsField = value;
                this.RaisePropertyChanged("periodicFeeDetails");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.tsysprepaid.com/fee")]
    public partial class pendingRecaptureFeeDetails : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string feeDescriptionField;
        
        private long feeAmountField;
        
        private long pendingFeeAmountField;
        
        private System.DateTime feePostedDateField;
        
        private System.DateTime recaptureExpiryDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string feeDescription {
            get {
                return this.feeDescriptionField;
            }
            set {
                this.feeDescriptionField = value;
                this.RaisePropertyChanged("feeDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long feeAmount {
            get {
                return this.feeAmountField;
            }
            set {
                this.feeAmountField = value;
                this.RaisePropertyChanged("feeAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public long pendingFeeAmount {
            get {
                return this.pendingFeeAmountField;
            }
            set {
                this.pendingFeeAmountField = value;
                this.RaisePropertyChanged("pendingFeeAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime feePostedDate {
            get {
                return this.feePostedDateField;
            }
            set {
                this.feePostedDateField = value;
                this.RaisePropertyChanged("feePostedDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime recaptureExpiryDate {
            get {
                return this.recaptureExpiryDateField;
            }
            set {
                this.recaptureExpiryDateField = value;
                this.RaisePropertyChanged("recaptureExpiryDate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.tsysprepaid.com/fee")]
    public partial class periodicFeeDetails : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string feeDescriptionField;
        
        private feeSubClass feeTypeField;
        
        private long feeAmountField;
        
        private periodType feePeriodField;
        
        private System.DateTime feeAssessmentDayField;
        
        private bool feeAssessmentDayFieldSpecified;
        
        private System.DateTime acctCycleDateField;
        
        private bool acctCycleDateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string feeDescription {
            get {
                return this.feeDescriptionField;
            }
            set {
                this.feeDescriptionField = value;
                this.RaisePropertyChanged("feeDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public feeSubClass feeType {
            get {
                return this.feeTypeField;
            }
            set {
                this.feeTypeField = value;
                this.RaisePropertyChanged("feeType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public long feeAmount {
            get {
                return this.feeAmountField;
            }
            set {
                this.feeAmountField = value;
                this.RaisePropertyChanged("feeAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public periodType feePeriod {
            get {
                return this.feePeriodField;
            }
            set {
                this.feePeriodField = value;
                this.RaisePropertyChanged("feePeriod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime feeAssessmentDay {
            get {
                return this.feeAssessmentDayField;
            }
            set {
                this.feeAssessmentDayField = value;
                this.RaisePropertyChanged("feeAssessmentDay");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool feeAssessmentDaySpecified {
            get {
                return this.feeAssessmentDayFieldSpecified;
            }
            set {
                this.feeAssessmentDayFieldSpecified = value;
                this.RaisePropertyChanged("feeAssessmentDaySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public System.DateTime acctCycleDate {
            get {
                return this.acctCycleDateField;
            }
            set {
                this.acctCycleDateField = value;
                this.RaisePropertyChanged("acctCycleDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool acctCycleDateSpecified {
            get {
                return this.acctCycleDateFieldSpecified;
            }
            set {
                this.acctCycleDateFieldSpecified = value;
                this.RaisePropertyChanged("acctCycleDateSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.tsysprepaid.com/fee")]
    public enum periodType {
        
        /// <remarks/>
        WEEKLY,
        
        /// <remarks/>
        MONTHLY,
        
        /// <remarks/>
        BIWEEKLY,
        
        /// <remarks/>
        BIMONTHLY,
        
        /// <remarks/>
        QUARTERLY,
        
        /// <remarks/>
        ANNUALLY,
        
        /// <remarks/>
        CUSTOM,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAccountFeeDetails", WrapperNamespace="http://api.tsysprepaid.com/fee/type", IsWrapped=true)]
    public partial class getAccountFeeDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.tsysprepaid.com/fee", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://api.tsysprepaid.com/fee")]
        public long accountId;
        
        public getAccountFeeDetailsRequest() {
        }
        
        public getAccountFeeDetailsRequest(long accountId) {
            this.accountId = accountId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAccountFeeDetailsResponse", WrapperNamespace="http://api.tsysprepaid.com/fee/type", IsWrapped=true)]
    public partial class getAccountFeeDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.tsysprepaid.com/fee", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://api.tsysprepaid.com/fee", IsNullable=true)]
        public MGI.Cxn.Fund.TSys.TSysFeeSvc.accountFeeData accountFeeData;
        
        public getAccountFeeDetailsResponse() {
        }
        
        public getAccountFeeDetailsResponse(MGI.Cxn.Fund.TSys.TSysFeeSvc.accountFeeData accountFeeData) {
            this.accountFeeData = accountFeeData;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface feeServiceChannel : MGI.Cxn.Fund.TSys.TSysFeeSvc.feeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class feeServiceClient : System.ServiceModel.ClientBase<MGI.Cxn.Fund.TSys.TSysFeeSvc.feeService>, MGI.Cxn.Fund.TSys.TSysFeeSvc.feeService {
        
        public feeServiceClient() {
        }
        
        public feeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public feeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public feeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public feeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MGI.Cxn.Fund.TSys.TSysFeeSvc.chargeFeeResponse MGI.Cxn.Fund.TSys.TSysFeeSvc.feeService.chargeFee(MGI.Cxn.Fund.TSys.TSysFeeSvc.chargeFeeRequest request) {
            return base.Channel.chargeFee(request);
        }
        
        public long chargeFee(long accountId, MGI.Cxn.Fund.TSys.TSysFeeSvc.feeType feeType, long amount, string description) {
            MGI.Cxn.Fund.TSys.TSysFeeSvc.chargeFeeRequest inValue = new MGI.Cxn.Fund.TSys.TSysFeeSvc.chargeFeeRequest();
            inValue.accountId = accountId;
            inValue.feeType = feeType;
            inValue.amount = amount;
            inValue.description = description;
            MGI.Cxn.Fund.TSys.TSysFeeSvc.chargeFeeResponse retVal = ((MGI.Cxn.Fund.TSys.TSysFeeSvc.feeService)(this)).chargeFee(inValue);
            return retVal.feeTransactionId;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MGI.Cxn.Fund.TSys.TSysFeeSvc.refundFeeResponse MGI.Cxn.Fund.TSys.TSysFeeSvc.feeService.refundFee(MGI.Cxn.Fund.TSys.TSysFeeSvc.refundFeeRequest request) {
            return base.Channel.refundFee(request);
        }
        
        public long refundFee(long transactionId, string description) {
            MGI.Cxn.Fund.TSys.TSysFeeSvc.refundFeeRequest inValue = new MGI.Cxn.Fund.TSys.TSysFeeSvc.refundFeeRequest();
            inValue.transactionId = transactionId;
            inValue.description = description;
            MGI.Cxn.Fund.TSys.TSysFeeSvc.refundFeeResponse retVal = ((MGI.Cxn.Fund.TSys.TSysFeeSvc.feeService)(this)).refundFee(inValue);
            return retVal.reversalFeeTransactionId;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MGI.Cxn.Fund.TSys.TSysFeeSvc.applyFeeResponse MGI.Cxn.Fund.TSys.TSysFeeSvc.feeService.applyFee(MGI.Cxn.Fund.TSys.TSysFeeSvc.applyFeeRequest request) {
            return base.Channel.applyFee(request);
        }
        
        public MGI.Cxn.Fund.TSys.TSysFeeSvc.feeTransactionDetail applyFee(long accountId, MGI.Cxn.Fund.TSys.TSysFeeSvc.feeSubClass feeSubClass, long amount, string description) {
            MGI.Cxn.Fund.TSys.TSysFeeSvc.applyFeeRequest inValue = new MGI.Cxn.Fund.TSys.TSysFeeSvc.applyFeeRequest();
            inValue.accountId = accountId;
            inValue.feeSubClass = feeSubClass;
            inValue.amount = amount;
            inValue.description = description;
            MGI.Cxn.Fund.TSys.TSysFeeSvc.applyFeeResponse retVal = ((MGI.Cxn.Fund.TSys.TSysFeeSvc.feeService)(this)).applyFee(inValue);
            return retVal.feeDetailTransaction;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MGI.Cxn.Fund.TSys.TSysFeeSvc.getAccountFeeDetailsResponse MGI.Cxn.Fund.TSys.TSysFeeSvc.feeService.getAccountFeeDetails(MGI.Cxn.Fund.TSys.TSysFeeSvc.getAccountFeeDetailsRequest request) {
            return base.Channel.getAccountFeeDetails(request);
        }
        
        public MGI.Cxn.Fund.TSys.TSysFeeSvc.accountFeeData getAccountFeeDetails(long accountId) {
            MGI.Cxn.Fund.TSys.TSysFeeSvc.getAccountFeeDetailsRequest inValue = new MGI.Cxn.Fund.TSys.TSysFeeSvc.getAccountFeeDetailsRequest();
            inValue.accountId = accountId;
            MGI.Cxn.Fund.TSys.TSysFeeSvc.getAccountFeeDetailsResponse retVal = ((MGI.Cxn.Fund.TSys.TSysFeeSvc.feeService)(this)).getAccountFeeDetails(inValue);
            return retVal.accountFeeData;
        }
    }
}
