//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCF.Zeo.Cxn.Check.Chexar.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://beta.chexar.net/webservice/callcenterservice.asmx")]
        public string MGI_Alloy_CXN_Check_Chexar_ChexarCallCenterService_CallCenterService {
            get {
                return ((string)(this["MGI_Alloy_CXN_Check_Chexar_ChexarCallCenterService_CallCenterService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://beta.chexar.net/webservice/commonservice.asmx")]
        public string MGI_Alloy_CXN_Check_Chexar_ChexarCommonService_CommonService {
            get {
                return ((string)(this["MGI_Alloy_CXN_Check_Chexar_ChexarCommonService_CommonService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://beta.chexar.net/webservice/CustService.asmx")]
        public string MGI_Alloy_CXN_Check_Chexar_ChexarCustomerService_CustService {
            get {
                return ((string)(this["MGI_Alloy_CXN_Check_Chexar_ChexarCustomerService_CustService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://beta.chexar.net/webservice/transactionservice.asmx")]
        public string MGI_Alloy_CXN_Check_Chexar_ChexarTransactionService_TransactionService {
            get {
                return ((string)(this["MGI_Alloy_CXN_Check_Chexar_ChexarTransactionService_TransactionService"]));
            }
        }
    }
}
