//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NexxoSiteMap {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NexxoSiteMap() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.NexxoSiteMap", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill Payment.
        /// </summary>
        internal static string BillPayment {
            get {
                return ResourceManager.GetString("BillPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan a Check.
        /// </summary>
        internal static string CashaCheck {
            get {
                return ResourceManager.GetString("CashaCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Drawer Report.
        /// </summary>
        internal static string CashDrawerReport {
            get {
                return ResourceManager.GetString("CashDrawerReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Management.
        /// </summary>
        internal static string CashManagementReport {
            get {
                return ResourceManager.GetString("CashManagementReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash to Customer.
        /// </summary>
        internal static string CashtoCustomer {
            get {
                return ResourceManager.GetString("CashtoCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Processing Fee.
        /// </summary>
        internal static string CheckCashingFee {
            get {
                return ResourceManager.GetString("CheckCashingFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check in Process.
        /// </summary>
        internal static string CheckCashingProgress {
            get {
                return ResourceManager.GetString("CheckCashingProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Declined.
        /// </summary>
        internal static string CheckDeclined {
            get {
                return ResourceManager.GetString("CheckDeclined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reciept to Customer.
        /// </summary>
        internal static string CheckoutSuccess {
            get {
                return ResourceManager.GetString("CheckoutSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Pending.
        /// </summary>
        internal static string CheckPending {
            get {
                return ResourceManager.GetString("CheckPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        internal static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Check Fee.
        /// </summary>
        internal static string ConfirmCheckFeeScreen {
            get {
                return ResourceManager.GetString("ConfirmCheckFeeScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Receiver.
        /// </summary>
        internal static string CreateReceiver {
            get {
                return ResourceManager.GetString("CreateReceiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodd Frank Confirmation.
        /// </summary>
        internal static string DoddFrankConfirmation {
            get {
                return ResourceManager.GetString("DoddFrankConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Receiver.
        /// </summary>
        internal static string EditReceiver {
            get {
                return ResourceManager.GetString("EditReceiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Check Amount.
        /// </summary>
        internal static string EnterCheckAmount {
            get {
                return ResourceManager.GetString("EnterCheckAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Locations.
        /// </summary>
        internal static string ManageLocations {
            get {
                return ResourceManager.GetString("ManageLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Receivers.
        /// </summary>
        internal static string ManageReceivers {
            get {
                return ResourceManager.GetString("ManageReceivers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Users.
        /// </summary>
        internal static string ManageUsers {
            get {
                return ResourceManager.GetString("ManageUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MoneyOrder.
        /// </summary>
        internal static string MoneyOrder {
            get {
                return ResourceManager.GetString("MoneyOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Reports.
        /// </summary>
        internal static string MyReports {
            get {
                return ResourceManager.GetString("MyReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Prepaid Card.
        /// </summary>
        internal static string NewPrepaidCard {
            get {
                return ResourceManager.GetString("NewPrepaidCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pickup Options.
        /// </summary>
        internal static string PickupOptions {
            get {
                return ResourceManager.GetString("PickupOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Check.
        /// </summary>
        internal static string ProcessCheck {
            get {
                return ResourceManager.GetString("ProcessCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing Check.
        /// </summary>
        internal static string ProcessingCheck {
            get {
                return ResourceManager.GetString("ProcessingCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        internal static string ProductInformation {
            get {
                return ResourceManager.GetString("ProductInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan a Check.
        /// </summary>
        internal static string ScanaCheck {
            get {
                return ResourceManager.GetString("ScanaCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Money.
        /// </summary>
        internal static string SendMoney {
            get {
                return ResourceManager.GetString("SendMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Prepaid Card.
        /// </summary>
        internal static string ServicePrepaidCard {
            get {
                return ResourceManager.GetString("ServicePrepaidCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShoppingCart Checkout.
        /// </summary>
        internal static string ShoppingCartCheckout {
            get {
                return ResourceManager.GetString("ShoppingCartCheckout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms &amp; Conditions.
        /// </summary>
        internal static string TermsAndConditions {
            get {
                return ResourceManager.GetString("TermsAndConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction History.
        /// </summary>
        internal static string TransactionHistory {
            get {
                return ResourceManager.GetString("TransactionHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Summary.
        /// </summary>
        internal static string TransactionSummary {
            get {
                return ResourceManager.GetString("TransactionSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $4 Purchase Fee will be deducted.
        /// </summary>
        internal static string VisaInitialLoad {
            get {
                return ResourceManager.GetString("VisaInitialLoad", resourceCulture);
    }
}
    }
}
