//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MGI.Cxn.Check.Certegy.Certegy {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://fis.certegy.pca.com/", ConfigurationName="Certegy.PCA")]
    public interface PCA {
        
        // CODEGEN: Generating message contract since the wrapper name (AuthorizeRequest) of message authorizeRequest does not match the default value (authorize)
        [System.ServiceModel.OperationContractAttribute(Action="authorize", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MGI.Cxn.Check.Certegy.Certegy.authorizeResponse authorize(MGI.Cxn.Check.Certegy.Certegy.authorizeRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (ReverseRequest) of message reverseRequest does not match the default value (reverse)
        [System.ServiceModel.OperationContractAttribute(Action="reverse", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MGI.Cxn.Check.Certegy.Certegy.reverseResponse reverse(MGI.Cxn.Check.Certegy.Certegy.reverseRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (EchoRequest) of message echoRequest does not match the default value (echo)
        [System.ServiceModel.OperationContractAttribute(Action="echo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MGI.Cxn.Check.Certegy.Certegy.echoResponse echo(MGI.Cxn.Check.Certegy.Certegy.echoRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fis.certegy.pca.com/")]
    public partial class Check : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string amountField;
        
        private MICR mICRField;
        
        private string issueDateField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
                this.RaisePropertyChanged("Amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public MICR MICR {
            get {
                return this.mICRField;
            }
            set {
                this.mICRField = value;
                this.RaisePropertyChanged("MICR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string IssueDate {
            get {
                return this.issueDateField;
            }
            set {
                this.issueDateField = value;
                this.RaisePropertyChanged("IssueDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fis.certegy.pca.com/")]
    public partial class MICR : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string expansionTypeField;
        
        private string entryTypeField;
        
        private string lineField;
        
        public MICR() {
            this.entryTypeField = "S";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ExpansionType {
            get {
                return this.expansionTypeField;
            }
            set {
                this.expansionTypeField = value;
                this.RaisePropertyChanged("ExpansionType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string EntryType {
            get {
                return this.entryTypeField;
            }
            set {
                this.entryTypeField = value;
                this.RaisePropertyChanged("EntryType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Line {
            get {
                return this.lineField;
            }
            set {
                this.lineField = value;
                this.RaisePropertyChanged("Line");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fis.certegy.pca.com/")]
    public partial class Custom : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fis.certegy.pca.com/")]
    public partial class Device : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string typeField;
        
        private string phoneField;
        
        private string idField;
        
        private string iPAddressField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
                this.RaisePropertyChanged("Phone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string IPAddress {
            get {
                return this.iPAddressField;
            }
            set {
                this.iPAddressField = value;
                this.RaisePropertyChanged("IPAddress");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fis.certegy.pca.com/")]
    public partial class ID : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string typeField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fis.certegy.pca.com/")]
    public partial class Address : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string line1Field;
        
        private string line2Field;
        
        private string cityField;
        
        private string stateField;
        
        private string zipField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Line1 {
            get {
                return this.line1Field;
            }
            set {
                this.line1Field = value;
                this.RaisePropertyChanged("Line1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Line2 {
            get {
                return this.line2Field;
            }
            set {
                this.line2Field = value;
                this.RaisePropertyChanged("Line2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("City");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
                this.RaisePropertyChanged("State");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Zip {
            get {
                return this.zipField;
            }
            set {
                this.zipField = value;
                this.RaisePropertyChanged("Zip");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fis.certegy.pca.com/")]
    public partial class DOB : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string yearField;
        
        private string monthField;
        
        private string dayField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Year {
            get {
                return this.yearField;
            }
            set {
                this.yearField = value;
                this.RaisePropertyChanged("Year");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Month {
            get {
                return this.monthField;
            }
            set {
                this.monthField = value;
                this.RaisePropertyChanged("Month");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Day {
            get {
                return this.dayField;
            }
            set {
                this.dayField = value;
                this.RaisePropertyChanged("Day");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fis.certegy.pca.com/")]
    public partial class Enrollment : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string lastNameField;
        
        private string firstNameField;
        
        private DOB dOBField;
        
        private string phoneField;
        
        private Address addressField;
        
        private ID idField;
        
        private byte[] swipedIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
                this.RaisePropertyChanged("LastName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
                this.RaisePropertyChanged("FirstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public DOB DOB {
            get {
                return this.dOBField;
            }
            set {
                this.dOBField = value;
                this.RaisePropertyChanged("DOB");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
                this.RaisePropertyChanged("Phone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public Address Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("Address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public ID ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=6)]
        public byte[] SwipedID {
            get {
                return this.swipedIDField;
            }
            set {
                this.swipedIDField = value;
                this.RaisePropertyChanged("SwipedID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AuthorizeRequest", WrapperNamespace="http://fis.certegy.pca.com/", IsWrapped=true)]
    public partial class authorizeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fis.certegy.pca.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TransID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fis.certegy.pca.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Version;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fis.certegy.pca.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TranType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fis.certegy.pca.com/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SiteID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fis.certegy.pca.com/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SSN;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fis.certegy.pca.com/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MGI.Cxn.Check.Certegy.Certegy.Check Check;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fis.certegy.pca.com/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MGI.Cxn.Check.Certegy.Certegy.Enrollment Enroll;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fis.certegy.pca.com/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MGI.Cxn.Check.Certegy.Certegy.Device Device;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fis.certegy.pca.com/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute("Roundtrip", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] Roundtrip;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fis.certegy.pca.com/", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute("Custom", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MGI.Cxn.Check.Certegy.Certegy.Custom[] Custom;
        
        public authorizeRequest() {
        }
        
        public authorizeRequest(string TransID, decimal Version, string TranType, string SiteID, string SSN, MGI.Cxn.Check.Certegy.Certegy.Check Check, MGI.Cxn.Check.Certegy.Certegy.Enrollment Enroll, MGI.Cxn.Check.Certegy.Certegy.Device Device, string[] Roundtrip, MGI.Cxn.Check.Certegy.Certegy.Custom[] Custom) {
            this.TransID = TransID;
            this.Version = Version;
            this.TranType = TranType;
            this.SiteID = SiteID;
            this.SSN = SSN;
            this.Check = Check;
            this.Enroll = Enroll;
            this.Device = Device;
            this.Roundtrip = Roundtrip;
            this.Custom = Custom;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AuthorizeResponse", WrapperNamespace="http://fis.certegy.pca.com/", IsWrapped=true)]
    public partial class authorizeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fis.certegy.pca.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TransID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fis.certegy.pca.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ResponseCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fis.certegy.pca.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ApprovalNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fis.certegy.pca.com/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SettlementID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fis.certegy.pca.com/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute("Roundtrip", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] Roundtrip;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fis.certegy.pca.com/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute("Custom", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MGI.Cxn.Check.Certegy.Certegy.Custom[] Custom;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fis.certegy.pca.com/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CertegyUID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fis.certegy.pca.com/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CheckABA;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fis.certegy.pca.com/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CheckAcct;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fis.certegy.pca.com/", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CheckNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fis.certegy.pca.com/", Order=10)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CheckType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fis.certegy.pca.com/", Order=11)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Fee;
        
        public authorizeResponse() {
        }
        
        public authorizeResponse(string TransID, string ResponseCode, string ApprovalNumber, string SettlementID, string[] Roundtrip, MGI.Cxn.Check.Certegy.Certegy.Custom[] Custom, string CertegyUID, string CheckABA, string CheckAcct, string CheckNumber, string CheckType, decimal Fee) {
            this.TransID = TransID;
            this.ResponseCode = ResponseCode;
            this.ApprovalNumber = ApprovalNumber;
            this.SettlementID = SettlementID;
            this.Roundtrip = Roundtrip;
            this.Custom = Custom;
            this.CertegyUID = CertegyUID;
            this.CheckABA = CheckABA;
            this.CheckAcct = CheckAcct;
            this.CheckNumber = CheckNumber;
            this.CheckType = CheckType;
            this.Fee = Fee;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReverseRequest", WrapperNamespace="http://fis.certegy.pca.com/", IsWrapped=true)]
    public partial class reverseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fis.certegy.pca.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TransID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fis.certegy.pca.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Version;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fis.certegy.pca.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SiteID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fis.certegy.pca.com/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SSN;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fis.certegy.pca.com/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MGI.Cxn.Check.Certegy.Certegy.Check Check;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fis.certegy.pca.com/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute("Roundtrip", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] Roundtrip;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fis.certegy.pca.com/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute("Custom", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MGI.Cxn.Check.Certegy.Certegy.Custom[] Custom;
        
        public reverseRequest() {
        }
        
        public reverseRequest(string TransID, decimal Version, string SiteID, string SSN, MGI.Cxn.Check.Certegy.Certegy.Check Check, string[] Roundtrip, MGI.Cxn.Check.Certegy.Certegy.Custom[] Custom) {
            this.TransID = TransID;
            this.Version = Version;
            this.SiteID = SiteID;
            this.SSN = SSN;
            this.Check = Check;
            this.Roundtrip = Roundtrip;
            this.Custom = Custom;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReverseResponse", WrapperNamespace="http://fis.certegy.pca.com/", IsWrapped=true)]
    public partial class reverseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fis.certegy.pca.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TransID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fis.certegy.pca.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ResponseCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fis.certegy.pca.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute("Roundtrip", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] Roundtrip;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fis.certegy.pca.com/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute("Custom", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MGI.Cxn.Check.Certegy.Certegy.Custom[] Custom;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fis.certegy.pca.com/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CertegyUID;
        
        public reverseResponse() {
        }
        
        public reverseResponse(string TransID, string ResponseCode, string[] Roundtrip, MGI.Cxn.Check.Certegy.Certegy.Custom[] Custom, string CertegyUID) {
            this.TransID = TransID;
            this.ResponseCode = ResponseCode;
            this.Roundtrip = Roundtrip;
            this.Custom = Custom;
            this.CertegyUID = CertegyUID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EchoRequest", WrapperNamespace="http://fis.certegy.pca.com/", IsWrapped=true)]
    public partial class echoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fis.certegy.pca.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SiteID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fis.certegy.pca.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer")]
        public string EchoNumber;
        
        public echoRequest() {
        }
        
        public echoRequest(string SiteID, string EchoNumber) {
            this.SiteID = SiteID;
            this.EchoNumber = EchoNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EchoResponse", WrapperNamespace="http://fis.certegy.pca.com/", IsWrapped=true)]
    public partial class echoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fis.certegy.pca.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SiteID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fis.certegy.pca.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer")]
        public string EchoNumber;
        
        public echoResponse() {
        }
        
        public echoResponse(string SiteID, string EchoNumber) {
            this.SiteID = SiteID;
            this.EchoNumber = EchoNumber;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PCAChannel : MGI.Cxn.Check.Certegy.Certegy.PCA, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PCAClient : System.ServiceModel.ClientBase<MGI.Cxn.Check.Certegy.Certegy.PCA>, MGI.Cxn.Check.Certegy.Certegy.PCA {
        
        public PCAClient() {
        }
        
        public PCAClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PCAClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PCAClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PCAClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MGI.Cxn.Check.Certegy.Certegy.authorizeResponse MGI.Cxn.Check.Certegy.Certegy.PCA.authorize(MGI.Cxn.Check.Certegy.Certegy.authorizeRequest request) {
            return base.Channel.authorize(request);
        }
        
        public string authorize(
                    ref string TransID, 
                    decimal Version, 
                    string TranType, 
                    string SiteID, 
                    string SSN, 
                    MGI.Cxn.Check.Certegy.Certegy.Check Check, 
                    MGI.Cxn.Check.Certegy.Certegy.Enrollment Enroll, 
                    MGI.Cxn.Check.Certegy.Certegy.Device Device, 
                    ref string[] Roundtrip, 
                    ref MGI.Cxn.Check.Certegy.Certegy.Custom[] Custom, 
                    out string ApprovalNumber, 
                    out string SettlementID, 
                    out string CertegyUID, 
                    out string CheckABA, 
                    out string CheckAcct, 
                    out string CheckNumber, 
                    out string CheckType, 
                    out decimal Fee) {
            MGI.Cxn.Check.Certegy.Certegy.authorizeRequest inValue = new MGI.Cxn.Check.Certegy.Certegy.authorizeRequest();
            inValue.TransID = TransID;
            inValue.Version = Version;
            inValue.TranType = TranType;
            inValue.SiteID = SiteID;
            inValue.SSN = SSN;
            inValue.Check = Check;
            inValue.Enroll = Enroll;
            inValue.Device = Device;
            inValue.Roundtrip = Roundtrip;
            inValue.Custom = Custom;
            MGI.Cxn.Check.Certegy.Certegy.authorizeResponse retVal = ((MGI.Cxn.Check.Certegy.Certegy.PCA)(this)).authorize(inValue);
            TransID = retVal.TransID;
            ApprovalNumber = retVal.ApprovalNumber;
            SettlementID = retVal.SettlementID;
            Roundtrip = retVal.Roundtrip;
            Custom = retVal.Custom;
            CertegyUID = retVal.CertegyUID;
            CheckABA = retVal.CheckABA;
            CheckAcct = retVal.CheckAcct;
            CheckNumber = retVal.CheckNumber;
            CheckType = retVal.CheckType;
            Fee = retVal.Fee;
            return retVal.ResponseCode;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MGI.Cxn.Check.Certegy.Certegy.reverseResponse MGI.Cxn.Check.Certegy.Certegy.PCA.reverse(MGI.Cxn.Check.Certegy.Certegy.reverseRequest request) {
            return base.Channel.reverse(request);
        }
        
        public string reverse(ref string TransID, decimal Version, string SiteID, string SSN, MGI.Cxn.Check.Certegy.Certegy.Check Check, ref string[] Roundtrip, ref MGI.Cxn.Check.Certegy.Certegy.Custom[] Custom, out string CertegyUID) {
            MGI.Cxn.Check.Certegy.Certegy.reverseRequest inValue = new MGI.Cxn.Check.Certegy.Certegy.reverseRequest();
            inValue.TransID = TransID;
            inValue.Version = Version;
            inValue.SiteID = SiteID;
            inValue.SSN = SSN;
            inValue.Check = Check;
            inValue.Roundtrip = Roundtrip;
            inValue.Custom = Custom;
            MGI.Cxn.Check.Certegy.Certegy.reverseResponse retVal = ((MGI.Cxn.Check.Certegy.Certegy.PCA)(this)).reverse(inValue);
            TransID = retVal.TransID;
            Roundtrip = retVal.Roundtrip;
            Custom = retVal.Custom;
            CertegyUID = retVal.CertegyUID;
            return retVal.ResponseCode;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MGI.Cxn.Check.Certegy.Certegy.echoResponse MGI.Cxn.Check.Certegy.Certegy.PCA.echo(MGI.Cxn.Check.Certegy.Certegy.echoRequest request) {
            return base.Channel.echo(request);
        }
        
        public void echo(ref string SiteID, ref string EchoNumber) {
            MGI.Cxn.Check.Certegy.Certegy.echoRequest inValue = new MGI.Cxn.Check.Certegy.Certegy.echoRequest();
            inValue.SiteID = SiteID;
            inValue.EchoNumber = EchoNumber;
            MGI.Cxn.Check.Certegy.Certegy.echoResponse retVal = ((MGI.Cxn.Check.Certegy.Certegy.PCA)(this)).echo(inValue);
            SiteID = retVal.SiteID;
            EchoNumber = retVal.EchoNumber;
        }
    }
}
