SET NOCOUNT ON

DECLARE @DISPSEQ INT, @MAINMODULEID INT, @APPLICATIONID INT, @MODULEID INT, @FUNCID1 int, @FUNCID2 int, @FUNCID3 int, @FUNCID4 int, @FUNCID5 int, @FUNCID6 int, @FUNCID7 int, @ROLEID INT, @PRIVILEGEID INT 

SELECT @APPLICATIONID = APPLICATIONID FROM TBL_KS_APPLICATION WHERE APPLICATIONNAME ='Payments'
SELECT @MAINMODULEID = MAINMODULEID FROM TBL_KS_MAINMODULE WHERE MAINMODULENAME ='Payments'
SELECT @DISPSEQ = ISNULL(MAX(DISPLAYSEQUENCE),0) + 10 FROM TBL_KS_MODULE 

IF NOT EXISTS(Select 1 FROM TBL_KS_MODULE Where ApplicationID = @APPLICATIONID And MODULENAME = 'ModulePaymentProfile')
	INSERT Into TBL_KS_MODULE (APPLICATIONID,MODULENAME,ABBREV,DESCRIPTION,DISPLAYSEQUENCE,ISACTIVE,MAINMODULEID) 
		VALUES (@APPLICATIONID,'ModulePaymentProfile','MPP','Module Payment Profile', @DISPSEQ, 1 ,@MAINMODULEID) 

SELECT @DISPSEQ = ISNULL(MAX(DISPLAYSEQUENCE),0)  FROM TBL_KS_PRIVILEGE
SELECT @MODULEID = MODULEID From TBL_KS_MODULE Where ApplicationID = @APPLICATIONID And MODULENAME = 'ModulePaymentProfile' 
SELECT @FUNCID1 = FUNCTIONID FROM TBL_KS_FUNCTION WHERE FUNCTIONNAME = 'Read'
SELECT @FUNCID2 = FUNCTIONID FROM TBL_KS_FUNCTION WHERE FUNCTIONNAME = 'Add'
SELECT @FUNCID3 = FUNCTIONID FROM TBL_KS_FUNCTION WHERE FUNCTIONNAME = 'Edit'
SELECT @FUNCID4 = FUNCTIONID FROM TBL_KS_FUNCTION WHERE FUNCTIONNAME = 'Delete'
SELECT @FUNCID5 = FUNCTIONID FROM TBL_KS_FUNCTION WHERE FUNCTIONNAME = 'Print'
SELECT @FUNCID6 = FUNCTIONID FROM TBL_KS_FUNCTION WHERE FUNCTIONNAME = 'Export'
SELECT @FUNCID7 = FUNCTIONID FROM TBL_KS_FUNCTION WHERE FUNCTIONNAME = 'Execute'

IF NOT EXISTS(Select 1 FROM TBL_KS_PRIVILEGE Where PRIVILEGENAME = 'PaymentProfile_Read')
	INSERT into TBL_KS_PRIVILEGE (PRIVILEGENAME, DESCRIPTION, DISPLAYSEQUENCE, MODULEID, FUNCTIONID) VALUES ( 'PaymentProfile_Read','Allows the ability to Read for Payment Profile', @DISPSEQ+ 10,@MODULEID,@FUNCID1)

IF NOT EXISTS(Select 1 FROM TBL_KS_PRIVILEGE Where PRIVILEGENAME = 'PaymentProfile_Add')
	INSERT into TBL_KS_PRIVILEGE (PRIVILEGENAME, DESCRIPTION, DISPLAYSEQUENCE, MODULEID, FUNCTIONID) VALUES ( 'PaymentProfile_Add','Allows the ability to Add for Payment Profile', @DISPSEQ+ 10,@MODULEID,@FUNCID2)

IF NOT EXISTS(Select 1 FROM TBL_KS_PRIVILEGE Where PRIVILEGENAME = 'PaymentProfile_Edit')
	INSERT into TBL_KS_PRIVILEGE (PRIVILEGENAME, DESCRIPTION, DISPLAYSEQUENCE, MODULEID, FUNCTIONID) VALUES ( 'PaymentProfile_Edit','Allows the ability to Edit for Payment Profile', @DISPSEQ+ 10,@MODULEID,@FUNCID3)

IF NOT EXISTS(Select 1 FROM TBL_KS_PRIVILEGE Where PRIVILEGENAME = 'PaymentProfile_Delete')
	INSERT into TBL_KS_PRIVILEGE (PRIVILEGENAME, DESCRIPTION, DISPLAYSEQUENCE, MODULEID, FUNCTIONID) VALUES ( 'PaymentProfile_Delete','Allows the ability to Delete Payment Profile', @DISPSEQ+ 10,@MODULEID,@FUNCID4)

IF NOT EXISTS(Select 1 FROM TBL_KS_PRIVILEGE Where PRIVILEGENAME = 'PaymentProfile_Print')
	INSERT into TBL_KS_PRIVILEGE (PRIVILEGENAME, DESCRIPTION, DISPLAYSEQUENCE, MODULEID, FUNCTIONID) VALUES ( 'PaymentProfile_Print','Allows the ability to Print Payment Profile', @DISPSEQ+ 10,@MODULEID,@FUNCID5)

IF NOT EXISTS(Select 1 FROM TBL_KS_PRIVILEGE Where PRIVILEGENAME = 'PaymentProfile_Export')
	INSERT into TBL_KS_PRIVILEGE (PRIVILEGENAME, DESCRIPTION, DISPLAYSEQUENCE, MODULEID, FUNCTIONID) VALUES ( 'PaymentProfile_Export','Allows the ability to Export Payment Profile', @DISPSEQ+ 10,@MODULEID,@FUNCID6)

IF NOT EXISTS(Select 1 FROM TBL_KS_PRIVILEGE Where PRIVILEGENAME = 'PaymentProfile_Execute')
	INSERT into TBL_KS_PRIVILEGE (PRIVILEGENAME, DESCRIPTION, DISPLAYSEQUENCE, MODULEID, FUNCTIONID) VALUES ( 'PaymentProfile_Execute','Allows the ability to Execute Payment Profile', @DISPSEQ+ 10,@MODULEID,@FUNCID7)

--Client Account Manager (Read And Edit)
SELECT @ROLEID = ROLEID FROM TBL_KS_ROLE WHERE RoleName = 'Client Account Manager'
SELECT @PRIVILEGEID = PRIVILEGEID FROM TBL_KS_PRIVILEGE WHERE PRIVILEGENAME = 'PaymentProfile_Read' 
IF NOT EXISTS(Select ROLEID FROM TBL_KS_ROLEPRIVILEGE Where ROLEID=@ROLEID AND PRIVILEGEID=@PRIVILEGEID)
    INSERT into TBL_KS_ROLEPRIVILEGE (ROLEID, PRIVILEGEID) Values (@ROLEID, @PRIVILEGEID)
SELECT @PRIVILEGEID = PRIVILEGEID FROM TBL_KS_PRIVILEGE WHERE PRIVILEGENAME = 'PaymentProfile_Edit' 
IF NOT EXISTS(Select ROLEID FROM TBL_KS_ROLEPRIVILEGE Where ROLEID=@ROLEID AND PRIVILEGEID=@PRIVILEGEID)
    INSERT into TBL_KS_ROLEPRIVILEGE (ROLEID, PRIVILEGEID) Values (@ROLEID, @PRIVILEGEID)

--Manager - Trust Administration (Read And Edit)
SELECT @ROLEID = ROLEID FROM TBL_KS_ROLE WHERE RoleName = 'Manager - Trust Administration'
SELECT @PRIVILEGEID = PRIVILEGEID FROM TBL_KS_PRIVILEGE WHERE PRIVILEGENAME = 'PaymentProfile_Read' 
IF NOT EXISTS(Select ROLEID FROM TBL_KS_ROLEPRIVILEGE Where ROLEID=@ROLEID AND PRIVILEGEID=@PRIVILEGEID)
    INSERT into TBL_KS_ROLEPRIVILEGE (ROLEID, PRIVILEGEID) Values (@ROLEID, @PRIVILEGEID)
SELECT @PRIVILEGEID = PRIVILEGEID FROM TBL_KS_PRIVILEGE WHERE PRIVILEGENAME = 'PaymentProfile_Edit' 
IF NOT EXISTS(Select ROLEID FROM TBL_KS_ROLEPRIVILEGE Where ROLEID=@ROLEID AND PRIVILEGEID=@PRIVILEGEID)
    INSERT into TBL_KS_ROLEPRIVILEGE (ROLEID, PRIVILEGEID) Values (@ROLEID, @PRIVILEGEID)

--Trust Administrator (Read And Edit)
SELECT @ROLEID = ROLEID FROM TBL_KS_ROLE WHERE RoleName = 'Trust Administrator'
SELECT @PRIVILEGEID = PRIVILEGEID FROM TBL_KS_PRIVILEGE WHERE PRIVILEGENAME = 'PaymentProfile_Read' 
IF NOT EXISTS(Select ROLEID FROM TBL_KS_ROLEPRIVILEGE Where ROLEID=@ROLEID AND PRIVILEGEID=@PRIVILEGEID)
    INSERT into TBL_KS_ROLEPRIVILEGE (ROLEID, PRIVILEGEID) Values (@ROLEID, @PRIVILEGEID)
SELECT @PRIVILEGEID = PRIVILEGEID FROM TBL_KS_PRIVILEGE WHERE PRIVILEGENAME = 'PaymentProfile_Edit' 
IF NOT EXISTS(Select ROLEID FROM TBL_KS_ROLEPRIVILEGE Where ROLEID=@ROLEID AND PRIVILEGEID=@PRIVILEGEID)
    INSERT into TBL_KS_ROLEPRIVILEGE (ROLEID, PRIVILEGEID) Values (@ROLEID, @PRIVILEGEID)

--Client Transition Manager (Read And Edit)
SELECT @ROLEID = ROLEID FROM TBL_KS_ROLE WHERE RoleName = 'Client Transition Manager'
SELECT @PRIVILEGEID = PRIVILEGEID FROM TBL_KS_PRIVILEGE WHERE PRIVILEGENAME = 'PaymentProfile_Read' 
IF NOT EXISTS(Select ROLEID FROM TBL_KS_ROLEPRIVILEGE Where ROLEID=@ROLEID AND PRIVILEGEID=@PRIVILEGEID)
    INSERT into TBL_KS_ROLEPRIVILEGE (ROLEID, PRIVILEGEID) Values (@ROLEID, @PRIVILEGEID)
SELECT @PRIVILEGEID = PRIVILEGEID FROM TBL_KS_PRIVILEGE WHERE PRIVILEGENAME = 'PaymentProfile_Edit' 
IF NOT EXISTS(Select ROLEID FROM TBL_KS_ROLEPRIVILEGE Where ROLEID=@ROLEID AND PRIVILEGEID=@PRIVILEGEID)
    INSERT into TBL_KS_ROLEPRIVILEGE (ROLEID, PRIVILEGEID) Values (@ROLEID, @PRIVILEGEID)

--PFA Manager (Read And Edit)
SELECT @ROLEID = ROLEID FROM TBL_KS_ROLE WHERE RoleName = 'PFA Manager'
SELECT @PRIVILEGEID = PRIVILEGEID FROM TBL_KS_PRIVILEGE WHERE PRIVILEGENAME = 'PaymentProfile_Read' 
IF NOT EXISTS(Select ROLEID FROM TBL_KS_ROLEPRIVILEGE Where ROLEID=@ROLEID AND PRIVILEGEID=@PRIVILEGEID)
    INSERT into TBL_KS_ROLEPRIVILEGE (ROLEID, PRIVILEGEID) Values (@ROLEID, @PRIVILEGEID)

--Pooled Fund Administrator (Read And Edit)
SELECT @ROLEID = ROLEID FROM TBL_KS_ROLE WHERE RoleName = 'Pooled Fund Administrator'
SELECT @PRIVILEGEID = PRIVILEGEID FROM TBL_KS_PRIVILEGE WHERE PRIVILEGENAME = 'PaymentProfile_Read' 
IF NOT EXISTS(Select ROLEID FROM TBL_KS_ROLEPRIVILEGE Where ROLEID=@ROLEID AND PRIVILEGEID=@PRIVILEGEID)
    INSERT into TBL_KS_ROLEPRIVILEGE (ROLEID, PRIVILEGEID) Values (@ROLEID, @PRIVILEGEID)

--Pooled Fund Administrator (Read And Edit)
SELECT @ROLEID = ROLEID FROM TBL_KS_ROLE WHERE RoleName = 'Pooled Fund Administrator'
SELECT @PRIVILEGEID = PRIVILEGEID FROM TBL_KS_PRIVILEGE WHERE PRIVILEGENAME = 'PaymentProfile_Read' 
IF NOT EXISTS(Select ROLEID FROM TBL_KS_ROLEPRIVILEGE Where ROLEID=@ROLEID AND PRIVILEGEID=@PRIVILEGEID)
    INSERT into TBL_KS_ROLEPRIVILEGE (ROLEID, PRIVILEGEID) Values (@ROLEID, @PRIVILEGEID)

--Production Services (Read And Edit)
SELECT @ROLEID = ROLEID FROM TBL_KS_ROLE WHERE RoleName = 'Production Services'
SELECT @PRIVILEGEID = PRIVILEGEID FROM TBL_KS_PRIVILEGE WHERE PRIVILEGENAME = 'PaymentProfile_Read' 
IF NOT EXISTS(Select ROLEID FROM TBL_KS_ROLEPRIVILEGE Where ROLEID=@ROLEID AND PRIVILEGEID=@PRIVILEGEID)
    INSERT into TBL_KS_ROLEPRIVILEGE (ROLEID, PRIVILEGEID) Values (@ROLEID, @PRIVILEGEID)

--Paragon View Only (Read And Edit)
SELECT @ROLEID = ROLEID FROM TBL_KS_ROLE WHERE RoleName = 'Paragon View Only'
SELECT @PRIVILEGEID = PRIVILEGEID FROM TBL_KS_PRIVILEGE WHERE PRIVILEGENAME = 'PaymentProfile_Read' 
IF NOT EXISTS(Select ROLEID FROM TBL_KS_ROLEPRIVILEGE Where ROLEID=@ROLEID AND PRIVILEGEID=@PRIVILEGEID)
    INSERT into TBL_KS_ROLEPRIVILEGE (ROLEID, PRIVILEGEID) Values (@ROLEID, @PRIVILEGEID)

--IT (Read And Edit)
SELECT @ROLEID = ROLEID FROM TBL_KS_ROLE WHERE RoleName = 'IT'
SELECT @PRIVILEGEID = PRIVILEGEID FROM TBL_KS_PRIVILEGE WHERE PRIVILEGENAME = 'PaymentProfile_Read' 
IF NOT EXISTS(Select ROLEID FROM TBL_KS_ROLEPRIVILEGE Where ROLEID=@ROLEID AND PRIVILEGEID=@PRIVILEGEID)
    INSERT into TBL_KS_ROLEPRIVILEGE (ROLEID, PRIVILEGEID) Values (@ROLEID, @PRIVILEGEID)

--Payment Administrator (Read And Edit)
SELECT @ROLEID = ROLEID FROM TBL_KS_ROLE WHERE RoleName = 'Payment Administrator'
SELECT @PRIVILEGEID = PRIVILEGEID FROM TBL_KS_PRIVILEGE WHERE PRIVILEGENAME = 'PaymentProfile_Read' 
IF NOT EXISTS(Select ROLEID FROM TBL_KS_ROLEPRIVILEGE Where ROLEID=@ROLEID AND PRIVILEGEID=@PRIVILEGEID)
    INSERT into TBL_KS_ROLEPRIVILEGE (ROLEID, PRIVILEGEID) Values (@ROLEID, @PRIVILEGEID)

SET NOCOUNT OFF