-- ============================================================
-- Author:	   <Swarnalakshmi>
-- Create date: <09/12/2014>
-- Description:	<Alter tWunion_trx_Aud Trigger to add missing columns>
-- Rally ID:	
-- ============================================================
ALTER TRIGGER [dbo].[tWUnion_TrxAud] on [dbo].[tWUnion_Trx] AFTER Insert, Update, Delete
AS
       SET NOCOUNT ON
       Declare @RevisionNo bigint
       select @RevisionNo = isnull(MAX(RevisionNo),0) + 1 from tWUnion_Trx_Aud where 
       Id = (select Id from inserted)
             
       if ((select COUNT(*) from inserted)<>0 and (select COUNT(*) from deleted)>0)
       begin
              insert into tWUnion_Trx_Aud(
						[rowguid],	[Id] ,	[WUnionAccountPK],
						[WUnionRecipientAccountPK],	[OriginatorsPrincipalAmount],	[OriginatingCountryCode],
						[OriginatingCurrencyCode],	[TranascationType],	[PromotionsCode] ,
						[ExchangeRate],	[DestinationPrincipalAmount],	[GrossTotalAmount],
						[Charges],	[TaxAmount],[Mtcn] ,	[DTCreate],
						[DTLastMod],	[PromotionDiscount] ,	[OtherCharges],
						[MoneyTransferKey],	[AdditionalCharges],[DestinationCountryCode] ,
						[DestinationCurrencyCode] ,	[DestinationState] ,	[IsDomesticTransfer] ,
						[IsFixedOnSend],[PhoneNumber],[Url],[AgencyName],[ChannelPartnerId],
						[ProviderId] ,[TestQuestion],[TempMTCN],[ExpectedPayoutStateCode],
						[ExpectedPayoutCityName],[AuditEvent],[DTAudit],[RevisionNo],
						TestAnswer,TestQuestionAvaliable, [GCNumber] ,[SenderName],
						[PdsRequiredFlag],[DfTransactionFlag],[DeliveryServiceName],
						[DTAvailableForPickup],[RecieverFirstName],[RecieverLastName],
						[RecieverSecondLastName],[PromoCodeDescription],[PromoName],
						[PromoMessage],[PromotionError],
						[Sender_ComplianceDetails_ComplianceData_Buffer],[recordingCountryCode],
						[recordingCurrencyCode],[originating_city],[originating_state],
						[municipal_tax],[state_tax],[county_tax],[plus_charges_amount],
						[message_charge],[total_undiscounted_charges],[total_discount],
						[total_discounted_charges],[instant_notification_addl_service_charges],
						[PaySideCharges],[PaySideTax],[AmountToReceiver],[SMSNotificationFlag],
						[PersonalMessage],[DeliveryServiceDesc],[ReferenceNo],[WUCard_TotalPointsEarned],
						[OriginalTransactionID],[TransactionSubType] ,[ReasonCode],[ReasonDescription],
						[Comments],[pay_or_do_not_pay_indicator] ,[OriginalDestinationCountryCode],
						[OriginalDestinationCurrencyCode],[FilingDate],[FilingTime],[PaidDateTime],
						[AvailableForPickup],[DelayHours] ,[AvailableForPickupEST],[DeliveryOption],
						[DeliveryOptionDesc],[PromotionSequenceNo],
						[DTServerCreate],[DTServerLastMod])
						
              select	[rowguid],	[Id] ,	[WUnionAccountPK],
						[WUnionRecipientAccountPK],	[OriginatorsPrincipalAmount],	[OriginatingCountryCode],
						[OriginatingCurrencyCode],	[TranascationType],	[PromotionsCode] ,
						[ExchangeRate],	[DestinationPrincipalAmount],	[GrossTotalAmount],
						[Charges],	[TaxAmount],[Mtcn] ,[DTCreate],
						[DTLastMod],[PromotionDiscount] ,	[OtherCharges],
						[MoneyTransferKey],	[AdditionalCharges],[DestinationCountryCode] ,
						[DestinationCurrencyCode] ,	[DestinationState] ,	[IsDomesticTransfer] ,
						[IsFixedOnSend],[PhoneNumber],[Url],[AgencyName],[ChannelPartnerId],
						[ProviderId] ,[TestQuestion], [TempMTCN],	[ExpectedPayoutStateCode],
						[ExpectedPayoutCityName], 2 as AuditEvent, GETDATE(), @RevisionNo,
					    	TestAnswer,TestQuestionAvaliable,[GCNumber] ,[SenderName],
						[PdsRequiredFlag],[DfTransactionFlag],[DeliveryServiceName],
						[DTAvailableForPickup],[RecieverFirstName],[RecieverLastName],
						[RecieverSecondLastName],[PromoCodeDescription],[PromoName],
						[PromoMessage],[PromotionError],
						[Sender_ComplianceDetails_ComplianceData_Buffer],[recordingCountryCode],
						[recordingCurrencyCode],[originating_city],[originating_state],
						[municipal_tax],[state_tax],[county_tax],[plus_charges_amount],
						[message_charge],[total_undiscounted_charges],[total_discount],
						[total_discounted_charges],[instant_notification_addl_service_charges],
						[PaySideCharges],[PaySideTax],[AmountToReceiver],[SMSNotificationFlag],
						[PersonalMessage],[DeliveryServiceDesc],[ReferenceNo],[WUCard_TotalPointsEarned],
						[OriginalTransactionID],[TransactionSubType] ,[ReasonCode],[ReasonDescription],
						[Comments],[pay_or_do_not_pay_indicator] ,[OriginalDestinationCountryCode],
						[OriginalDestinationCurrencyCode],[FilingDate],[FilingTime],[PaidDateTime],
						[AvailableForPickup],[DelayHours] ,[AvailableForPickupEST],[DeliveryOption],
						[DeliveryOptionDesc],[PromotionSequenceNo],GETDATE() , GETDATE() from inserted
       end
       else if(select COUNT(*) from inserted)>0 and (select COUNT(*) from deleted)=0
       begin
               insert into tWUnion_Trx_Aud( [rowguid],	[Id] ,	[WUnionAccountPK],
						[WUnionRecipientAccountPK],	[OriginatorsPrincipalAmount],	[OriginatingCountryCode],
						[OriginatingCurrencyCode],	[TranascationType],	[PromotionsCode] ,
						[ExchangeRate],	[DestinationPrincipalAmount],	[GrossTotalAmount],
						[Charges],	[TaxAmount],[Mtcn] ,	[DTCreate],
						[DTLastMod],	[PromotionDiscount] ,	[OtherCharges],
						[MoneyTransferKey],	[AdditionalCharges],[DestinationCountryCode] ,
						[DestinationCurrencyCode] ,	[DestinationState] ,	[IsDomesticTransfer] ,
						[IsFixedOnSend],[PhoneNumber],[Url],[AgencyName],[ChannelPartnerId],
						[ProviderId] ,[TestQuestion],[TempMTCN],[ExpectedPayoutStateCode],
						[ExpectedPayoutCityName],[AuditEvent],[DTAudit],[RevisionNo],
						TestAnswer,TestQuestionAvaliable, [GCNumber] ,[SenderName],
						[PdsRequiredFlag],[DfTransactionFlag],[DeliveryServiceName],
						[DTAvailableForPickup],[RecieverFirstName],[RecieverLastName],
						[RecieverSecondLastName],[PromoCodeDescription],[PromoName],
						[PromoMessage],[PromotionError],
						[Sender_ComplianceDetails_ComplianceData_Buffer],[recordingCountryCode],
						[recordingCurrencyCode],[originating_city],[originating_state],
						[municipal_tax],[state_tax],[county_tax],[plus_charges_amount],
						[message_charge],[total_undiscounted_charges],[total_discount],
						[total_discounted_charges],[instant_notification_addl_service_charges],
						[PaySideCharges],[PaySideTax],[AmountToReceiver],[SMSNotificationFlag],
						[PersonalMessage],[DeliveryServiceDesc],[ReferenceNo],[WUCard_TotalPointsEarned],
						[OriginalTransactionID],[TransactionSubType] ,[ReasonCode],[ReasonDescription],
						[Comments],[pay_or_do_not_pay_indicator] ,[OriginalDestinationCountryCode],
						[OriginalDestinationCurrencyCode],[FilingDate],[FilingTime],[PaidDateTime],
						[AvailableForPickup],[DelayHours] ,[AvailableForPickupEST],[DeliveryOption],
						[DeliveryOptionDesc],[PromotionSequenceNo],[DTServerCreate],[DTServerLastMod])
						
              select  [rowguid],	[Id] ,	[WUnionAccountPK],
						[WUnionRecipientAccountPK],	[OriginatorsPrincipalAmount],	[OriginatingCountryCode],
						[OriginatingCurrencyCode],	[TranascationType],	[PromotionsCode] ,
						[ExchangeRate],	[DestinationPrincipalAmount],	[GrossTotalAmount],
						[Charges],	[TaxAmount],[Mtcn] ,[DTCreate],
						[DTLastMod],[PromotionDiscount] ,	[OtherCharges],
						[MoneyTransferKey],	[AdditionalCharges],[DestinationCountryCode] ,
						[DestinationCurrencyCode] ,	[DestinationState] ,	[IsDomesticTransfer] ,
						[IsFixedOnSend],[PhoneNumber],[Url],[AgencyName],[ChannelPartnerId],
						[ProviderId] ,[TestQuestion], [TempMTCN],	[ExpectedPayoutStateCode],
						[ExpectedPayoutCityName], 2 as AuditEvent, GETDATE(), @RevisionNo,
					    	TestAnswer,TestQuestionAvaliable,[GCNumber] ,[SenderName],
						[PdsRequiredFlag],[DfTransactionFlag],[DeliveryServiceName],
						[DTAvailableForPickup],[RecieverFirstName],[RecieverLastName],
						[RecieverSecondLastName],[PromoCodeDescription],[PromoName],
						[PromoMessage],[PromotionError],
						[Sender_ComplianceDetails_ComplianceData_Buffer],[recordingCountryCode],
						[recordingCurrencyCode],[originating_city],[originating_state],
						[municipal_tax],[state_tax],[county_tax],[plus_charges_amount],
						[message_charge],[total_undiscounted_charges],[total_discount],
						[total_discounted_charges],[instant_notification_addl_service_charges],
						[PaySideCharges],[PaySideTax],[AmountToReceiver],[SMSNotificationFlag],
						[PersonalMessage],[DeliveryServiceDesc],[ReferenceNo],[WUCard_TotalPointsEarned],
						[OriginalTransactionID],[TransactionSubType] ,[ReasonCode],[ReasonDescription],
						[Comments],[pay_or_do_not_pay_indicator] ,[OriginalDestinationCountryCode],
						[OriginalDestinationCurrencyCode],[FilingDate],[FilingTime],[PaidDateTime],
						[AvailableForPickup],[DelayHours] ,[AvailableForPickupEST],[DeliveryOption],
						[DeliveryOptionDesc],[PromotionSequenceNo],GETDATE() , GETDATE() from inserted
       end
       else if(select COUNT(*) from deleted)>0
       begin
              insert into tWUnion_Trx_Aud(
						[rowguid],	[Id] ,	[WUnionAccountPK],
						[WUnionRecipientAccountPK],	[OriginatorsPrincipalAmount],	[OriginatingCountryCode],
						[OriginatingCurrencyCode],	[TranascationType],	[PromotionsCode] ,
						[ExchangeRate],	[DestinationPrincipalAmount],	[GrossTotalAmount],
						[Charges],	[TaxAmount],[Mtcn] ,[DTCreate],
						[DTLastMod],	[PromotionDiscount] ,[OtherCharges],
						[MoneyTransferKey],	[AdditionalCharges],[DestinationCountryCode] ,
						[DestinationCurrencyCode] ,	[DestinationState] ,	[IsDomesticTransfer] ,
						[IsFixedOnSend],[PhoneNumber],[Url],[AgencyName],[ChannelPartnerId],
						[ProviderId] ,[TestQuestion],[TempMTCN],	[ExpectedPayoutStateCode],
						[ExpectedPayoutCityName],[AuditEvent],[DTAudit],[RevisionNo],
						TestAnswer,TestQuestionAvaliable,[GCNumber] ,[SenderName],
						[PdsRequiredFlag],[DfTransactionFlag],[DeliveryServiceName],
						[DTAvailableForPickup],[RecieverFirstName],[RecieverLastName],
						[RecieverSecondLastName],[PromoCodeDescription],[PromoName],	
						[PromoMessage],[PromotionError],
						[Sender_ComplianceDetails_ComplianceData_Buffer],[recordingCountryCode],
						[recordingCurrencyCode],[originating_city],[originating_state],
						[municipal_tax],[state_tax],[county_tax],[plus_charges_amount],
						[message_charge],[total_undiscounted_charges],[total_discount],
						[total_discounted_charges],[instant_notification_addl_service_charges],
						[PaySideCharges],[PaySideTax],[AmountToReceiver],[SMSNotificationFlag],
						[PersonalMessage],[DeliveryServiceDesc],[ReferenceNo],[WUCard_TotalPointsEarned],
						[OriginalTransactionID],[TransactionSubType] ,[ReasonCode],[ReasonDescription],
						[Comments],[pay_or_do_not_pay_indicator] ,[OriginalDestinationCountryCode],
						[OriginalDestinationCurrencyCode],[FilingDate],[FilingTime],[PaidDateTime],
						[AvailableForPickup],[DelayHours] ,[AvailableForPickupEST],[DeliveryOption],
						[DeliveryOptionDesc],[PromotionSequenceNo],
						[DTServerCreate],[DTServerLastMod])
						
             select [rowguid],	[Id] ,	[WUnionAccountPK],
						[WUnionRecipientAccountPK],	[OriginatorsPrincipalAmount],	[OriginatingCountryCode],
						[OriginatingCurrencyCode],	[TranascationType],	[PromotionsCode] ,
						[ExchangeRate],	[DestinationPrincipalAmount],	[GrossTotalAmount],
						[Charges],	[TaxAmount],[Mtcn] ,[DTCreate],
						[DTLastMod],[PromotionDiscount] ,	[OtherCharges],
						[MoneyTransferKey],	[AdditionalCharges],[DestinationCountryCode] ,
						[DestinationCurrencyCode] ,	[DestinationState] ,	[IsDomesticTransfer] ,
						[IsFixedOnSend],[PhoneNumber],[Url],[AgencyName],[ChannelPartnerId],
						[ProviderId] ,[TestQuestion], [TempMTCN],	[ExpectedPayoutStateCode],
						[ExpectedPayoutCityName], 2 as AuditEvent, GETDATE(), @RevisionNo,
					    	TestAnswer,TestQuestionAvaliable,[GCNumber] ,[SenderName],
						[PdsRequiredFlag],[DfTransactionFlag],[DeliveryServiceName],
						[DTAvailableForPickup],[RecieverFirstName],[RecieverLastName],
						[RecieverSecondLastName],[PromoCodeDescription],[PromoName],
						[PromoMessage],[PromotionError],
						[Sender_ComplianceDetails_ComplianceData_Buffer],[recordingCountryCode],
						[recordingCurrencyCode],[originating_city],[originating_state],
						[municipal_tax],[state_tax],[county_tax],[plus_charges_amount],
						[message_charge],[total_undiscounted_charges],[total_discount],
						[total_discounted_charges],[instant_notification_addl_service_charges],
						[PaySideCharges],[PaySideTax],[AmountToReceiver],[SMSNotificationFlag],
						[PersonalMessage],[DeliveryServiceDesc],[ReferenceNo],[WUCard_TotalPointsEarned],
						[OriginalTransactionID],[TransactionSubType] ,[ReasonCode],[ReasonDescription],
						[Comments],[pay_or_do_not_pay_indicator] ,[OriginalDestinationCountryCode],
						[OriginalDestinationCurrencyCode],[FilingDate],[FilingTime],[PaidDateTime],
						[AvailableForPickup],[DelayHours] ,[AvailableForPickupEST],[DeliveryOption],
						[DeliveryOptionDesc],[PromotionSequenceNo],GETDATE() , GETDATE() from inserted
       END


GO