IF OBJECT_ID(N'dbo.TBL_PartBeneContactLookUp') IS NULL
BEGIN
	CREATE TABLE dbo.TBL_PartBeneContactLookUp (
		ParticipantID INT
		,BENEFICIARYID INT
		,CONTACTID INT
		,CONTACTROLECODE INT
		,CUSTOMERACCOUNTNUMBER VARCHAR(14)
		)
END;
ELSE
BEGIN
	TRUNCATE TABLE dbo.TBL_PartBeneContactLookUp
END;
