//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MGI.Channel.DMS.Web.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExceptionCodes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionCodes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MGI.Channel.DMS.Web.Common.ExceptionCodes", typeof(ExceptionCodes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACTIVATION_FAILED .
        /// </summary>
        public static string _2_1 {
            get {
                return ResourceManager.GetString("2.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVALID_CUSTOMER_DATA_DOB .
        /// </summary>
        public static string _2_10 {
            get {
                return ResourceManager.GetString("2.10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVALID_CUSTOMER_DATA_ID .
        /// </summary>
        public static string _2_11 {
            get {
                return ResourceManager.GetString("2.11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVALID_CUSTOMER_DATA_CHECK_PROFILE .
        /// </summary>
        public static string _2_12 {
            get {
                return ResourceManager.GetString("2.12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVALID_CUSTOMER_DATA_SSN .
        /// </summary>
        public static string _2_13 {
            get {
                return ResourceManager.GetString("2.13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LEAD_NOT_SAVED .
        /// </summary>
        public static string _2_14 {
            get {
                return ResourceManager.GetString("2.14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTACTS_NOT_SAVED .
        /// </summary>
        public static string _2_15 {
            get {
                return ResourceManager.GetString("2.15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID_NOT_SAVED .
        /// </summary>
        public static string _2_16 {
            get {
                return ResourceManager.GetString("2.16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHECK_PROFILE_NOT_SAVED .
        /// </summary>
        public static string _2_17 {
            get {
                return ResourceManager.GetString("2.17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LEAD_NOT_FOUND .
        /// </summary>
        public static string _2_18 {
            get {
                return ResourceManager.GetString("2.18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVALID_CUSTOMER_DATA_REFERRAL_CODE .
        /// </summary>
        public static string _2_19 {
            get {
                return ResourceManager.GetString("2.19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACTIVATION_FAILED_PROSPECT_INCOMPLETE .
        /// </summary>
        public static string _2_2 {
            get {
                return ResourceManager.GetString("2.2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OFAC_WARNING .
        /// </summary>
        public static string _2_3 {
            get {
                return ResourceManager.GetString("2.3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVALID_PIN .
        /// </summary>
        public static string _2_4 {
            get {
                return ResourceManager.GetString("2.4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVALID_CUSTOMER_DATA .
        /// </summary>
        public static string _2_5 {
            get {
                return ResourceManager.GetString("2.5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVALID_CUSTOMER_DATA_NAME .
        /// </summary>
        public static string _2_6 {
            get {
                return ResourceManager.GetString("2.6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVALID_CUSTOMER_DATA_ADDRESS .
        /// </summary>
        public static string _2_7 {
            get {
                return ResourceManager.GetString("2.7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVALID_CUSTOMER_DATA_PHONE .
        /// </summary>
        public static string _2_8 {
            get {
                return ResourceManager.GetString("2.8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVALID_CUSTOMER_DATA_EMAIL .
        /// </summary>
        public static string _2_9 {
            get {
                return ResourceManager.GetString("2.9", resourceCulture);
            }
        }
    }
}
