using System;
using System.Collections.Generic;
using MGI.Channel.Shared.Server.Data;
using MGI.Common.Util;

namespace MGI.Channel.Consumer.Server.Contract
{
	public interface IBillPayService
	{
		#region Biller Related Methods

		/// <summary>
		/// This method is used to get the biller information in billpay page
		/// </summary>
		/// <param name="customerSessionId">This field contains customer session id from web layer</param>
		/// <param name="channelPartnerId">This is channelpartner id</param>
		/// <param name="searchTerm">searchTerm checks with billercode and billername</param>
		/// <param name="mgiContext">This is the common class parameter used to pass supplimental information</param>
		/// <returns>List of product information like its Limits and many more</returns>
		List<MGI.Channel.Shared.Server.Data.Product> GetBillers(long customerSessionId, long channelPartnerId, string searchTerm, MGIContext mgiContext);

		/// <summary>
		/// This method gets the Frequent biller information in billpay page
		/// </summary>
		/// <param name="customerSessionId">This field contains customer session id from web layer</param>
		/// <param name="alloyId">This is autogenerated number which get created on Customer Profile generation</param>
		/// <param name="mgiContext">This is the common class parameter used to pass supplimental information</param>
		/// <returns>List of Frequent Biller</returns>
		List<FavoriteBiller> GetFrequentBillers(long customerSessionId, long alloyId, MGIContext mgiContext);

		/// <summary>
		/// This method is used to Add Favorite Biller, this happens when to a new biller a billpay is done
		/// </summary>
		/// <param name="customerSessionId">This field contains customer session id from web layer</param>
		/// <param name="favoriteBiller">This is has information about biller like account number, provider ID</param>
		/// <param name="mgiContext">This is the common class parameter used to pass supplimental information</param>
		/// <returns></returns>
		void AddFavoriteBiller(long customerSessionId, FavoriteBiller favoriteBiller, MGIContext mgiContext);

		/// <summary>
		/// This method is used to Update Favorite Biller Account Number
		/// </summary>
		/// <param name="customerSessionId">This field contains customer session id from web layer</param>
		/// <param name="billerId">Biller id gets generated as new biller is added</param>
		/// <param name="accountNumber">This has Account Number</param>
		/// <param name="mgiContext">This is the common class parameter used to pass supplimental information</param>
		/// <returns>bool</returns>
		bool UpdateFavoriteBillerAccountNumber(long customerSessionId, long billerId, string accountNumber, MGIContext mgiContext);
		
		/// <summary>
		/// This method is used to Update Favorite Biller Status
		/// </summary>
		/// <param name="customerSessionId">This field contains customer session id from web layer</param>
		/// <param name="billerId">Biller id gets generated as new biller is added</param>
		/// <param name="status">This is has status of the bool</param>
		/// <param name="mgiContext">This is the common class parameter used to pass supplimental information</param>
		/// <returns>bool</returns>
		bool UpdateFavoriteBillerStatus(long customerSessionId, long billerId, bool status, MGIContext mgiContext);

		/// <summary>
		/// This method is used to get biller information like delivery option, message etc
		/// </summary>
		/// <param name="customerSessionId">This field contains customer session id from web layer</param>
		/// <param name="billerNameOrCode">This has biller Name or Code</param>
		/// <param name="mgiContext">This is the common class parameter used to pass supplimental information</param>
		/// <returns>return Biller information like deliveryoption, denominatins and many more</returns>
		BillerInfo GetBillerInfo(long customerSessionId, string billerNameOrCode, MGIContext mgiContext);

		/// <summary>
		/// This method is used to get favorite biller information
		/// </summary>
		/// <param name="customerSessionId">This field contains customer session id from web layer</param>
		/// <param name="billerNameOrCode">This has biller Name or Code</param>
		/// <param name="mgiContext">This is the common class parameter used to pass supplimental information</param>
		/// <returns>return Favorite Biller info like Biller Name, AccountNumber, associated ChannelPartner Id</returns>
		FavoriteBiller GetFavoriteBiller(long customerSessionId, string billerNameOrCode, MGIContext mgiContext);

		/// <summary>
		/// The user / teller will have the ability to delete a specific biller from the Favorite Billers list
		/// </summary>
		/// <param name="customerSessionId">This field contains customer session id from web layer</param>
		/// <param name="billerID">biller ID will help us to disable biller from tCustomerPreferedProducts table</param>
		/// <param name="mgiContext">This is the common class parameter used to pass supplimental information</param>
		/// <returns></returns>
		void DeleteFavoriteBiller(long customerSessionId, long billerID, MGIContext mgiContext);

		#endregion

		#region BillPay Trx Methods

		/// <summary>
		/// The user / teller will have the ability to get fee for specific billpaymeny transaction
		/// </summary>
		/// <param name="customerSessionId">This field contains customer session id from web layer</param>
		/// <param name="billerNameOrCode">This field contains biler Name or biller code</param>
		/// <param name="mgiContext">This is the common class parameter used to pass supplimental information</param>
		/// <returns>return Favorite Biller Fee info</returns>
		BillFee GetBillPaymentFee(long customerSessionId, string billerNameOrCode, string accountNumber, decimal amount, BillerLocation location, MGIContext mgiContext);

		/// <summary>
		/// The user / teller will have dynamic fields generated on the base of selection of BillerCode
		/// </summary>
		/// <param name="customerSessionId">This field contains customer session id from web layer</param>
		/// <param name="billerNameOrCode">This field contains biler Name or biller code</param>
		/// <param name="location">Location information</param>
		/// <param name="mgiContext">This is the common class parameter used to pass supplimental information</param>
		/// <returns>return Dynamic fields value</returns>
		List<Field> GetBillPaymentProviderAttributes(long customerSessionId, string billerNameOrCode, string location, MGIContext mgiContext);

		/// <summary>
		/// The user / teller will validate billpayment
		/// </summary>
		/// <param name="customerSessionId">This field contains customer session id from web layer</param>
		/// <param name="billerID">Biller id gets generated as new biller is added </param>
		/// <param name="mgiContext">This is the common class parameter used to pass supplimental information</param>
		/// <returns>return Transaction ID</returns>
		long ValidateBillPayment(long customerSessionId, BillPayment billPayment, MGIContext mgiContext);

		/// <summary>
		/// The user / teller will get Billers Last Transaction
		/// </summary>
		/// <param name="customerSessionId">This field contains customer session id from web layer</param>
		/// <param name="billerCode">This contains billercode</param>
		/// <param name="alloyId">This is autogenerated number which get created on Customer Profile generation</param>
		/// <param name="mgiContext">This is the common class parameter used to pass supplimental information</param>
		/// <returns>return Billers Last Transaction</returns>
		BillPayTransaction GetBillerLastTransaction(long customerSessionId, string billerCode, long alloyId, MGIContext mgiContext);

		#endregion

	}
}
