-- ============================================================
-- Author:		<Swarnalakshmi>
-- Create date: <07/28/2014>
-- Description:	<CREATE Table for MoneyGram Transfer Transaction Audit Table> 
-- Rally ID:	<NA>
-- ============================================================

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[tMGram_Transfer_Trx_Aud]') AND type in (N'U'))
DROP TABLE [dbo].[tMGram_Transfer_Trx_Aud]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[tMGram_Transfer_Trx_Aud](
	[rowguid] [uniqueidentifier] NULL,
	[Id] [bigint] NULL,
	[Amount] [decimal](18, 2) NULL,
	[FeeAmount] [decimal](18, 2) NULL,
	[DestinationCountry] [varchar](50) NULL,
	[DestinationState] [varchar](50) NULL,
	[DeliveryOption] [varchar](50) NULL,
	[DeliveryOptionDesc] [varchar](50) NULL,
	[ReceiveCurrency] [varchar](10) NULL,
	[SenderFirstName] [varchar](50) NULL,
	[SenderLastName] [varchar](50) NULL,
	[SenderMiddleName] [varchar](50) NULL,
	[SenderLastName2] [varchar](50) NULL,
	[SenderAddress] [varchar](50) NULL,
	[SenderAddress2] [varchar](50) NULL,
	[SenderAddress3] [varchar](50) NULL,
	[SenderCity] [varchar](50) NULL,
	[SenderState] [varchar](50) NULL,
	[SenderZipCode] [varchar](20) NULL,
	[SenderCountry] [varchar](50) NULL,
	[SenderHomePhone] [varchar](20) NULL,
	[SenderPhotoIdType] [varchar](50) NULL,
	[SenderPhotoIdNumber] [varchar](50) NULL,
	[SenderPhotoIdState] [varchar](50) NULL,
	[SenderPhotoIdCountry] [varchar](50) NULL,
	[SenderLegalIdType] [varchar](50) NULL,
	[SenderLegalIdNumber] [varchar](50) NULL,
	[SenderOccupation] [varchar](50) NULL,
	[SenderBirthCity] [varchar](50) NULL,
	[SenderBirthCountry] [varchar](50) NULL,
	[SenderPassportIssueDate] [varchar](50) NULL,
	[SenderPassportIssueCity] [varchar](50) NULL,
	[SenderPassportIssueCountry] [varchar](50) NULL,
	[SenderLegalIdIssueCountry] [varchar](50) NULL,
	[SenderEmailAddress] [varchar](50) NULL,
	[SenderMobilePhone] [varchar](50) NULL,
	[SenderPhotoIdExpDate] [datetime] NULL,
	[SenderPhotoIdIssueDate] [datetime] NULL,
	[SenderPhotoIdStored] [bit] NULL,
	[SenderNationalityCountry] [varchar](50) NULL,
	[SenderNationalityAtBirthCountry] [varchar](50) NULL,
	[ReceiverFirstName] [varchar](50) NULL,
	[ReceiverLastName] [varchar](50) NULL,
	[ReceiverMiddleName] [varchar](50) NULL,
	[ReceiverLastName2] [varchar](50) NULL,
	[ReceiverAddress] [varchar](50) NULL,
	[ReceiverAddress2] [varchar](50) NULL,
	[ReceiverAddress3] [varchar](50) NULL,
	[ReceiverCity] [varchar](50) NULL,
	[ReceiverState] [varchar](50) NULL,
	[ReceiverCountry] [varchar](50) NULL,
	[ReceiverZipCode] [varchar](50) NULL,
	[ReceiverPhone] [varchar](50) NULL,
	[PrimaryReceiptLanguage] [varchar](20) NULL,
	[SecondaryReceiptLanguage] [varchar](20) NULL,
	[PromoCodeValues_PromoCode] [varchar](20) NULL,
	[PromotionDiscount] [decimal](18, 2) NULL,
	[PromotionErrorCodeMessage_PrimaryLanguage] [varchar](200) NULL,
	[PromotionErrorCode] [varchar](20) NULL,
	[PromotionDiscountId] [varchar](20) NULL,
	[PromotionCategoryId] [varchar](20) NULL,
	[PromotionDiscountAmount] [decimal](18, 2) NULL,
	[GrossTotalAmount] [decimal](18, 2) NULL,
	[TaxAmount] [decimal](18, 2) NULL,
	[ReceiveAmount] [decimal](18, 2) NULL,
	[EstimatedReceiveAmount] [decimal](18, 2) NULL,
	[EstimatedExchangeRate] [decimal](18, 2) NULL,
	[ReceiveAmountAltered] [bit] NULL,
	[RevisedInformationalFee] [bit] NULL,
	[SendAmountAltered] [bit] NULL,
	[TotalSendFees] [decimal](18, 2) NULL,
	[TotalDiscountAmount] [decimal](18, 2) NULL,
	[TotalSendTaxes] [decimal](18, 2) NULL,
	[TotalAmountToCollect] [decimal](18, 2) NULL,
	[DetailSendAmounts_mgiNonDiscountedSendFee] [decimal](18, 2) NULL,
	[DetailSendAmounts_totalNonDiscountedFees] [decimal](18, 2) NULL,
	[DetailSendAmounts_discountedMgiSendFee] [decimal](18, 2) NULL,
	[DetailSendAmounts_mgiSendTax] [decimal](18, 2) NULL,
	[DetailSendAmounts_totalMgiCollectedFeesAndTaxes] [decimal](18, 2) NULL,
	[DetailSendAmounts_totalAmountToMgi] [decimal](18, 2) NULL,
	[DetailSendAmounts_totalSendFeesAndTaxes] [decimal](18, 2) NULL,
	[DetailSendAmounts_totalNonMgiSendFeesAndTaxes] [decimal](18, 2) NULL,
	[DetailSendAmounts_nonMgiSendTax] [decimal](18, 2) NULL,
	[DetailSendAmounts_nonMgiSendFee] [decimal](18, 2) NULL,
	[ValidCurrencyIndicator] [bit] NULL,
	[PayoutCurrency] [varchar](50) NULL,
	[TotalReceiveFees] [decimal](18, 2) NULL,
	[TotalReceiveTaxes] [decimal](18, 2) NULL,
	[TotalReceiveAmount] [decimal](18, 2) NULL,
	[ReceiveFeesAreEstimated] [bit] NULL,
	[ReceiveTaxesAreEstimated] [bit] NULL,
	[DetailReceiveAmounts_nonMgiReceiveFee] [decimal](18, 2) NULL,
	[DetailReceiveAmounts_nonMgiReceiveTax] [decimal](18, 2) NULL,
	[DetailReceiveAmounts_mgiReceiveFee] [decimal](18, 2) NULL,
	[DetailReceiveAmounts_mgiReceiveTax] [decimal](18, 2) NULL,
	[DetailEstimatedReceiveAmounts_nonMgiReceiveFee] [decimal](18, 2) NULL,
	[DetailEstimatedReceiveAmounts_nonMgiReceiveTax] [decimal](18, 2) NULL,
	[DetailEstimatedReceiveAmounts_mgiReceiveFee] [decimal](18, 2) NULL,
	[DetailEstimatedReceiveAmounts_mgiReceiveTax] [decimal](18, 2) NULL,
	[TransactionType] [varchar](20) NULL,
	[ChannelPartnerId] [bigint] NULL,
	[ProviderId] [int] NULL,
	[MgiTransactionSessionId] [varchar](50) NULL,
	[ExchangeRate] [decimal](18, 2) NULL,
	[AgentCustomerNumber] [varchar](50) NULL,
	[SenderDOB] [datetime] NULL,
	[SendCurrency] [varchar](10) NULL,
	[ConsumerId] [varchar](20) NULL,
	[FormFreeStaging] [bit] NULL,
	[ReadyForCommit] [bit] NULL,
	[ReceiveAgentID] [varchar](50) NULL,
	[ReceiveAgentName] [varchar](40) NULL,
	[ReceiveAgentAddress] [varchar](100) NULL,
	[ExchangeRateApplied] [decimal](18, 2) NULL,
	[ReceiveFeeDisclosureText] [bit] NULL,
	[ReceiveTaxDisclosureText] [bit] NULL,
	[ReferenceNumber] [varchar](20) NULL,
	[PartnerConfirmationNumber] [varchar](50) NULL,
	[FreePhoneCallPIN] [varchar](50) NULL,
	[TollFreePhoneNumber] [varchar](50) NULL,
	[ExpectedDateOfDelivery] [datetime] NULL,
	[TransactionDateTime] [datetime] NULL,
	[StateRegulatorVersion] [varchar](50) NULL,
	[AccountNumber] [varchar](50) NULL,
	[CustomerReceiveNumber] [varchar](50) NULL,
	[Direction1] [varchar](50) NULL,
	[Direction2] [varchar](50) NULL,
	[Direction3] [varchar](50) NULL,
	[TestQuestion] [varchar](50) NULL,
	[TestAnswer] [varchar](50) NULL,
	[MessageField1] [varchar](50) NULL,
	[MessageField2] [varchar](50) NULL,
	[MarketingOptIn] [varchar](50) NULL,
	[PcTerminalNumber] [varchar](50) NULL,
	[AgentUseSendData] [varchar](50) NULL,
	[AgentTransactionId] [varchar](50) NULL,
	[TimeToLive] [varchar](50) NULL,
	[IsDomesticTransfer] [bit] NULL,
	[ReceiverId] [bigint] NULL,
	[AccountId] [bigint] NULL,
	[RequestResponseType] [tinyint] NULL,
	[AgentID] [varchar](20) NULL,
	[AgentSequence] [varchar](10) NULL,
	[Token] [varchar](10) NULL,
	[RequestTimeStamp] [datetime] NULL,
	[ApiVersion] [varchar](10) NULL,
	[ClientSoftwareVersion] [varchar](10) NULL,
	[DoCheckIn] [bit] NULL,
	[ResponseTimeStamp] [datetime] NULL,
	[Flags] [int] NULL,
	[PromotionalMessage_PrimaryLanguage] [varchar](200) NULL,
	[PromotionalMessage_SecondaryLanguage] [varchar](200) NULL,
	[PartnerName] [varchar](40) NULL,
	[ReceiptTextInfo_PrimaryLanguage] [varchar](200) NULL,
	[ReceiptTextInfo_SecondaryLanguage] [varchar](200) NULL,
	[AccountNumberLastFour] [varchar](4) NULL,
	[CustomerServiceMessage] [varchar](255) NULL,
	[AccountNickname] [varchar](30) NULL,
	[PromotionErrorCodeMessage_SecondaryLanguage] [varchar](200) NULL,
	[DisclosureText_PrimaryLanguage] [varchar](200) NULL,
	[DisclosureText_SecondaryLanguage] [varchar](200) NULL,
	[DynamicFields] [varchar](max) NULL,
	[AuditEvent] smallint NOT NULL,
	[DTAudit] Datetime NOT NULL,
	[RevisionNo] bigint NULL,
	[DTCreate] [datetime] NULL,
	[DTLastMod] [datetime] NULL,
	[DTServerCreate] [datetime] NULL,
	[DTServerLastMod] [datetime] NULL
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


