USE [master]
GO

/****** Object:  Database [Partner]    Script Date: 04/04/2013 13:52:37 ******/
CREATE DATABASE [Partner] ON  PRIMARY 
( NAME = N'Partner', FILENAME = N'D:\MSSQL_Data\Partner.mdf' , SIZE = 2048KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Partner_log', FILENAME = N'E:\MSSQL_TransactionLogs\Partner_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Partner] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Partner].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Partner] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Partner] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Partner] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Partner] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Partner] SET ARITHABORT OFF 
GO

ALTER DATABASE [Partner] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Partner] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [Partner] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Partner] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Partner] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Partner] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Partner] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Partner] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Partner] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Partner] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Partner] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Partner] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Partner] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Partner] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Partner] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Partner] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Partner] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Partner] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Partner] SET  READ_WRITE 
GO

ALTER DATABASE [Partner] SET RECOVERY FULL 
GO

ALTER DATABASE [Partner] SET  MULTI_USER 
GO

ALTER DATABASE [Partner] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Partner] SET DB_CHAINING OFF 
GO


