--- ===============================================================================
-- Author:		<Shwetha Mohan>
-- Create date: <12/12/20165>
-- Description:	 Alter PK and FK constraints for Location related tables
-- Jira ID:		<AL-7582>
-- ================================================================================


-- DROP FK constraints in Location related tables
IF EXISTS (SELECT 1 FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_tAgentLocationMapping_tAgentDetails_AgentPK]') AND parent_object_id = OBJECT_ID(N'[dbo].[tAgentLocationMapping]'))
BEGIN
	ALTER TABLE [dbo].[tAgentLocationMapping] DROP CONSTRAINT [FK_tAgentLocationMapping_tAgentDetails_AgentPK]
END
GO

IF EXISTS (SELECT 1 FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_tAgentLocationMapping_tLocations_LocationPK]') AND parent_object_id = OBJECT_ID(N'[dbo].[tAgentLocationMapping]'))
BEGIN
	ALTER TABLE [dbo].[tAgentLocationMapping] DROP CONSTRAINT [FK_tAgentLocationMapping_tLocations_LocationPK]
END
GO

IF EXISTS (SELECT 1 FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_tLocationCounterIdDetails_LocationId]') AND parent_object_id = OBJECT_ID(N'[dbo].[tLocationCounterIdDetails]'))
BEGIN
	ALTER TABLE [dbo].[tLocationCounterIdDetails] DROP CONSTRAINT [FK_tLocationCounterIdDetails_LocationId]
END
GO

DECLARE @FKName VARCHAR(500);
SELECT @FKName = f.name
	FROM SYS.FOREIGN_KEYS AS f
			INNER JOIN SYS.FOREIGN_KEY_COLUMNS AS fc ON f.OBJECT_ID = fc.CONSTRAINT_OBJECT_ID
			INNER JOIN SYS.OBJECTS AS o ON o.OBJECT_ID = fc.REFERENCED_OBJECT_ID
	WHERE OBJECT_NAME(f.PARENT_OBJECT_ID) = 'tLocationProcessorCredentials'
			AND COL_NAME(fc.PARENT_OBJECT_ID, fc.parent_column_id) = 'LocationId'
			AND OBJECT_NAME(f.REFERENCED_OBJECT_ID) = 'tLocations'
			AND COL_NAME(fc.REFERENCED_OBJECT_ID, fc.REFERENCED_COLUMN_ID) = 'LocationPK';
IF(@FKName IS NOT NULL)
	BEGIN
		EXEC ('ALTER TABLE  tLocationProcessorCredentials DROP CONSTRAINT '+@FKName);
 END;
 GO

IF EXISTS (SELECT 1 FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_tNpsTerminals_tLocations_RowGuid]') AND parent_object_id = OBJECT_ID(N'[dbo].[tNpsTerminals]'))
BEGIN	
		ALTER TABLE [dbo].[tNpsTerminals] DROP CONSTRAINT [FK_tNpsTerminals_tLocations_RowGuid]
END
GO

IF EXISTS (SELECT 1 FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_tTerminals_tLocations]') AND parent_object_id = OBJECT_ID(N'[dbo].[tTerminals]'))
BEGIN
	ALTER TABLE [dbo].[tTerminals] DROP CONSTRAINT [FK_tTerminals_tLocations]
END
GO

IF EXISTS (SELECT 1 FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_tChannelPartnerPricing_tLocations]') AND parent_object_id = OBJECT_ID(N'[dbo].[tChannelPartnerPricing]'))
BEGIN
	ALTER TABLE [dbo].[tChannelPartnerPricing] DROP CONSTRAINT [FK_tChannelPartnerPricing_tLocations]
END
GO
--==========================================================================================================

-- DROP PK constraints in Location related tables
IF EXISTS (SELECT * FROM sys.objects WHERE type_desc = 'PRIMARY_KEY_CONSTRAINT' AND OBJECT_NAME(parent_object_id) = 'tAgentLocationMapping')
BEGIN
 -- PK constraint Name generated by server which was not common for all the DB server, So fetch the PK constraint Name and DROP
DECLARE @PKName varchar(max)
SELECT @PKName=name FROM sys.objects WHERE type_desc = 'PRIMARY_KEY_CONSTRAINT' AND OBJECT_NAME(parent_object_id) = 'tAgentLocationMapping'
EXEC('ALTER TABLE [dbo].[tAgentLocationMapping] DROP CONSTRAINT ' + @PKName)
END
GO

IF EXISTS (SELECT 1 FROM sys.objects WHERE type_desc = 'PRIMARY_KEY_CONSTRAINT' AND OBJECT_NAME(parent_object_id) = 'tLocationCounterIdDetails' AND OBJECT_NAME(OBJECT_ID) = 'PK_tLocationCounterIdDetails')
BEGIN
	ALTER TABLE [dbo].[tLocationCounterIdDetails] DROP CONSTRAINT [PK_tLocationCounterIdDetails]
END
GO

IF EXISTS (SELECT 1 FROM sys.objects WHERE type_desc = 'PRIMARY_KEY_CONSTRAINT' AND OBJECT_NAME(parent_object_id) = 'tLocationProcessorCredentials' AND OBJECT_NAME(OBJECT_ID) != 'PK_tLocationProcessorCredentials')
BEGIN
     -- PK constraint Name generated by server which was not common for all the DB server, So fetch the PK constraint Name and DROP
    DECLARE @PKName varchar(max)
	SELECT @PKName=name FROM sys.objects WHERE type_desc = 'PRIMARY_KEY_CONSTRAINT' AND OBJECT_NAME(parent_object_id) = 'tLocationProcessorCredentials'	
	EXEC('ALTER TABLE [dbo].[tLocationProcessorCredentials] DROP CONSTRAINT ' + @PKName) 
END
GO

IF EXISTS (SELECT 1 FROM sys.objects WHERE type_desc = 'PRIMARY_KEY_CONSTRAINT' AND OBJECT_NAME(parent_object_id) = 'tLocations' AND OBJECT_NAME(OBJECT_ID) = 'PK_tLocations')
BEGIN
	ALTER TABLE [dbo].[tLocations] DROP CONSTRAINT [PK_tLocations]
END
GO

--==============================================================================================================
-- Add Pk constraint to tLocation table
IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE type_desc = 'PRIMARY_KEY_CONSTRAINT' AND OBJECT_NAME(parent_object_id) = 'tLocations' AND OBJECT_NAME(OBJECT_ID) = 'PK_tLocation')
BEGIN
ALTER TABLE [dbo].[tLocations] ADD  CONSTRAINT [PK_tLocation] PRIMARY KEY CLUSTERED (LocationID)
END
GO

-- Add PK constraint to tLocationProcessorCredentials table
IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE type_desc = 'PRIMARY_KEY_CONSTRAINT' AND OBJECT_NAME(parent_object_id) = 'tLocationProcessorCredentials' AND OBJECT_NAME(OBJECT_ID) = 'PK_tLocationProcessorCredentials')
BEGIN
ALTER TABLE [dbo].[tLocationProcessorCredentials] ADD  CONSTRAINT [PK_tLocationProcessorCredentials] PRIMARY KEY CLUSTERED (LocationProcessorCredentialsID)
END
GO

----- ReName LocationId to LocationPK
IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'tLocationProcessorCredentials' AND COLUMN_NAME = 'LocationId' AND DATA_TYPE = 'uniqueidentifier')
BEGIN
	 EXEC sp_RENAME '[tLocationProcessorCredentials].[LocationId]' , 'LocationPK' , 'COLUMN'	 
END
GO

-- ADD LocationId(bigint) for FK reference
IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'tLocationProcessorCredentials' AND COLUMN_NAME = 'LocationId')
BEGIN
	ALTER TABLE tLocationProcessorCredentials 
	ADD LocationId BIGINT NULL
END
GO

-- Add Pk constraint to tLocationCounterIdDetails table
IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE type_desc = 'PRIMARY_KEY_CONSTRAINT' AND OBJECT_NAME(parent_object_id) = 'tLocationCounterIdDetails' AND OBJECT_NAME(OBJECT_ID) = 'PK_tLocationCounterIdDetails')
BEGIN
	ALTER TABLE [dbo].[tLocationCounterIdDetails] ADD  CONSTRAINT [PK_tLocationCounterIdDetails] PRIMARY KEY CLUSTERED (LocationCounterIdDetailID)
END
GO

-- ReName LocationId to LocationPK
IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'tLocationCounterIdDetails' AND COLUMN_NAME = 'LocationId' AND DATA_TYPE = 'uniqueidentifier')
BEGIN
	 EXEC sp_RENAME '[tLocationCounterIdDetails].[LocationId]' , 'LocationPK' , 'COLUMN'	 
END
GO

--===================================================================================================================

-- ADD LocationId(bigint) for FK reference
IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'tLocationCounterIdDetails' AND COLUMN_NAME = 'LocationId')
BEGIN
	ALTER TABLE tLocationCounterIdDetails 
	ADD LocationId BIGINT NULL
END
GO

-- ADD LocationId as FK in tLocationProcessorCredentials

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_tLocations_tLocationProcessorCredentials]') AND parent_object_id = OBJECT_ID(N'[dbo].[tLocationProcessorCredentials]'))
BEGIN
	ALTER TABLE [dbo].[tLocationProcessorCredentials]  WITH CHECK ADD  CONSTRAINT [FK_tLocations_tLocationProcessorCredentials] FOREIGN KEY([LocationId])
	REFERENCES [dbo].[tLocations] ([LocationID])	
END
GO

-- ADD LocationId as FK in tLocationCounterIdDetails

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_tLocations_tLocationCounterIdDetails]') AND parent_object_id = OBJECT_ID(N'[dbo].[tLocationCounterIdDetails]'))
BEGIN
	ALTER TABLE [dbo].[tLocationCounterIdDetails]  WITH CHECK ADD  CONSTRAINT [FK_tLocations_tLocationCounterIdDetails] FOREIGN KEY([LocationId])
	REFERENCES [dbo].[tLocations] ([LocationID])	
END
GO

--========================================================================================================================-=


-- tAgentLocationMapping == this table is not used, will be removed from the DB

IF NOT EXISTS( SELECT 1 FROM sys.default_constraints WHERE name = 'DF_tLocationPK_tLocation' )
BEGIN
	ALTER TABLE tLocationProcessorCredentials ADD CONSTRAINT DF_LocationProcessorCredentialsPK_tLocationProcessorCredentials DEFAULT NEWID() FOR LocationProcessorCredentialsPK
END
GO

IF NOT EXISTS( SELECT 1 FROM sys.default_constraints WHERE name = 'DF_tLocationPK_tLocation' )
BEGIN
	ALTER TABLE tLocationProcessorCredentials ADD CONSTRAINT DF_tLocationPK_tLocationProcessorCredentials DEFAULT NEWID() FOR LocationPK
END
GO

IF NOT EXISTS( SELECT 1 FROM sys.default_constraints WHERE name = 'DF_tLocationPK_tLocation' )
BEGIN
	ALTER TABLE tLocations ADD CONSTRAINT DF_tLocationPK_tLocation DEFAULT NEWID() FOR LocationPK
END
GO

IF NOT EXISTS( SELECT 1 FROM sys.default_constraints WHERE name = 'DF_LocationCounterIdDetailPK_tLocationCounterIdDetails' )
BEGIN
	ALTER TABLE tLocationCounterIdDetails ADD CONSTRAINT DF_LocationCounterIdDetailPK_tLocationCounterIdDetails DEFAULT NEWID() FOR LocationCounterIdDetailPK
END
GO

IF OBJECT_ID(N'[trgLocationCounterIdInsertUpdate]', N'TR') IS NOT NULL
DROP TRIGGER [trgLocationCounterIdInsertUpdate]
GO

-- ADD LocationId(bigint) for FK reference
IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'tLocations' AND COLUMN_NAME = 'LocationPK')
BEGIN
	ALTER TABLE tLocations 
	ALTER COLUMN LocationPK UNIQUEIDENTIFIER NULL
END
GO


IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'tLocationCounterIdDetails' AND COLUMN_NAME = 'LocationPK')
BEGIN
	ALTER TABLE tLocationCounterIdDetails 
	ALTER COLUMN LocationPK UNIQUEIDENTIFIER NULL
END
GO

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'tLocationCounterIdDetails' AND COLUMN_NAME = 'LocationCounterIdDetailPK')
BEGIN
	ALTER TABLE tLocationCounterIdDetails 
	ALTER COLUMN LocationCounterIdDetailPK UNIQUEIDENTIFIER NULL
END
GO


