---===============================================================================
-- Author:		 <M.Purna Pushkal>
-- Create date: <28/11/2016>
-- Description: Update  WU transaction
-- Jira ID:		 <AL-8320>
-- ================================================================================

IF OBJECT_ID('usp_UpdateWUBillPayTransaction') IS NOT NULL
BEGIN
	DROP PROCEDURE dbo.usp_UpdateWUBillPayTransaction
END
GO

CREATE PROCEDURE usp_UpdateWUBillPayTransaction
(
	@wuBillPayTrxID                                      BIGINT,
	@dTServerDate                                        DATETIME,
	@senderCountryCode                                   VARCHAR(50), 
	@senderCurrencyCode                                  VARCHAR(50), 
	@levelCode                                           VARCHAR(50), 
	@senderEmail                                         VARCHAR(50), 
	@senderContactPhone                                  VARCHAR(50), 
	@billerCityCode                                      VARCHAR(50), 
	@countryCode                                         VARCHAR(50),
	@currencyCode                                        VARCHAR(50), 
	@financialsOriginatorsPrincipalAmount                DECIMAL(18, 2), 
	@financialsDestinationPrincipalAmount                DECIMAL(18, 2), 
	@financialsFee                                       DECIMAL(18, 2), 
	@financialsGrossTotalAmount                          DECIMAL(18, 2), 
	@financialsTotal                                     DECIMAL(18, 2),
	@financialsUndiscountedCharges                       DECIMAL(18, 2), 
	@financialsDiscountedCharges                         DECIMAL(18, 2),                                           
	@paymentDetailsRecordingCountryCode                  VARCHAR(50), 
	@paymentDetailsRecordingCountryCurrency              VARCHAR(50), 
	@paymentDetailsDestinationCountryCode                VARCHAR(20), 
	@paymentDetailsDestinationCountryCurrency            VARCHAR(20), 
	@paymentDetailsOriginatingCountryCode                VARCHAR(20), 
	@paymentDetailsOriginatingCountryCurrency            VARCHAR(20), 
	@paymentDetailsOriginatingCity                       VARCHAR(50), 
	@paymentDetailsOriginatingState                      VARCHAR(50), 
	@paymentDetailsTransactionType                       VARCHAR(50), 
	@paymentDetailsPaymentType                           VARCHAR(50), 
	@paymentDetailsExchangeRate                          DECIMAL(18, 2),                                             
	@paymentDetailsFixOnSend                             VARCHAR(50),                                             
	@paymentDetailsReceiptOptOut                         VARCHAR(50),                                             
	@paymentDetailsAuthStatus                            VARCHAR(50),                                             
	@fillingDate                                         VARCHAR(50),                                             
	@fillingTime                                         VARCHAR(50),                                             
	@mTCN                                                VARCHAR(50),                                             
	@newMTCN                                             VARCHAR(50),                                             
	@dfFieldsPDSRequiredFlag                             VARCHAR(50),                                             
	@dfFieldsTransactionFlag                             VARCHAR(50),                                             
	@dfFieldsDeliveryServiceName                         VARCHAR(50),                                             
	@deliveryCode                                        VARCHAR(50),                                            
	@fusionScreen                                        VARCHAR(50),                                             
	@convSessionCookie                                   VARCHAR(200),                                             
	@instantNotificationAddlServiceCharges               VARCHAR(200),                                             
	@instantNotificationAddlServiceLength                VARCHAR(50),                                             
	@promotionscouponspromotions                         VARCHAR(30),                                             
	@promotionspromocodedescription                      VARCHAR(250),                                             
	@promotionspromosequenceno                           VARCHAR(15),                                             
	@promotionspromoname                                 VARCHAR(50),                                             
	@promotionspromomessage                              VARCHAR(250),                                             
	@promotionspromodiscountamount                       BIGINT,                                             
	@promotionspromotionerror                            VARCHAR(250),                                             
	@promotionssenderpromocode                           VARCHAR(30),                                             
	@senderComplianceDetailsTemplateID                   VARCHAR(20),                                             
	@senderComplianceDetailsIdDetailsIdType              VARCHAR(10),                                             
	@senderComplianceDetailsIdDetailsIdCountryOfIssue    VARCHAR(50),                                            
	@senderComplianceDetailsIdDetailsIdPlaceOfIssue      VARCHAR(50),                                             
	@senderComplianceDetailsIdDetailsIdNumber            VARCHAR(50),                                             
	@senderComplianceDetailsSecondIDIdType               VARCHAR(10),                                             
	@senderComplianceDetailsSecondIDIdCountryOfIssue     VARCHAR(50),                                             
	@senderComplianceDetailsSecondIDIdNumber             VARCHAR(50),                                             
	@senderComplianceDetailsDateOfBirth                  VARCHAR(20),                                             
	@senderComplianceDetailsOccupation                   VARCHAR(50),                                             
	@senderComplianceDetailsCurrentAddressAddrLine1      VARCHAR(255),                                             
	@senderComplianceDetailsCurrentAddressAddrLine2      VARCHAR(255),                                             
	@senderComplianceDetailsCurrentAddressCity           VARCHAR(50),                                             
	@senderComplianceDetailsCurrentAddressStateCode      VARCHAR(20),                                             
	@senderComplianceDetailsCurrentAddressPostalCode     VARCHAR(20),                                            
	@senderComplianceDetailsContactPhone                 VARCHAR(20),                                             
	@senderComplianceDetailsIActOnMyBehalf               VARCHAR(10),                                             
	@senderComplianceDetailsAckFlag                      VARCHAR(10),                                             
	@senderComplianceDetailsComplianceDataBuffer         VARCHAR(500),                                             
	@financialsPlusChargesAmount                         DECIMAL(18, 2),                                             
	@financialsTotalDiscount                             DECIMAL(18, 2),                                             
	@wUCardTotalPointsEarned                             VARCHAR(50),                                           
	@qPCompanyDepartment                                 VARCHAR(100),                                             
	@dTTerminalDate                                      DATETIME,                                            
	@messageArea                                         NVARCHAR(MAX)    
)                                    
AS
BEGIN
	BEGIN TRY
		UPDATE 
			dbo.tWUnion_BillPay_Trx
		SET
			DTServerLastModified = @dTServerDate,
			Sender_CountryCode = @senderCountryCode,
			Sender_CurrencyCode = @senderCurrencyCode,
			LevelCode = @levelCode,
			Sender_Email = @senderEmail,
			Sender_ContactPhone = @senderContactPhone,
			Biller_CityCode = @billerCityCode,
			CurrencyCode = @currencyCode,
			CountryCode = @countryCode,
			Financials_OriginatorsPrincipalAmount = @financialsOriginatorsPrincipalAmount,
			Financials_DestinationPrincipalAmount = @financialsDestinationPrincipalAmount,
			Financials_Fee = @financialsFee,
			Financials_GrossTotalAmount = @financialsGrossTotalAmount,
			Financials_UndiscountedCharges = @financialsUndiscountedCharges,
			Financials_DiscountedCharges = @financialsDiscountedCharges,
			PaymentDetails_Recording_CountryCode = @paymentDetailsRecordingCountryCode,
			PaymentDetails_Recording_CountryCurrency = @paymentDetailsOriginatingCountryCurrency,
			PaymentDetails_Destination_CountryCode = @paymentDetailsDestinationCountryCode,
			PaymentDetails_Destination_CountryCurrency = @paymentDetailsDestinationCountryCurrency,
			PaymentDetails_Originating_CountryCode = @paymentDetailsOriginatingCountryCode,
			PaymentDetails_Originating_CountryCurrency = @paymentDetailsOriginatingCountryCurrency,
			PaymentDetails_Originating_City = @paymentDetailsOriginatingCity,
			PaymentDetails_Originating_State = @paymentDetailsOriginatingState,
			PaymentDetails_TransactionType = @paymentDetailsTransactionType,
			PaymentDetails_PaymentType = @paymentDetailsPaymentType,
			PaymentDetails_ExchangeRate = @paymentDetailsExchangeRate,
			PaymentDetails_FixOnSend = @paymentDetailsFixOnSend,
			PaymentDetails_ReceiptOptOut = @paymentDetailsReceiptOptOut,
			PaymentDetails_AuthStatus = @paymentDetailsAuthStatus,
			FillingDate = @fillingDate,
			FillingTime = @fillingTime,
			MTCN = @mTCN,
			NewMTCN = @newMTCN,
			DfFields_PDSRequiredFlag = @dfFieldsPDSRequiredFlag,
			DfFields_TransactionFlag = @dfFieldsTransactionFlag,
			DfFields_DeliveryServiceName = @dfFieldsDeliveryServiceName,
			DeliveryCode = @deliveryCode,
			FusionScreen = @fusionScreen,
			ConvSessionCookie = @convSessionCookie,
			InstantNotification_AddlServiceCharges = @instantNotificationAddlServiceCharges,
			InstantNotification_AddlServiceLength = @instantNotificationAddlServiceLength,
			promotions_coupons_promotions = @promotionscouponspromotions,
			promotions_promo_code_description = @promotionspromocodedescription,
			promotions_promo_sequence_no = @promotionspromosequenceno,
			promotions_promo_name = @promotionspromoname,
			promotions_promo_message = @promotionspromomessage,
			promotions_promo_discount_amount = @promotionspromodiscountamount,
			promotions_promotion_error = @promotionsPromotionError,
			promotions_sender_promo_code = @promotionssenderpromocode,
			Sender_ComplianceDetails_TemplateID = @senderComplianceDetailsTemplateID,
			Sender_ComplianceDetails_IdDetails_IdType = @senderComplianceDetailsIdDetailsIdType,
			Sender_ComplianceDetails_IdDetails_IdCountryOfIssue = @senderComplianceDetailsIdDetailsIdCountryOfIssue,
			Sender_ComplianceDetails_IdDetails_IdPlaceOfIssue = @senderComplianceDetailsIdDetailsIdPlaceOfIssue,
			Sender_ComplianceDetails_IdDetails_IdNumber = @senderComplianceDetailsIdDetailsIdNumber,
			Sender_ComplianceDetails_SecondID_IdType = @senderComplianceDetailsSecondIDIdType,
			Sender_ComplianceDetails_SecondID_IdCountryOfIssue = @senderComplianceDetailsSecondIDIdCountryOfIssue,
			Sender_ComplianceDetails_SecondID_IdNumber = @senderComplianceDetailsSecondIDIdNumber,
			Sender_ComplianceDetails_DateOfBirth = @senderComplianceDetailsDateOfBirth,
			Sender_ComplianceDetails_Occupation = @senderComplianceDetailsOccupation,
			Sender_ComplianceDetails_CurrentAddress_AddrLine1 = @senderComplianceDetailsCurrentAddressAddrLine1,
			Sender_ComplianceDetails_CurrentAddress_AddrLine2 = @senderComplianceDetailsCurrentAddressAddrLine2,
			Sender_ComplianceDetails_CurrentAddress_City = @senderComplianceDetailsCurrentAddressCity,
			Sender_ComplianceDetails_CurrentAddress_StateCode = @senderComplianceDetailsCurrentAddressStateCode,
			Sender_ComplianceDetails_CurrentAddress_PostalCode = @senderComplianceDetailsCurrentAddressPostalCode,
			Sender_ComplianceDetails_ContactPhone = @senderComplianceDetailsContactPhone,
			Sender_ComplianceDetails_I_ActOnMyBehalf = @senderComplianceDetailsIActOnMyBehalf,
			Sender_ComplianceDetails_Ack_Flag = @senderComplianceDetailsAckFlag,
			Sender_ComplianceDetails_ComplianceData_Buffer = @senderComplianceDetailsComplianceDataBuffer,
			Financials_PlusChargesAmount = @financialsPlusChargesAmount,
			Financials_TotalDiscount = @financialsTotalDiscount,
			WUCard_TotalPointsEarned = @wUCardTotalPointsEarned,
			QPCompany_Department = @qPCompanyDepartment,
			DTTerminalLastModified = @dTTerminalDate,
			MessageArea = @messageArea
		WHERE
			WUBillPayTrxID = @wuBillPayTrxID
	END TRY

	BEGIN CATCH
		 EXECUTE dbo.usp_CreateErrorInfo
	END CATCH
END
GO
