//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Peripheral.Service.CustomAction.DMSService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NpsTerminal", Namespace="http://schemas.datacontract.org/2004/07/MGI.Channel.DMS.NpsInstallerServer.Data")]
    [System.SerializableAttribute()]
    public partial class NpsTerminal : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Peripheral.Service.CustomAction.DMSService.ChannelPartner ChannelPartnerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ChannelPartnerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DTCreateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DTLastModField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IpAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Peripheral.Service.CustomAction.DMSService.Location LocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PeripheralServiceUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PortField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid rowguidField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Peripheral.Service.CustomAction.DMSService.ChannelPartner ChannelPartner {
            get {
                return this.ChannelPartnerField;
            }
            set {
                if ((object.ReferenceEquals(this.ChannelPartnerField, value) != true)) {
                    this.ChannelPartnerField = value;
                    this.RaisePropertyChanged("ChannelPartner");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ChannelPartnerId {
            get {
                return this.ChannelPartnerIdField;
            }
            set {
                if ((this.ChannelPartnerIdField.Equals(value) != true)) {
                    this.ChannelPartnerIdField = value;
                    this.RaisePropertyChanged("ChannelPartnerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DTCreate {
            get {
                return this.DTCreateField;
            }
            set {
                if ((this.DTCreateField.Equals(value) != true)) {
                    this.DTCreateField = value;
                    this.RaisePropertyChanged("DTCreate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DTLastMod {
            get {
                return this.DTLastModField;
            }
            set {
                if ((this.DTLastModField.Equals(value) != true)) {
                    this.DTLastModField = value;
                    this.RaisePropertyChanged("DTLastMod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IpAddress {
            get {
                return this.IpAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.IpAddressField, value) != true)) {
                    this.IpAddressField = value;
                    this.RaisePropertyChanged("IpAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Peripheral.Service.CustomAction.DMSService.Location Location {
            get {
                return this.LocationField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationField, value) != true)) {
                    this.LocationField = value;
                    this.RaisePropertyChanged("Location");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PeripheralServiceUrl {
            get {
                return this.PeripheralServiceUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.PeripheralServiceUrlField, value) != true)) {
                    this.PeripheralServiceUrlField = value;
                    this.RaisePropertyChanged("PeripheralServiceUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Port {
            get {
                return this.PortField;
            }
            set {
                if ((object.ReferenceEquals(this.PortField, value) != true)) {
                    this.PortField = value;
                    this.RaisePropertyChanged("Port");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid rowguid {
            get {
                return this.rowguidField;
            }
            set {
                if ((this.rowguidField.Equals(value) != true)) {
                    this.rowguidField = value;
                    this.RaisePropertyChanged("rowguid");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChannelPartner", Namespace="http://schemas.datacontract.org/2004/07/MGI.Channel.DMS.NpsInstallerServer.Data")]
    [System.SerializableAttribute()]
    public partial class ChannelPartner : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid rowguidField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid rowguid {
            get {
                return this.rowguidField;
            }
            set {
                if ((this.rowguidField.Equals(value) != true)) {
                    this.rowguidField = value;
                    this.RaisePropertyChanged("rowguid");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Location", Namespace="http://schemas.datacontract.org/2004/07/MGI.Channel.DMS.NpsInstallerServer.Data")]
    [System.SerializableAttribute()]
    public partial class Location : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Address1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Address2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BankIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BranchIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ChannelPartnerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DTCreateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DTLastModField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocationIdentifierField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocationNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TimezoneIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZipCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid rowguidField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address1 {
            get {
                return this.Address1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Address1Field, value) != true)) {
                    this.Address1Field = value;
                    this.RaisePropertyChanged("Address1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address2 {
            get {
                return this.Address2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Address2Field, value) != true)) {
                    this.Address2Field = value;
                    this.RaisePropertyChanged("Address2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BankID {
            get {
                return this.BankIDField;
            }
            set {
                if ((object.ReferenceEquals(this.BankIDField, value) != true)) {
                    this.BankIDField = value;
                    this.RaisePropertyChanged("BankID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BranchID {
            get {
                return this.BranchIDField;
            }
            set {
                if ((object.ReferenceEquals(this.BranchIDField, value) != true)) {
                    this.BranchIDField = value;
                    this.RaisePropertyChanged("BranchID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ChannelPartnerId {
            get {
                return this.ChannelPartnerIdField;
            }
            set {
                if ((this.ChannelPartnerIdField.Equals(value) != true)) {
                    this.ChannelPartnerIdField = value;
                    this.RaisePropertyChanged("ChannelPartnerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DTCreate {
            get {
                return this.DTCreateField;
            }
            set {
                if ((this.DTCreateField.Equals(value) != true)) {
                    this.DTCreateField = value;
                    this.RaisePropertyChanged("DTCreate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DTLastMod {
            get {
                return this.DTLastModField;
            }
            set {
                if ((this.DTLastModField.Equals(value) != true)) {
                    this.DTLastModField = value;
                    this.RaisePropertyChanged("DTLastMod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsActive {
            get {
                return this.IsActiveField;
            }
            set {
                if ((this.IsActiveField.Equals(value) != true)) {
                    this.IsActiveField = value;
                    this.RaisePropertyChanged("IsActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LocationIdentifier {
            get {
                return this.LocationIdentifierField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationIdentifierField, value) != true)) {
                    this.LocationIdentifierField = value;
                    this.RaisePropertyChanged("LocationIdentifier");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LocationName {
            get {
                return this.LocationNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationNameField, value) != true)) {
                    this.LocationNameField = value;
                    this.RaisePropertyChanged("LocationName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TimezoneID {
            get {
                return this.TimezoneIDField;
            }
            set {
                if ((object.ReferenceEquals(this.TimezoneIDField, value) != true)) {
                    this.TimezoneIDField = value;
                    this.RaisePropertyChanged("TimezoneID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZipCode {
            get {
                return this.ZipCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ZipCodeField, value) != true)) {
                    this.ZipCodeField = value;
                    this.RaisePropertyChanged("ZipCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid rowguid {
            get {
                return this.rowguidField;
            }
            set {
                if ((this.rowguidField.Equals(value) != true)) {
                    this.rowguidField = value;
                    this.RaisePropertyChanged("rowguid");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NexxoSOAPFault", Namespace="http://schemas.datacontract.org/2004/07/MGI.Common.Sys")]
    [System.SerializableAttribute()]
    public partial class NexxoSOAPFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddlDetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MajorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MinorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProcessorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProviderErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProviderErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProviderIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StackTraceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddlDetails {
            get {
                return this.AddlDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.AddlDetailsField, value) != true)) {
                    this.AddlDetailsField = value;
                    this.RaisePropertyChanged("AddlDetails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Details {
            get {
                return this.DetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.DetailsField, value) != true)) {
                    this.DetailsField = value;
                    this.RaisePropertyChanged("Details");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MajorCode {
            get {
                return this.MajorCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.MajorCodeField, value) != true)) {
                    this.MajorCodeField = value;
                    this.RaisePropertyChanged("MajorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MinorCode {
            get {
                return this.MinorCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.MinorCodeField, value) != true)) {
                    this.MinorCodeField = value;
                    this.RaisePropertyChanged("MinorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Processor {
            get {
                return this.ProcessorField;
            }
            set {
                if ((object.ReferenceEquals(this.ProcessorField, value) != true)) {
                    this.ProcessorField = value;
                    this.RaisePropertyChanged("Processor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProviderErrorCode {
            get {
                return this.ProviderErrorCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ProviderErrorCodeField, value) != true)) {
                    this.ProviderErrorCodeField = value;
                    this.RaisePropertyChanged("ProviderErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProviderErrorMessage {
            get {
                return this.ProviderErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ProviderErrorMessageField, value) != true)) {
                    this.ProviderErrorMessageField = value;
                    this.RaisePropertyChanged("ProviderErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProviderId {
            get {
                return this.ProviderIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ProviderIdField, value) != true)) {
                    this.ProviderIdField = value;
                    this.RaisePropertyChanged("ProviderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StackTrace {
            get {
                return this.StackTraceField;
            }
            set {
                if ((object.ReferenceEquals(this.StackTraceField, value) != true)) {
                    this.StackTraceField = value;
                    this.RaisePropertyChanged("StackTrace");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DMSService.INpsInstallerService")]
    public interface INpsInstallerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INpsInstallerService/CreateTerminal", ReplyAction="http://tempuri.org/INpsInstallerService/CreateTerminalResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Peripheral.Service.CustomAction.DMSService.NexxoSOAPFault), Action="http://tempuri.org/INpsInstallerService/CreateTerminalNexxoSOAPFaultFault", Name="NexxoSOAPFault", Namespace="http://schemas.datacontract.org/2004/07/MGI.Common.Sys")]
        bool CreateTerminal(Peripheral.Service.CustomAction.DMSService.NpsTerminal npsTerminal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INpsInstallerService/UpdateTerminal", ReplyAction="http://tempuri.org/INpsInstallerService/UpdateTerminalResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Peripheral.Service.CustomAction.DMSService.NexxoSOAPFault), Action="http://tempuri.org/INpsInstallerService/UpdateTerminalNexxoSOAPFaultFault", Name="NexxoSOAPFault", Namespace="http://schemas.datacontract.org/2004/07/MGI.Common.Sys")]
        bool UpdateTerminal(Peripheral.Service.CustomAction.DMSService.NpsTerminal npsTerminal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INpsInstallerService/Locations", ReplyAction="http://tempuri.org/INpsInstallerService/LocationsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Peripheral.Service.CustomAction.DMSService.NexxoSOAPFault), Action="http://tempuri.org/INpsInstallerService/LocationsNexxoSOAPFaultFault", Name="NexxoSOAPFault", Namespace="http://schemas.datacontract.org/2004/07/MGI.Common.Sys")]
        string[] Locations(string agentName, string agentPassword, string channelPartnerName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INpsInstallerService/LookupNpsInstallerTerminalByIpAddress", ReplyAction="http://tempuri.org/INpsInstallerService/LookupNpsInstallerTerminalByIpAddressResp" +
            "onse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Peripheral.Service.CustomAction.DMSService.NexxoSOAPFault), Action="http://tempuri.org/INpsInstallerService/LookupNpsInstallerTerminalByIpAddressNexx" +
            "oSOAPFaultFault", Name="NexxoSOAPFault", Namespace="http://schemas.datacontract.org/2004/07/MGI.Common.Sys")]
        Peripheral.Service.CustomAction.DMSService.NpsTerminal LookupNpsInstallerTerminalByIpAddress(string ipAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INpsInstallerService/GetAllLocations", ReplyAction="http://tempuri.org/INpsInstallerService/GetAllLocationsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Peripheral.Service.CustomAction.DMSService.NexxoSOAPFault), Action="http://tempuri.org/INpsInstallerService/GetAllLocationsNexxoSOAPFaultFault", Name="NexxoSOAPFault", Namespace="http://schemas.datacontract.org/2004/07/MGI.Common.Sys")]
        Peripheral.Service.CustomAction.DMSService.Location[] GetAllLocations();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INpsInstallerServiceChannel : Peripheral.Service.CustomAction.DMSService.INpsInstallerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NpsInstallerServiceClient : System.ServiceModel.ClientBase<Peripheral.Service.CustomAction.DMSService.INpsInstallerService>, Peripheral.Service.CustomAction.DMSService.INpsInstallerService {
        
        public NpsInstallerServiceClient() {
        }
        
        public NpsInstallerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NpsInstallerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NpsInstallerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NpsInstallerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool CreateTerminal(Peripheral.Service.CustomAction.DMSService.NpsTerminal npsTerminal) {
            return base.Channel.CreateTerminal(npsTerminal);
        }
        
        public bool UpdateTerminal(Peripheral.Service.CustomAction.DMSService.NpsTerminal npsTerminal) {
            return base.Channel.UpdateTerminal(npsTerminal);
        }
        
        public string[] Locations(string agentName, string agentPassword, string channelPartnerName) {
            return base.Channel.Locations(agentName, agentPassword, channelPartnerName);
        }
        
        public Peripheral.Service.CustomAction.DMSService.NpsTerminal LookupNpsInstallerTerminalByIpAddress(string ipAddress) {
            return base.Channel.LookupNpsInstallerTerminalByIpAddress(ipAddress);
        }
        
        public Peripheral.Service.CustomAction.DMSService.Location[] GetAllLocations() {
            return base.Channel.GetAllLocations();
        }
    }
}
