IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[tWUnion_States]') AND type in (N'U'))
	insert into tWUnion_States (rowguid,StateCode,Name,ISOCountryCode,DTCreate) values (NEWID(),'AB','Alberta','CA',GETDATE())
	insert into tWUnion_States (rowguid,StateCode,Name,ISOCountryCode,DTCreate) values (NEWID(),'BC','British Columbia','CA',GETDATE())
	insert into tWUnion_States (rowguid,StateCode,Name,ISOCountryCode,DTCreate) values (NEWID(),'MB','Manitoba','CA',GETDATE())
	insert into tWUnion_States (rowguid,StateCode,Name,ISOCountryCode,DTCreate) values (NEWID(),'NB','New Brunswick','CA',GETDATE())
	insert into tWUnion_States (rowguid,StateCode,Name,ISOCountryCode,DTCreate) values (NEWID(),'NL','Newfoundland and Labrador','CA',GETDATE())
	insert into tWUnion_States (rowguid,StateCode,Name,ISOCountryCode,DTCreate) values (NEWID(),'NT','Northwest Territories','CA',GETDATE())
	insert into tWUnion_States (rowguid,StateCode,Name,ISOCountryCode,DTCreate) values (NEWID(),'NS','Nova Scotia','CA',GETDATE())
	insert into tWUnion_States (rowguid,StateCode,Name,ISOCountryCode,DTCreate) values (NEWID(),'NU','Nunavut','CA',GETDATE())
	insert into tWUnion_States (rowguid,StateCode,Name,ISOCountryCode,DTCreate) values (NEWID(),'ON','Ontario','CA',GETDATE())
	insert into tWUnion_States (rowguid,StateCode,Name,ISOCountryCode,DTCreate) values (NEWID(),'PE','Prince Edward Island','CA',GETDATE())
	insert into tWUnion_States (rowguid,StateCode,Name,ISOCountryCode,DTCreate) values (NEWID(),'QC','Quebec','CA',GETDATE())
	insert into tWUnion_States (rowguid,StateCode,Name,ISOCountryCode,DTCreate) values (NEWID(),'SK','Saskatchewan','CA',GETDATE())
	insert into tWUnion_States (rowguid,StateCode,Name,ISOCountryCode,DTCreate) values (NEWID(),'YT','Yukon','CA',GETDATE())
GO