using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using MGI.Channel.Shared.Server.Data;

namespace MGI.Channel.DMS.Server.Data
{
	[DataContract]
	[KnownType(typeof(Product))]
	[KnownType(typeof(List<string>))]
	[KnownType(typeof(List<Product>))]
	[KnownType(typeof(BillPayLocation))]
	[KnownType(typeof(BillFee))]
	[KnownType(typeof(BillerInfo))]
	[KnownType(typeof(List<Field>))]
	[KnownType(typeof(FavoriteBiller))]
	[KnownType(typeof(MGI.Channel.Shared.Server.Data.CardInfo))]
	[KnownType(typeof(CashierDetails))]
	[KnownType(typeof(decimal))]
	[KnownType(typeof(Receiver))]
	[KnownType(typeof(List<XferMasterData>))]
	[KnownType(typeof(BannerMessage))]
	[KnownType(typeof(List<MoneyTransferReason>))]
	[KnownType(typeof(string))]
	[KnownType(typeof(long))]
	[KnownType(typeof(bool))]
	[KnownType(typeof(FeeResponse))]
	[KnownType(typeof(ValidateResponse))]
	[KnownType(typeof(MoneyTransferTransaction))]
	[KnownType(typeof(CardDetails))]
	[KnownType(typeof(List<WUCustomerGoldCardResult>))]
	[KnownType(typeof(Account))]
	[KnownType(typeof(List<DeliveryService>))]
	[KnownType(typeof(SendMoneySearchResponse))]
	[KnownType(typeof(ModifySendMoneyResponse))]
	[KnownType(typeof(List<Receiver>))]
	[KnownType(typeof(MoneyOrder))]
	[KnownType(typeof(TransactionFee))]
	[KnownType(typeof(Data.CheckPrint))]
	[KnownType(typeof(KeyValuePair<string, string>))]
	[KnownType(typeof(FundTransaction))]
	[KnownType(typeof(List<ShippingTypes>))]
	[KnownType(typeof(List<CardTransactionHistory>))]
	[KnownType(typeof(FundsProcessorAccount))]
	[KnownType(typeof(TransactionFee))]
	[KnownType(typeof(Data.CardInfo))]
	[KnownType(typeof(Message))]
	[KnownType(typeof(List<TransactionHistory>))]
	[KnownType(typeof(CheckTransaction))]
	[KnownType(typeof(BillPayTransaction))]
	[KnownType(typeof(CashTransaction))]
	[KnownType(typeof(List<ReceiptData>))]
	[KnownType(typeof(bool))]
	[KnownType(typeof(Terminal))]
	[KnownType(typeof(NpsTerminal))]
	[KnownType(typeof(List<NpsTerminal>))]
	[KnownType(typeof(List<Terminal>))]
	[KnownType(typeof(ChannelPartnerCertificate))]
	[KnownType(typeof(ChannelPartner))]
	[KnownType(typeof(List<TipsAndOffers>))]
	[KnownType(typeof(List<ProcessorCredential>))]
	[KnownType(typeof(Location))]
	[KnownType(typeof(List<Location>))]
	[KnownType(typeof(long))]
	[KnownType(typeof(AgentSession))]
	[KnownType(typeof(UserDetails))]
	[KnownType(typeof(List<UserDetails>))]
	[KnownType(typeof(MoneyOrderTransaction))]
	[KnownType(typeof(Customer))]
	[KnownType(typeof(Prospect))]
	[KnownType(typeof(List<CustomerSearchResult>))]
	[KnownType(typeof(CustomerSession))]
	[KnownType(typeof(List<Prospect>))]
	[KnownType(typeof(MGI.Channel.Shared.Server.Data.ShoppingCart))]
	[KnownType(typeof(MGI.Channel.Shared.Server.Data.ShoppingCartCheckoutStatus))]
	[KnownType(typeof(MGI.Channel.Shared.Server.Data.Receipts))]
	[KnownType(typeof(List<ParkedTransaction>))]
	[KnownType(typeof(List<LegalCode>))]
	[KnownType(typeof(List<MasterCountry>))]
	[KnownType(typeof(List<Occupation>))]
	[KnownType(typeof(IDRequirement))]
	[KnownType(typeof(MasterCountry))]
	[KnownType(typeof(Check))]
	[KnownType(typeof(List<CheckType>))]
	[KnownType(typeof(CheckProcessorInfo))]
	[KnownType(typeof(List<AgentMessage>))]
	[KnownType(typeof(CheckLogin))]
	[KnownType(typeof(CheckTransactionDetails))]
	[KnownType(typeof(AgentMessage))]
	public class Response
	{
		[DataMember]
		public object Result { get; set; }
		[DataMember]
		public Error Error { get; set; }
	}

}
