//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCF.Zeo.Cxn.Customer.TCF.TellerWorkQueueService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PrecartRequest", Namespace="http://schemas.datacontract.org/2004/07/TellerWorkQueueWS")]
    [System.SerializableAttribute()]
    public partial class PrecartRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BasicAuthInfo BasicAuthInformationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CustomerInfo CustomerInformationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SessionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ZeoTransaction[] TransactionSummaryField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BasicAuthInfo BasicAuthInformation {
            get {
                return this.BasicAuthInformationField;
            }
            set {
                if ((object.ReferenceEquals(this.BasicAuthInformationField, value) != true)) {
                    this.BasicAuthInformationField = value;
                    this.RaisePropertyChanged("BasicAuthInformation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CustomerInfo CustomerInformation {
            get {
                return this.CustomerInformationField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerInformationField, value) != true)) {
                    this.CustomerInformationField = value;
                    this.RaisePropertyChanged("CustomerInformation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SessionId {
            get {
                return this.SessionIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SessionIdField, value) != true)) {
                    this.SessionIdField = value;
                    this.RaisePropertyChanged("SessionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ZeoTransaction[] TransactionSummary {
            get {
                return this.TransactionSummaryField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionSummaryField, value) != true)) {
                    this.TransactionSummaryField = value;
                    this.RaisePropertyChanged("TransactionSummary");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BasicAuthInfo", Namespace="http://schemas.datacontract.org/2004/07/TellerWorkQueueWS")]
    [System.SerializableAttribute()]
    public partial class BasicAuthInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AMPMIndicatorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BankNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BranchNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BusinessDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CashDrawerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HostNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LUField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LawsonIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubClientNodeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TellerNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AMPMIndicator {
            get {
                return this.AMPMIndicatorField;
            }
            set {
                if ((object.ReferenceEquals(this.AMPMIndicatorField, value) != true)) {
                    this.AMPMIndicatorField = value;
                    this.RaisePropertyChanged("AMPMIndicator");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BankNumber {
            get {
                return this.BankNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.BankNumberField, value) != true)) {
                    this.BankNumberField = value;
                    this.RaisePropertyChanged("BankNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BranchNumber {
            get {
                return this.BranchNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.BranchNumberField, value) != true)) {
                    this.BranchNumberField = value;
                    this.RaisePropertyChanged("BranchNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BusinessDate {
            get {
                return this.BusinessDateField;
            }
            set {
                if ((object.ReferenceEquals(this.BusinessDateField, value) != true)) {
                    this.BusinessDateField = value;
                    this.RaisePropertyChanged("BusinessDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CashDrawer {
            get {
                return this.CashDrawerField;
            }
            set {
                if ((object.ReferenceEquals(this.CashDrawerField, value) != true)) {
                    this.CashDrawerField = value;
                    this.RaisePropertyChanged("CashDrawer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HostName {
            get {
                return this.HostNameField;
            }
            set {
                if ((object.ReferenceEquals(this.HostNameField, value) != true)) {
                    this.HostNameField = value;
                    this.RaisePropertyChanged("HostName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LU {
            get {
                return this.LUField;
            }
            set {
                if ((object.ReferenceEquals(this.LUField, value) != true)) {
                    this.LUField = value;
                    this.RaisePropertyChanged("LU");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LawsonId {
            get {
                return this.LawsonIdField;
            }
            set {
                if ((object.ReferenceEquals(this.LawsonIdField, value) != true)) {
                    this.LawsonIdField = value;
                    this.RaisePropertyChanged("LawsonId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubClientNodeId {
            get {
                return this.SubClientNodeIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SubClientNodeIdField, value) != true)) {
                    this.SubClientNodeIdField = value;
                    this.RaisePropertyChanged("SubClientNodeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TellerNumber {
            get {
                return this.TellerNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.TellerNumberField, value) != true)) {
                    this.TellerNumberField = value;
                    this.RaisePropertyChanged("TellerNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((object.ReferenceEquals(this.UserIdField, value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerInfo", Namespace="http://schemas.datacontract.org/2004/07/TellerWorkQueueWS")]
    [System.SerializableAttribute()]
    public partial class CustomerInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressLine1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressLine2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApplicationCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CitizenshipCountry1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CitizenshipCountry2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientCustomerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerSinceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DOBField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmployerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmployerPhoneNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdExpDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdIssueDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdIssuerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdIssuerCountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaidenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MiddleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NEXXOPANField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OccDescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OccupationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumber1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumber1TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumber2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumber2ProvField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumber2TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProdCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SSNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TCFCustomerIndicatorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TCFExistField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TCFPANField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TaxCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZipField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressLine1 {
            get {
                return this.AddressLine1Field;
            }
            set {
                if ((object.ReferenceEquals(this.AddressLine1Field, value) != true)) {
                    this.AddressLine1Field = value;
                    this.RaisePropertyChanged("AddressLine1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressLine2 {
            get {
                return this.AddressLine2Field;
            }
            set {
                if ((object.ReferenceEquals(this.AddressLine2Field, value) != true)) {
                    this.AddressLine2Field = value;
                    this.RaisePropertyChanged("AddressLine2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApplicationCode {
            get {
                return this.ApplicationCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ApplicationCodeField, value) != true)) {
                    this.ApplicationCodeField = value;
                    this.RaisePropertyChanged("ApplicationCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CitizenshipCountry1 {
            get {
                return this.CitizenshipCountry1Field;
            }
            set {
                if ((object.ReferenceEquals(this.CitizenshipCountry1Field, value) != true)) {
                    this.CitizenshipCountry1Field = value;
                    this.RaisePropertyChanged("CitizenshipCountry1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CitizenshipCountry2 {
            get {
                return this.CitizenshipCountry2Field;
            }
            set {
                if ((object.ReferenceEquals(this.CitizenshipCountry2Field, value) != true)) {
                    this.CitizenshipCountry2Field = value;
                    this.RaisePropertyChanged("CitizenshipCountry2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientCustomerId {
            get {
                return this.ClientCustomerIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientCustomerIdField, value) != true)) {
                    this.ClientCustomerIdField = value;
                    this.RaisePropertyChanged("ClientCustomerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerSince {
            get {
                return this.CustomerSinceField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerSinceField, value) != true)) {
                    this.CustomerSinceField = value;
                    this.RaisePropertyChanged("CustomerSince");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerType {
            get {
                return this.CustomerTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerTypeField, value) != true)) {
                    this.CustomerTypeField = value;
                    this.RaisePropertyChanged("CustomerType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DOB {
            get {
                return this.DOBField;
            }
            set {
                if ((object.ReferenceEquals(this.DOBField, value) != true)) {
                    this.DOBField = value;
                    this.RaisePropertyChanged("DOB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmployerName {
            get {
                return this.EmployerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployerNameField, value) != true)) {
                    this.EmployerNameField = value;
                    this.RaisePropertyChanged("EmployerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmployerPhoneNum {
            get {
                return this.EmployerPhoneNumField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployerPhoneNumField, value) != true)) {
                    this.EmployerPhoneNumField = value;
                    this.RaisePropertyChanged("EmployerPhoneNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((object.ReferenceEquals(this.GenderField, value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdExpDate {
            get {
                return this.IdExpDateField;
            }
            set {
                if ((object.ReferenceEquals(this.IdExpDateField, value) != true)) {
                    this.IdExpDateField = value;
                    this.RaisePropertyChanged("IdExpDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdIssueDate {
            get {
                return this.IdIssueDateField;
            }
            set {
                if ((object.ReferenceEquals(this.IdIssueDateField, value) != true)) {
                    this.IdIssueDateField = value;
                    this.RaisePropertyChanged("IdIssueDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdIssuer {
            get {
                return this.IdIssuerField;
            }
            set {
                if ((object.ReferenceEquals(this.IdIssuerField, value) != true)) {
                    this.IdIssuerField = value;
                    this.RaisePropertyChanged("IdIssuer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdIssuerCountry {
            get {
                return this.IdIssuerCountryField;
            }
            set {
                if ((object.ReferenceEquals(this.IdIssuerCountryField, value) != true)) {
                    this.IdIssuerCountryField = value;
                    this.RaisePropertyChanged("IdIssuerCountry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdNumber {
            get {
                return this.IdNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.IdNumberField, value) != true)) {
                    this.IdNumberField = value;
                    this.RaisePropertyChanged("IdNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdType {
            get {
                return this.IdTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.IdTypeField, value) != true)) {
                    this.IdTypeField = value;
                    this.RaisePropertyChanged("IdType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Maiden {
            get {
                return this.MaidenField;
            }
            set {
                if ((object.ReferenceEquals(this.MaidenField, value) != true)) {
                    this.MaidenField = value;
                    this.RaisePropertyChanged("Maiden");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MiddleName {
            get {
                return this.MiddleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MiddleNameField, value) != true)) {
                    this.MiddleNameField = value;
                    this.RaisePropertyChanged("MiddleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NEXXOPAN {
            get {
                return this.NEXXOPANField;
            }
            set {
                if ((object.ReferenceEquals(this.NEXXOPANField, value) != true)) {
                    this.NEXXOPANField = value;
                    this.RaisePropertyChanged("NEXXOPAN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OccDesc {
            get {
                return this.OccDescField;
            }
            set {
                if ((object.ReferenceEquals(this.OccDescField, value) != true)) {
                    this.OccDescField = value;
                    this.RaisePropertyChanged("OccDesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Occupation {
            get {
                return this.OccupationField;
            }
            set {
                if ((object.ReferenceEquals(this.OccupationField, value) != true)) {
                    this.OccupationField = value;
                    this.RaisePropertyChanged("Occupation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber1 {
            get {
                return this.PhoneNumber1Field;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumber1Field, value) != true)) {
                    this.PhoneNumber1Field = value;
                    this.RaisePropertyChanged("PhoneNumber1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber1Type {
            get {
                return this.PhoneNumber1TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumber1TypeField, value) != true)) {
                    this.PhoneNumber1TypeField = value;
                    this.RaisePropertyChanged("PhoneNumber1Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber2 {
            get {
                return this.PhoneNumber2Field;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumber2Field, value) != true)) {
                    this.PhoneNumber2Field = value;
                    this.RaisePropertyChanged("PhoneNumber2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber2Prov {
            get {
                return this.PhoneNumber2ProvField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumber2ProvField, value) != true)) {
                    this.PhoneNumber2ProvField = value;
                    this.RaisePropertyChanged("PhoneNumber2Prov");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber2Type {
            get {
                return this.PhoneNumber2TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumber2TypeField, value) != true)) {
                    this.PhoneNumber2TypeField = value;
                    this.RaisePropertyChanged("PhoneNumber2Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProdCode {
            get {
                return this.ProdCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ProdCodeField, value) != true)) {
                    this.ProdCodeField = value;
                    this.RaisePropertyChanged("ProdCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SSN {
            get {
                return this.SSNField;
            }
            set {
                if ((object.ReferenceEquals(this.SSNField, value) != true)) {
                    this.SSNField = value;
                    this.RaisePropertyChanged("SSN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TCFCustomerIndicator {
            get {
                return this.TCFCustomerIndicatorField;
            }
            set {
                if ((object.ReferenceEquals(this.TCFCustomerIndicatorField, value) != true)) {
                    this.TCFCustomerIndicatorField = value;
                    this.RaisePropertyChanged("TCFCustomerIndicator");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TCFExist {
            get {
                return this.TCFExistField;
            }
            set {
                if ((object.ReferenceEquals(this.TCFExistField, value) != true)) {
                    this.TCFExistField = value;
                    this.RaisePropertyChanged("TCFExist");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TCFPAN {
            get {
                return this.TCFPANField;
            }
            set {
                if ((object.ReferenceEquals(this.TCFPANField, value) != true)) {
                    this.TCFPANField = value;
                    this.RaisePropertyChanged("TCFPAN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TaxCode {
            get {
                return this.TaxCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.TaxCodeField, value) != true)) {
                    this.TaxCodeField = value;
                    this.RaisePropertyChanged("TaxCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Zip {
            get {
                return this.ZipField;
            }
            set {
                if ((object.ReferenceEquals(this.ZipField, value) != true)) {
                    this.ZipField = value;
                    this.RaisePropertyChanged("Zip");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ZeoTransaction", Namespace="http://schemas.datacontract.org/2004/07/TellerWorkQueueWS")]
    [System.SerializableAttribute()]
    public partial class ZeoTransaction : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AliasIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardNbrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CheckNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CheckTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConfirmationNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryOfBirthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DDAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DOBField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeliveryMethodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeliveryOptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FeeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InitialPurchaseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoadAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MTCNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NewCardBalanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OccupationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PayeeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PickupCityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PickupCountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PickupStateProvinceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PurchaseFeeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecondLastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateProvinceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TCFABAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TCFAccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TCFApplField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ToAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ToCityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ToCountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ToCountryOfBirthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ToDOBField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ToDeliveryMethodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ToDeliveryOptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ToFirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ToGenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ToLastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ToMiddleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ToOccupationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ToPhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ToPickupCityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ToPickupCountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ToPickupStateProvinceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ToSecondLastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ToStateProvinceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ToZipCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TranIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TranTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WithdrawAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZipCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountNumber {
            get {
                return this.AccountNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountNumberField, value) != true)) {
                    this.AccountNumberField = value;
                    this.RaisePropertyChanged("AccountNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AliasId {
            get {
                return this.AliasIdField;
            }
            set {
                if ((object.ReferenceEquals(this.AliasIdField, value) != true)) {
                    this.AliasIdField = value;
                    this.RaisePropertyChanged("AliasId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((object.ReferenceEquals(this.AmountField, value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardNbr {
            get {
                return this.CardNbrField;
            }
            set {
                if ((object.ReferenceEquals(this.CardNbrField, value) != true)) {
                    this.CardNbrField = value;
                    this.RaisePropertyChanged("CardNbr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CheckNumber {
            get {
                return this.CheckNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CheckNumberField, value) != true)) {
                    this.CheckNumberField = value;
                    this.RaisePropertyChanged("CheckNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CheckType {
            get {
                return this.CheckTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.CheckTypeField, value) != true)) {
                    this.CheckTypeField = value;
                    this.RaisePropertyChanged("CheckType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConfirmationNumber {
            get {
                return this.ConfirmationNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ConfirmationNumberField, value) != true)) {
                    this.ConfirmationNumberField = value;
                    this.RaisePropertyChanged("ConfirmationNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountryOfBirth {
            get {
                return this.CountryOfBirthField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryOfBirthField, value) != true)) {
                    this.CountryOfBirthField = value;
                    this.RaisePropertyChanged("CountryOfBirth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DDA {
            get {
                return this.DDAField;
            }
            set {
                if ((object.ReferenceEquals(this.DDAField, value) != true)) {
                    this.DDAField = value;
                    this.RaisePropertyChanged("DDA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DOB {
            get {
                return this.DOBField;
            }
            set {
                if ((object.ReferenceEquals(this.DOBField, value) != true)) {
                    this.DOBField = value;
                    this.RaisePropertyChanged("DOB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeliveryMethod {
            get {
                return this.DeliveryMethodField;
            }
            set {
                if ((object.ReferenceEquals(this.DeliveryMethodField, value) != true)) {
                    this.DeliveryMethodField = value;
                    this.RaisePropertyChanged("DeliveryMethod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeliveryOption {
            get {
                return this.DeliveryOptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DeliveryOptionField, value) != true)) {
                    this.DeliveryOptionField = value;
                    this.RaisePropertyChanged("DeliveryOption");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fee {
            get {
                return this.FeeField;
            }
            set {
                if ((object.ReferenceEquals(this.FeeField, value) != true)) {
                    this.FeeField = value;
                    this.RaisePropertyChanged("Fee");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((object.ReferenceEquals(this.GenderField, value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InitialPurchase {
            get {
                return this.InitialPurchaseField;
            }
            set {
                if ((object.ReferenceEquals(this.InitialPurchaseField, value) != true)) {
                    this.InitialPurchaseField = value;
                    this.RaisePropertyChanged("InitialPurchase");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoadAmount {
            get {
                return this.LoadAmountField;
            }
            set {
                if ((object.ReferenceEquals(this.LoadAmountField, value) != true)) {
                    this.LoadAmountField = value;
                    this.RaisePropertyChanged("LoadAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MTCN {
            get {
                return this.MTCNField;
            }
            set {
                if ((object.ReferenceEquals(this.MTCNField, value) != true)) {
                    this.MTCNField = value;
                    this.RaisePropertyChanged("MTCN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NewCardBalance {
            get {
                return this.NewCardBalanceField;
            }
            set {
                if ((object.ReferenceEquals(this.NewCardBalanceField, value) != true)) {
                    this.NewCardBalanceField = value;
                    this.RaisePropertyChanged("NewCardBalance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Occupation {
            get {
                return this.OccupationField;
            }
            set {
                if ((object.ReferenceEquals(this.OccupationField, value) != true)) {
                    this.OccupationField = value;
                    this.RaisePropertyChanged("Occupation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Payee {
            get {
                return this.PayeeField;
            }
            set {
                if ((object.ReferenceEquals(this.PayeeField, value) != true)) {
                    this.PayeeField = value;
                    this.RaisePropertyChanged("Payee");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PickupCity {
            get {
                return this.PickupCityField;
            }
            set {
                if ((object.ReferenceEquals(this.PickupCityField, value) != true)) {
                    this.PickupCityField = value;
                    this.RaisePropertyChanged("PickupCity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PickupCountry {
            get {
                return this.PickupCountryField;
            }
            set {
                if ((object.ReferenceEquals(this.PickupCountryField, value) != true)) {
                    this.PickupCountryField = value;
                    this.RaisePropertyChanged("PickupCountry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PickupStateProvince {
            get {
                return this.PickupStateProvinceField;
            }
            set {
                if ((object.ReferenceEquals(this.PickupStateProvinceField, value) != true)) {
                    this.PickupStateProvinceField = value;
                    this.RaisePropertyChanged("PickupStateProvince");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PurchaseFee {
            get {
                return this.PurchaseFeeField;
            }
            set {
                if ((object.ReferenceEquals(this.PurchaseFeeField, value) != true)) {
                    this.PurchaseFeeField = value;
                    this.RaisePropertyChanged("PurchaseFee");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SecondLastName {
            get {
                return this.SecondLastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SecondLastNameField, value) != true)) {
                    this.SecondLastNameField = value;
                    this.RaisePropertyChanged("SecondLastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StateProvince {
            get {
                return this.StateProvinceField;
            }
            set {
                if ((object.ReferenceEquals(this.StateProvinceField, value) != true)) {
                    this.StateProvinceField = value;
                    this.RaisePropertyChanged("StateProvince");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TCFABA {
            get {
                return this.TCFABAField;
            }
            set {
                if ((object.ReferenceEquals(this.TCFABAField, value) != true)) {
                    this.TCFABAField = value;
                    this.RaisePropertyChanged("TCFABA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TCFAccount {
            get {
                return this.TCFAccountField;
            }
            set {
                if ((object.ReferenceEquals(this.TCFAccountField, value) != true)) {
                    this.TCFAccountField = value;
                    this.RaisePropertyChanged("TCFAccount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TCFAppl {
            get {
                return this.TCFApplField;
            }
            set {
                if ((object.ReferenceEquals(this.TCFApplField, value) != true)) {
                    this.TCFApplField = value;
                    this.RaisePropertyChanged("TCFAppl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToAddress {
            get {
                return this.ToAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.ToAddressField, value) != true)) {
                    this.ToAddressField = value;
                    this.RaisePropertyChanged("ToAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToCity {
            get {
                return this.ToCityField;
            }
            set {
                if ((object.ReferenceEquals(this.ToCityField, value) != true)) {
                    this.ToCityField = value;
                    this.RaisePropertyChanged("ToCity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToCountry {
            get {
                return this.ToCountryField;
            }
            set {
                if ((object.ReferenceEquals(this.ToCountryField, value) != true)) {
                    this.ToCountryField = value;
                    this.RaisePropertyChanged("ToCountry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToCountryOfBirth {
            get {
                return this.ToCountryOfBirthField;
            }
            set {
                if ((object.ReferenceEquals(this.ToCountryOfBirthField, value) != true)) {
                    this.ToCountryOfBirthField = value;
                    this.RaisePropertyChanged("ToCountryOfBirth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToDOB {
            get {
                return this.ToDOBField;
            }
            set {
                if ((object.ReferenceEquals(this.ToDOBField, value) != true)) {
                    this.ToDOBField = value;
                    this.RaisePropertyChanged("ToDOB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToDeliveryMethod {
            get {
                return this.ToDeliveryMethodField;
            }
            set {
                if ((object.ReferenceEquals(this.ToDeliveryMethodField, value) != true)) {
                    this.ToDeliveryMethodField = value;
                    this.RaisePropertyChanged("ToDeliveryMethod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToDeliveryOption {
            get {
                return this.ToDeliveryOptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ToDeliveryOptionField, value) != true)) {
                    this.ToDeliveryOptionField = value;
                    this.RaisePropertyChanged("ToDeliveryOption");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToFirstName {
            get {
                return this.ToFirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ToFirstNameField, value) != true)) {
                    this.ToFirstNameField = value;
                    this.RaisePropertyChanged("ToFirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToGender {
            get {
                return this.ToGenderField;
            }
            set {
                if ((object.ReferenceEquals(this.ToGenderField, value) != true)) {
                    this.ToGenderField = value;
                    this.RaisePropertyChanged("ToGender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToLastName {
            get {
                return this.ToLastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ToLastNameField, value) != true)) {
                    this.ToLastNameField = value;
                    this.RaisePropertyChanged("ToLastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToMiddleName {
            get {
                return this.ToMiddleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ToMiddleNameField, value) != true)) {
                    this.ToMiddleNameField = value;
                    this.RaisePropertyChanged("ToMiddleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToOccupation {
            get {
                return this.ToOccupationField;
            }
            set {
                if ((object.ReferenceEquals(this.ToOccupationField, value) != true)) {
                    this.ToOccupationField = value;
                    this.RaisePropertyChanged("ToOccupation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToPhoneNumber {
            get {
                return this.ToPhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ToPhoneNumberField, value) != true)) {
                    this.ToPhoneNumberField = value;
                    this.RaisePropertyChanged("ToPhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToPickupCity {
            get {
                return this.ToPickupCityField;
            }
            set {
                if ((object.ReferenceEquals(this.ToPickupCityField, value) != true)) {
                    this.ToPickupCityField = value;
                    this.RaisePropertyChanged("ToPickupCity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToPickupCountry {
            get {
                return this.ToPickupCountryField;
            }
            set {
                if ((object.ReferenceEquals(this.ToPickupCountryField, value) != true)) {
                    this.ToPickupCountryField = value;
                    this.RaisePropertyChanged("ToPickupCountry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToPickupStateProvince {
            get {
                return this.ToPickupStateProvinceField;
            }
            set {
                if ((object.ReferenceEquals(this.ToPickupStateProvinceField, value) != true)) {
                    this.ToPickupStateProvinceField = value;
                    this.RaisePropertyChanged("ToPickupStateProvince");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToSecondLastName {
            get {
                return this.ToSecondLastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ToSecondLastNameField, value) != true)) {
                    this.ToSecondLastNameField = value;
                    this.RaisePropertyChanged("ToSecondLastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToStateProvince {
            get {
                return this.ToStateProvinceField;
            }
            set {
                if ((object.ReferenceEquals(this.ToStateProvinceField, value) != true)) {
                    this.ToStateProvinceField = value;
                    this.RaisePropertyChanged("ToStateProvince");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToZipCode {
            get {
                return this.ToZipCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ToZipCodeField, value) != true)) {
                    this.ToZipCodeField = value;
                    this.RaisePropertyChanged("ToZipCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Total {
            get {
                return this.TotalField;
            }
            set {
                if ((object.ReferenceEquals(this.TotalField, value) != true)) {
                    this.TotalField = value;
                    this.RaisePropertyChanged("Total");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TranId {
            get {
                return this.TranIdField;
            }
            set {
                if ((object.ReferenceEquals(this.TranIdField, value) != true)) {
                    this.TranIdField = value;
                    this.RaisePropertyChanged("TranId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TranType {
            get {
                return this.TranTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TranTypeField, value) != true)) {
                    this.TranTypeField = value;
                    this.RaisePropertyChanged("TranType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WithdrawAmount {
            get {
                return this.WithdrawAmountField;
            }
            set {
                if ((object.ReferenceEquals(this.WithdrawAmountField, value) != true)) {
                    this.WithdrawAmountField = value;
                    this.RaisePropertyChanged("WithdrawAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZipCode {
            get {
                return this.ZipCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ZipCodeField, value) != true)) {
                    this.ZipCodeField = value;
                    this.RaisePropertyChanged("ZipCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PrecartResponse", Namespace="http://schemas.datacontract.org/2004/07/TellerWorkQueueWS")]
    [System.SerializableAttribute()]
    public partial class PrecartResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PostcartRequest", Namespace="http://schemas.datacontract.org/2004/07/TellerWorkQueueWS")]
    [System.SerializableAttribute()]
    public partial class PostcartRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BasicAuthInfo BasicAuthInformationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CustomerInfo CustomerInformationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SessionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ZeoTransaction TransactionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BasicAuthInfo BasicAuthInformation {
            get {
                return this.BasicAuthInformationField;
            }
            set {
                if ((object.ReferenceEquals(this.BasicAuthInformationField, value) != true)) {
                    this.BasicAuthInformationField = value;
                    this.RaisePropertyChanged("BasicAuthInformation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CustomerInfo CustomerInformation {
            get {
                return this.CustomerInformationField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerInformationField, value) != true)) {
                    this.CustomerInformationField = value;
                    this.RaisePropertyChanged("CustomerInformation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SessionId {
            get {
                return this.SessionIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SessionIdField, value) != true)) {
                    this.SessionIdField = value;
                    this.RaisePropertyChanged("SessionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ZeoTransaction Transaction {
            get {
                return this.TransactionField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionField, value) != true)) {
                    this.TransactionField = value;
                    this.RaisePropertyChanged("Transaction");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PostcartResponse", Namespace="http://schemas.datacontract.org/2004/07/TellerWorkQueueWS")]
    [System.SerializableAttribute()]
    public partial class PostcartResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerRiskScoreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GPRRiskScoreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TemplateTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TranIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TranTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZeoServicesRiskScoreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerRiskScore {
            get {
                return this.CustomerRiskScoreField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerRiskScoreField, value) != true)) {
                    this.CustomerRiskScoreField = value;
                    this.RaisePropertyChanged("CustomerRiskScore");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GPRRiskScore {
            get {
                return this.GPRRiskScoreField;
            }
            set {
                if ((object.ReferenceEquals(this.GPRRiskScoreField, value) != true)) {
                    this.GPRRiskScoreField = value;
                    this.RaisePropertyChanged("GPRRiskScore");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TemplateType {
            get {
                return this.TemplateTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TemplateTypeField, value) != true)) {
                    this.TemplateTypeField = value;
                    this.RaisePropertyChanged("TemplateType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TranId {
            get {
                return this.TranIdField;
            }
            set {
                if ((object.ReferenceEquals(this.TranIdField, value) != true)) {
                    this.TranIdField = value;
                    this.RaisePropertyChanged("TranId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TranType {
            get {
                return this.TranTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TranTypeField, value) != true)) {
                    this.TranTypeField = value;
                    this.RaisePropertyChanged("TranType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZeoServicesRiskScore {
            get {
                return this.ZeoServicesRiskScoreField;
            }
            set {
                if ((object.ReferenceEquals(this.ZeoServicesRiskScoreField, value) != true)) {
                    this.ZeoServicesRiskScoreField = value;
                    this.RaisePropertyChanged("ZeoServicesRiskScore");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TellerWorkQueueService.ITellerWorkQueueWS")]
    public interface ITellerWorkQueueWS {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITellerWorkQueueWS/Precart", ReplyAction="http://tempuri.org/ITellerWorkQueueWS/PrecartResponse")]
        PrecartResponse Precart(PrecartRequest preCartRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITellerWorkQueueWS/Precart", ReplyAction="http://tempuri.org/ITellerWorkQueueWS/PrecartResponse")]
        System.Threading.Tasks.Task<PrecartResponse> PrecartAsync(PrecartRequest preCartRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITellerWorkQueueWS/GetTodoList", ReplyAction="http://tempuri.org/ITellerWorkQueueWS/GetTodoListResponse")]
        System.Xml.Linq.XElement GetTodoList(string userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITellerWorkQueueWS/GetTodoList", ReplyAction="http://tempuri.org/ITellerWorkQueueWS/GetTodoListResponse")]
        System.Threading.Tasks.Task<System.Xml.Linq.XElement> GetTodoListAsync(string userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITellerWorkQueueWS/UpdateWorkItem", ReplyAction="http://tempuri.org/ITellerWorkQueueWS/UpdateWorkItemResponse")]
        string UpdateWorkItem(string userId, System.Xml.Linq.XElement todoList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITellerWorkQueueWS/UpdateWorkItem", ReplyAction="http://tempuri.org/ITellerWorkQueueWS/UpdateWorkItemResponse")]
        System.Threading.Tasks.Task<string> UpdateWorkItemAsync(string userId, System.Xml.Linq.XElement todoList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITellerWorkQueueWS/Postcart", ReplyAction="http://tempuri.org/ITellerWorkQueueWS/PostcartResponse")]
        PostcartResponse Postcart(PostcartRequest postcartRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITellerWorkQueueWS/Postcart", ReplyAction="http://tempuri.org/ITellerWorkQueueWS/PostcartResponse")]
        System.Threading.Tasks.Task<PostcartResponse> PostcartAsync(PostcartRequest postcartRequest);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITellerWorkQueueWSChannel : ITellerWorkQueueWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TellerWorkQueueWSClient : System.ServiceModel.ClientBase<ITellerWorkQueueWS>, ITellerWorkQueueWS {
        
        public TellerWorkQueueWSClient() {
        }
        
        public TellerWorkQueueWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TellerWorkQueueWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TellerWorkQueueWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TellerWorkQueueWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PrecartResponse Precart(PrecartRequest preCartRequest) {
            return base.Channel.Precart(preCartRequest);
        }
        
        public System.Threading.Tasks.Task<PrecartResponse> PrecartAsync(PrecartRequest preCartRequest) {
            return base.Channel.PrecartAsync(preCartRequest);
        }
        
        public System.Xml.Linq.XElement GetTodoList(string userId) {
            return base.Channel.GetTodoList(userId);
        }
        
        public System.Threading.Tasks.Task<System.Xml.Linq.XElement> GetTodoListAsync(string userId) {
            return base.Channel.GetTodoListAsync(userId);
        }
        
        public string UpdateWorkItem(string userId, System.Xml.Linq.XElement todoList) {
            return base.Channel.UpdateWorkItem(userId, todoList);
        }
        
        public System.Threading.Tasks.Task<string> UpdateWorkItemAsync(string userId, System.Xml.Linq.XElement todoList) {
            return base.Channel.UpdateWorkItemAsync(userId, todoList);
        }
        
        public PostcartResponse Postcart(PostcartRequest postcartRequest) {
            return base.Channel.Postcart(postcartRequest);
        }
        
        public System.Threading.Tasks.Task<PostcartResponse> PostcartAsync(PostcartRequest postcartRequest) {
            return base.Channel.PostcartAsync(postcartRequest);
        }
    }
}
