USE [master]
GO

/****** Object:  Database [CXE]    Script Date: 04/04/2013 13:52:37 ******/
CREATE DATABASE [CXE] ON  PRIMARY 
( NAME = N'CXE', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MDOWD\MSSQL\DATA\CXE.mdf' , SIZE = 2048KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'CXE_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MDOWD\MSSQL\DATA\CXE_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [CXE] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CXE].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CXE] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CXE] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CXE] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CXE] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CXE] SET ARITHABORT OFF 
GO

ALTER DATABASE [CXE] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CXE] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [CXE] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CXE] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CXE] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CXE] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CXE] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CXE] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CXE] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CXE] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CXE] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CXE] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CXE] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CXE] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CXE] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CXE] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CXE] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CXE] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CXE] SET  READ_WRITE 
GO

ALTER DATABASE [CXE] SET RECOVERY FULL 
GO

ALTER DATABASE [CXE] SET  MULTI_USER 
GO

ALTER DATABASE [CXE] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CXE] SET DB_CHAINING OFF 
GO


