

IF EXISTS (SELECT *
           FROM   sysobjects 
           WHERE  type = 'P'
                  AND name = 'USP_EX_DelPolicyitemCascade')
    BEGIN
        DROP PROCEDURE USP_EX_DelPolicyitemCascade;
        PRINT 'DROPPED USP_EX_DelPolicyitemCascade';
    END
GO 

  
/******************************************************************************                    
** Name : USP_EX_DelPolicyitemCascade
** Old Name:     USP_EIS_EX_POLICYITEM_CASCADE_DelProc                     
** Short Desc: To Insert/Update the POLICYITEM table for a particular dimension.              
**                    
** Full Description: To Insert/Update the POLICYITEM table for a particular dimension.              
**                            
 @POLICYDIMENSIONID INT ,  
 @ENTITY_TYPE VARCHAR(100),  
 @ENTITY_ID INT,  
 @USERID INT  
** Sample Call                    
        EXEC USP_EIS_EX_POLICYITEM_CASCADE_DelProc  'Income Accrual Pol',18,100,100002,18              
**                    
** Return values: NONE                    
**                    
**                    
** Standard declarations                    
**       SET LOCK_TIMEOUT         30000   -- 30 seconds                    
**                     
** Created By: VShivhare                    
** Company   : Kaspick & Company                    
** Project   : Excelsior                    
** Created DT: July 04 2007  
**                                
*******************************************************************************              
**       Change History                    
*******************************************************************************              
** Date:        Author:  Bug #     Description:                           Rvwd              
** --------     -------- ------    -------------------------------------- --------    
** 03/18/2008 Saravanan PM ET# 6274 Modified  && Updating Billing Information of TA - Only Acount Level BillingProfile            
** 12/04/2014 Yugandhar				Rewritten  Excelsior 6.1
*******************************************************************************                    
** Copyright (C) <CopyrightYear,,Year> Kaspick & Company, All Rights Reserved                    
** COMPANY CONFIDENTIAL -- NOT FOR DISTRIBUTION      

--Sample Call
USP_EX_DelPolicyitemCascade 18,'program','100002',18               
*******************************************************************************/                    
CREATE PROCEDURE USP_EX_DelPolicyitemCascade 
(  
 @POLICYDIMENSIONID INT ,  
 @ENTITY_TYPE VARCHAR(100),  
 @ENTITY_ID VARCHAR(15),  
 @USERID INT  
)  
AS  
BEGIN   
BEGIN TRY  
 DECLARE   
 @MAX_POLICY_LEVEL INT,  
 @MIN_RECORDID INT,  
 @MAX_RECORDID INT,  
 @DATA_TYPE VARCHAR(20),  
 @POLICY_LEVEL INT,  
 @BLN_RESULT BIT,  
 @VAL_DATE DATETIME,  
 @VAL_LIST INT ,  
 @VAL_NUMERIC FLOAT,  
 @VAL_TEXT VARCHAR(100),   
 @VAL_LOGICAL BIT,  
 @TMP_PRG_ID VARCHAR(15),  
 @POLICYITEM_ID INT,  
 @TMP_CL_ID Varchar(15),  
    @PRE_DATEVAL DATETIME,  
 @PRE_NUMERICVAL FLOAT,  
 @PRE_LISTVAL INT,  
 @PRE_TEXTVAL VARCHAR(100),  
 @PRE_LOGICALVAL BIT ,  
    @G_DATEVAL DATETIME,  
 @G_NUMERICVAL FLOAT,  
 @G_LISTVAL INT,  
 @G_TEXTVAL VARCHAR(100),  
 @G_LOGICALVAL BIT ,  
  
 @DONOR_BENE_TAX_HIGH_PRIORITY INT  
  
 SELECT @DONOR_BENE_TAX_HIGH_PRIORITY = PolicyDimensionID FROM TBL_POLICYDIMENSION WHERE FULLNAME = 'HIGH PRIORITY'  
  
 --Declare Temp Table  
 DECLARE @TMP_CL_PRG TABLE(PROGRAMID VARCHAR(15)) --Temp Table for Client Program  
 DECLARE @TMP_PRG_EQUAL TABLE(PROGRAMID varchar(15)) --Temp Table for Client Program with equal value  
 DECLARE @TMP_ACT_EQUAL TABLE(ACCOUNTID VARCHAR(14)) --Temp Table for Client ACCOUNT with equal value  
 DECLARE @TMP_PR_ACT TABLE(ACCOUNTID VARCHAR(14)) --Temp Table for Program Account  
  
 DECLARE @TMP_ACT_BILL_PROFILE TABLE(ID INT  IDENTITY (1,1), ACCOUNTID INT, BILLINGSTARTDATE DATETIME) --Temp Table for Account Billing Start date  
  
 --get policy dimension details for selected policydimension  
 SELECT @MAX_POLICY_LEVEL=MAXPOLICYLEVEL, @DATA_TYPE=DATATYPE FROM TBL_PolicyDimension WHERE POLICYDIMENSIONID =@POLICYDIMENSIONID  
 --If the policy is being changed from Client page/level  
 IF(@ENTITY_TYPE='MANAGER')  
 BEGIN  
   --Collect all programs defined for the selected client  
   INSERT INTO @TMP_CL_PRG SELECT AllianceNumber FROM SYN_IT_AccountMaster WHERE ManagerCode=@ENTITY_ID  
  
   --Set all the previous client policy values  
    SELECT   
     @PRE_DATEVAL=DATEVALUE ,  
     @PRE_NUMERICVAL=NUMERICVALUE ,  
     @PRE_LISTVAL=POLICYDROPDOWNID ,  
     @PRE_LOGICALVAL=LOGICALVALUE,  
     @PRE_TEXTVAL=TEXTVALUE  
    FROM TBL_PolicyItem   
    WHERE  OWNERID=@ENTITY_ID AND POLICYLEVEL=100 AND POLICYDIMENSIONID=@POLICYDIMENSIONID  
  
   IF(@DATA_TYPE='DATE')  
    BEGIN  
     INSERT INTO @TMP_PRG_EQUAL (PROGRAMID)  
      SELECT OWNERID FROM TBL_PolicyItem   
      WHERE  POLICYLEVEL=200   
      AND POLICYDIMENSIONID=@POLICYDIMENSIONID  
      AND DATEDIFF(DAY,DATEVALUE,@PRE_DATEVAL)=0  
      AND OWNERID IN (SELECT PROGRAMID FROM @TMP_CL_PRG)  
    END  
    ELSE IF(@DATA_TYPE='LIST')  
    BEGIN  
     INSERT INTO @TMP_PRG_EQUAL (PROGRAMID)  
      SELECT OWNERID FROM TBL_PolicyItem   
      WHERE  POLICYLEVEL=200   
      AND POLICYDIMENSIONID=@POLICYDIMENSIONID  
      AND  POLICYDROPDOWNID = @PRE_LISTVAL  
      AND OWNERID IN (SELECT PROGRAMID FROM @TMP_CL_PRG)  
    END  
    ELSE IF(@DATA_TYPE='LOGICAL')  
    BEGIN  
     INSERT INTO @TMP_PRG_EQUAL (PROGRAMID)  
      SELECT OWNERID FROM TBL_PolicyItem   
      WHERE  POLICYLEVEL=200   
      AND POLICYDIMENSIONID=@POLICYDIMENSIONID  
      AND LOGICALVALUE = @PRE_LOGICALVAL  
      AND OWNERID IN (SELECT PROGRAMID FROM @TMP_CL_PRG)  
      END  
      ELSE IF(@DATA_TYPE='NUMERIC')  
      BEGIN  
     INSERT INTO @TMP_PRG_EQUAL (PROGRAMID)  
      SELECT OWNERID FROM TBL_PolicyItem   
      WHERE  POLICYLEVEL=200   
      AND POLICYDIMENSIONID=@POLICYDIMENSIONID  
      AND NUMERICVALUE = @PRE_NUMERICVAL  
      AND OWNERID IN (SELECT PROGRAMID FROM @TMP_CL_PRG)  
    END  
    ELSE IF(@DATA_TYPE='TEXT')  
    BEGIN  
     INSERT INTO @TMP_PRG_EQUAL (PROGRAMID)  
      SELECT OWNERID FROM TBL_PolicyItem   
      WHERE  POLICYLEVEL=200   
      AND POLICYDIMENSIONID=@POLICYDIMENSIONID  
      AND TEXTVALUE = @PRE_TEXTVAL  
      AND OWNERID IN (SELECT PROGRAMID FROM @TMP_CL_PRG)  
    END  
    --fetch all the account under matching programs for this client  
    --------------------------------------  
    IF(@DATA_TYPE='DATE')  
    BEGIN  
     INSERT INTO @TMP_ACT_EQUAL (ACCOUNTID)  
      SELECT OWNERID FROM TBL_PolicyItem   
      WHERE  POLICYLEVEL=300   
      AND POLICYDIMENSIONID=@POLICYDIMENSIONID  
      AND DATEDIFF(DAY,DATEVALUE,@PRE_DATEVAL)=0  
      AND OWNERID IN (SELECT CustomerAccountNumber FROM SYN_IT_AccountMaster WHERE Alliancenumber IN   
               (SELECT PROGRAMID FROM @TMP_PRG_EQUAL))  
    END  
    ELSE IF(@DATA_TYPE='LIST')  
    BEGIN  
     INSERT INTO @TMP_ACT_EQUAL (ACCOUNTID)  
      SELECT OWNERID FROM TBL_PolicyItem   
      WHERE  POLICYLEVEL=300   
      AND POLICYDIMENSIONID=@POLICYDIMENSIONID  
      AND  POLICYDROPDOWNID = @PRE_LISTVAL  
      AND OWNERID IN (SELECT CustomerAccountNumber FROM SYN_IT_AccountMaster WHERE Alliancenumber IN   
               (SELECT PROGRAMID FROM @TMP_PRG_EQUAL))  
    END  
    ELSE IF(@DATA_TYPE='LOGICAL')  
    BEGIN  
     INSERT INTO @TMP_ACT_EQUAL (ACCOUNTID)  
      SELECT OWNERID FROM TBL_PolicyItem   
      WHERE  POLICYLEVEL=300   
      AND POLICYDIMENSIONID=@POLICYDIMENSIONID  
      AND LOGICALVALUE = @PRE_LOGICALVAL  
      AND OWNERID IN (SELECT CustomerAccountNumber FROM SYN_IT_AccountMaster WHERE Alliancenumber IN   
               (SELECT PROGRAMID FROM @TMP_PRG_EQUAL))  
      END  
      ELSE IF(@DATA_TYPE='NUMERIC')  
      BEGIN  
     INSERT INTO @TMP_ACT_EQUAL (ACCOUNTID)  
      SELECT OWNERID FROM TBL_PolicyItem   
      WHERE  POLICYLEVEL=300   
      AND POLICYDIMENSIONID=@POLICYDIMENSIONID  
      AND NUMERICVALUE = @PRE_NUMERICVAL  
      AND OWNERID IN (SELECT CustomerAccountNumber FROM SYN_IT_AccountMaster WHERE Alliancenumber IN   
               (SELECT PROGRAMID FROM @TMP_PRG_EQUAL))  
    END  
    ELSE IF(@DATA_TYPE='TEXT')  
    BEGIN  
     INSERT INTO @TMP_ACT_EQUAL (ACCOUNTID)  
      SELECT OWNERID FROM TBL_PolicyItem   
      WHERE  POLICYLEVEL=300   
      AND POLICYDIMENSIONID=@POLICYDIMENSIONID  
      AND TEXTVALUE = @PRE_TEXTVAL  
      AND OWNERID IN (SELECT CustomerAccountNumber FROM SYN_IT_AccountMaster WHERE Alliancenumber IN   
               (SELECT PROGRAMID FROM @TMP_PRG_EQUAL))  
    END  
  
    --Update for Client  
    UPDATE TBL_POLICYITEM   
    SET DELETEDUSERID=@USERID,  
     MODIFIEDDATE=GETDATE()  
    WHERE POLICYITEMID IN(SELECT POLICYITEMID FROM TBL_PolicyItem   
         WHERE OWNERID=@ENTITY_ID AND POLICYLEVEL=100   
         AND POLICYDIMENSIONID=@POLICYDIMENSIONID)  
  
    --Update for all Client Program  
    UPDATE TBL_POLICYITEM  
    SET DELETEDUSERID=@USERID,  
     MODIFIEDDATE=GETDATE()  
    WHERE POLICYITEMID IN(SELECT POLICYITEMID FROM TBL_PolicyItem   
         WHERE OWNERID IN(SELECT PROGRAMID FROM @TMP_PRG_EQUAL)  
         AND POLICYLEVEL=200 AND POLICYDIMENSIONID=@POLICYDIMENSIONID)  
      
    --Update for all Client Program Account  
    UPDATE TBL_POLICYITEM  
    SET DELETEDUSERID=@USERID,  
     MODIFIEDDATE=GETDATE()  
    WHERE POLICYITEMID IN (SELECT POLICYITEMID FROM TBL_PolicyItem   
         WHERE OWNERID IN (SELECT ACCOUNTID FROM @TMP_ACT_EQUAL)  
         AND POLICYLEVEL=300 AND POLICYDIMENSIONID=@POLICYDIMENSIONID)  
  
    --Delete from Policy Item  
    DELETE FROM TBL_POLICYITEM  
    WHERE POLICYITEMID IN(SELECT POLICYITEMID FROM TBL_PolicyItem   
         WHERE OWNERID=@ENTITY_ID AND POLICYLEVEL=100   
         AND POLICYDIMENSIONID=@POLICYDIMENSIONID)  
      
    DELETE FROM TBL_POLICYITEM 
    WHERE POLICYITEMID IN(SELECT POLICYITEMID FROM TBL_PolicyItem   
         WHERE OWNERID IN(SELECT PROGRAMID FROM @TMP_PRG_EQUAL)  
         AND POLICYLEVEL=200 AND POLICYDIMENSIONID=@POLICYDIMENSIONID)  
      
    DELETE FROM TBL_POLICYITEM  
    WHERE POLICYITEMID IN(SELECT POLICYITEMID FROM TBL_PolicyItem   
         WHERE OWNERID IN((SELECT ACCOUNTID FROM @TMP_ACT_EQUAL))  
         AND POLICYLEVEL=300 AND POLICYDIMENSIONID=@POLICYDIMENSIONID)  
  
    DELETE FROM TBL_PolicyItem  
    WHERE OWNERID=@ENTITY_ID AND POLICYLEVEL=100 AND POLICYDIMENSIONID=@POLICYDIMENSIONID   
  
    DELETE FROM TBL_PolicyItem  
    WHERE OWNERID IN(SELECT PROGRAMID FROM @TMP_PRG_EQUAL)  
    AND POLICYLEVEL=200 AND POLICYDIMENSIONID=@POLICYDIMENSIONID  
  
    DELETE FROM TBL_PolicyItem  
    WHERE OWNERID IN((SELECT ACCOUNTID FROM @TMP_ACT_EQUAL))  
    AND POLICYLEVEL=300 AND POLICYDIMENSIONID=@POLICYDIMENSIONID  
        
  END  
  ELSE IF(@ENTITY_TYPE='ALLIANCE')  
  BEGIN  
   --retrive client ID for this program  
   SELECT @TMP_CL_ID = Managercode FROM SYN_IT_ContactMaster WHERE Alliancenumber = @ENTITY_ID  
   --first update this value with client & then  
   --Fetch all the account for this program,if value matches for any account then update  
   --Check for Client value  
   INSERT INTO @TMP_PR_ACT SELECT CustomerAccountNumber FROM SYN_IT_AccountMaster WHERE Alliancenumber=@ENTITY_ID  
   --retrive program policy item record  
   SELECT    
    @POLICYITEM_ID = POLICYITEMID,  
    @PRE_DATEVAL=DATEVALUE ,  
    @PRE_NUMERICVAL=NUMERICVALUE ,  
    @PRE_LISTVAL=POLICYDROPDOWNID ,  
    @PRE_LOGICALVAL=LOGICALVALUE,  
    @PRE_TEXTVAL=TEXTVALUE  
   FROM TBL_PolicyItem  
   WHERE OWNERID=@ENTITY_ID AND POLICYLEVEL=200 AND POLICYDIMENSIONID=@POLICYDIMENSIONID  
   --check if policy item record exists client  
   IF EXISTS(SELECT POLICYITEMID FROM TBL_PolicyItem WHERE OWNERID=@TMP_CL_ID AND POLICYLEVEL=100 AND POLICYDIMENSIONID=@POLICYDIMENSIONID)  
   BEGIN  
    SELECT    
     @VAL_DATE=DATEVALUE ,  
     @VAL_NUMERIC=NUMERICVALUE ,  
     @VAL_LIST=POLICYDROPDOWNID ,  
     @VAL_LOGICAL=LOGICALVALUE,  
     @VAL_TEXT=TEXTVALUE  
    FROM TBL_PolicyItem  
    WHERE OWNERID=@TMP_CL_ID AND POLICYLEVEL=100 AND POLICYDIMENSIONID=@POLICYDIMENSIONID  
   END  
  
   ELSE --if no value exists at both levels delete & return  
   BEGIN  
    IF(@DATA_TYPE='DATE')  
    BEGIN  
     INSERT INTO @TMP_ACT_EQUAL (ACCOUNTID)  
      SELECT OWNERID FROM TBL_PolicyItem   
      WHERE  POLICYLEVEL=300   
      AND POLICYDIMENSIONID=@POLICYDIMENSIONID  
      AND DATEDIFF(DAY,DATEVALUE,@PRE_DATEVAL)=0  
      AND OWNERID IN (SELECT ACCOUNTID FROM @TMP_PR_ACT)  
    END  
    ELSE IF(@DATA_TYPE='LIST')  
    BEGIN  
     INSERT INTO @TMP_ACT_EQUAL (ACCOUNTID)  
      SELECT OWNERID FROM TBL_PolicyItem   
      WHERE  POLICYLEVEL=300   
      AND POLICYDIMENSIONID=@POLICYDIMENSIONID  
      AND  POLICYDROPDOWNID = @PRE_LISTVAL  
      AND OWNERID IN (SELECT ACCOUNTID FROM @TMP_PR_ACT)  
    END  
    ELSE IF(@DATA_TYPE='LOGICAL')  
    BEGIN  
     INSERT INTO @TMP_ACT_EQUAL (ACCOUNTID)  
      SELECT OWNERID FROM TBL_PolicyItem   
      WHERE  POLICYLEVEL=300   
      AND POLICYDIMENSIONID=@POLICYDIMENSIONID  
      AND LOGICALVALUE = @PRE_LOGICALVAL  
      AND OWNERID IN (SELECT ACCOUNTID FROM @TMP_PR_ACT)  
      END  
      ELSE IF(@DATA_TYPE='NUMERIC')  
      BEGIN  
     INSERT INTO @TMP_ACT_EQUAL (ACCOUNTID)  
      SELECT OWNERID FROM TBL_PolicyItem   
      WHERE  POLICYLEVEL=300   
      AND POLICYDIMENSIONID=@POLICYDIMENSIONID  
      AND NUMERICVALUE = @PRE_NUMERICVAL  
      AND OWNERID IN (SELECT ACCOUNTID FROM @TMP_PR_ACT)  
    END  
    ELSE IF(@DATA_TYPE='TEXT')  
    BEGIN  
     INSERT INTO @TMP_ACT_EQUAL (ACCOUNTID)  
      SELECT OWNERID FROM TBL_PolicyItem   
      WHERE  POLICYLEVEL=300   
      AND POLICYDIMENSIONID=@POLICYDIMENSIONID  
      AND TEXTVALUE = @PRE_TEXTVAL  
      AND OWNERID IN (SELECT ACCOUNTID FROM @TMP_PR_ACT)  
    END  
    --Update for program  
    UPDATE TBL_POLICYITEM
    SET DELETEDUSERID=@USERID,  
     MODIFIEDDATE=GETDATE()  
    WHERE POLICYITEMID IN(SELECT POLICYITEMID FROM TBL_PolicyItem WHERE OWNERID=@ENTITY_ID AND POLICYLEVEL=200 AND POLICYDIMENSIONID=@POLICYDIMENSIONID)  
    --Update for all Program Account  
    UPDATE TBL_POLICYITEM
    SET DELETEDUSERID=@USERID,  
     MODIFIEDDATE=GETDATE()  
    WHERE POLICYITEMID  IN  
     (SELECT POLICYITEMID FROM TBL_PolicyItem   
     WHERE OWNERID IN (SELECT ACCOUNTID FROM @TMP_ACT_EQUAL)  
     AND POLICYLEVEL=300 AND POLICYDIMENSIONID=@POLICYDIMENSIONID)  
  
  
    --Delete from Policy Item  
    DELETE FROM TBL_POLICYITEM
    WHERE POLICYITEMID IN(SELECT POLICYITEMID FROM TBL_PolicyItem WHERE OWNERID=@ENTITY_ID AND POLICYLEVEL=200 AND POLICYDIMENSIONID=@POLICYDIMENSIONID)  
      
    DELETE FROM TBL_POLICYITEM  
    WHERE POLICYITEMID  IN  
     (SELECT POLICYITEMID FROM TBL_PolicyItem   
     WHERE OWNERID IN (SELECT ACCOUNTID FROM @TMP_ACT_EQUAL)  
     AND POLICYLEVEL=300 AND POLICYDIMENSIONID=@POLICYDIMENSIONID)  
  
    DELETE FROM TBL_PolicyItem  
    WHERE OWNERID=@ENTITY_ID AND POLICYLEVEL=200 AND POLICYDIMENSIONID=@POLICYDIMENSIONID   
  
    DELETE FROM TBL_PolicyItem  
    WHERE OWNERID IN (SELECT ACCOUNTID FROM @TMP_ACT_EQUAL)  
    AND POLICYLEVEL=300 AND POLICYDIMENSIONID=@POLICYDIMENSIONID  
  
  
    RETURN(1)  
   END  
  
   --update all accounts under this program  
   IF(@DATA_TYPE='DATE')  
   BEGIN  
    --update policy item supplement table  
    UPDATE TBL_POLICYITEM SET   
     MODIFIEDUSERID=@USERID,  
     MODIFIEDDATE=GETDATE()  
    WHERE POLICYITEMID IN   
     (SELECT POLICYITEMID FROM TBL_PolicyItem   
     WHERE OWNERID IN (SELECT ACCOUNTID FROM @TMP_PR_ACT)  
     AND POLICYLEVEL=300 AND POLICYDIMENSIONID=@POLICYDIMENSIONID  
     AND DATEDIFF(DAY,DATEVALUE,@PRE_DATEVAL)=0)  
     
    DECLARE @TEMP_PR_ACT_BILLING TABLE(ACCOUNTID INT)  
  
    --ET 6274 Updating Billing Information of TA  
    -- if the Policydimention is 225 (Services start date)  
    -- Added by Saravanan on 18 Mar 2008  
    IF(@POLICYDIMENSIONID = 225)  
    BEGIN  
     INSERT INTO @TEMP_PR_ACT_BILLING (ACCOUNTID)  
     SELECT OWNERID FROM TBL_PolicyItem  
     WHERE OWNERID IN(SELECT ACCOUNTID FROM @TMP_PR_ACT)  
       AND POLICYDIMENSIONID=@POLICYDIMENSIONID AND  DATEDIFF(DAY,DATEVALUE,@PRE_DATEVAL)=0   
       AND POLICYLEVEL=300   
  
     
     INSERT INTO @TMP_ACT_BILL_PROFILE(ACCOUNTID, BILLINGSTARTDATE)  
     SELECT ACCOUNTID , @VAL_DATE FROM @TEMP_PR_ACT_BILLING  
  
    END  
    --End  
  
    UPDATE TBL_PolicyItem SET DATEVALUE=@VAL_DATE  
    WHERE OWNERID IN(SELECT ACCOUNTID FROM @TMP_PR_ACT)  
    AND POLICYDIMENSIONID=@POLICYDIMENSIONID AND  DATEDIFF(DAY,DATEVALUE,@PRE_DATEVAL)=0   
    AND POLICYLEVEL=300   
  
          
   END  
   ELSE IF(@DATA_TYPE='LIST')  
   BEGIN  
    --update policy item supplement table  
    UPDATE TBL_POLICYITEM SET   
     MODIFIEDUSERID=@USERID,  
     MODIFIEDDATE=GETDATE()  
    WHERE POLICYITEMID IN   
     (SELECT POLICYITEMID FROM TBL_PolicyItem   
     WHERE OWNERID IN (SELECT ACCOUNTID FROM @TMP_PR_ACT)  
     AND POLICYLEVEL=300 AND POLICYDIMENSIONID=@POLICYDIMENSIONID  
     AND POLICYDROPDOWNID = @PRE_LISTVAL)  
  
  
    UPDATE TBL_PolicyItem SET POLICYDROPDOWNID=@VAL_LIST  
    WHERE  OWNERID IN(SELECT ACCOUNTID FROM @TMP_PR_ACT)  
    AND POLICYDIMENSIONID=@POLICYDIMENSIONID AND POLICYDROPDOWNID = @PRE_LISTVAL  
    AND POLICYLEVEL=300      
   END  
   ELSE IF(@DATA_TYPE='LOGICAL')  
   BEGIN  
    --update policy item supplement table  
    UPDATE TBL_POLICYITEM SET   
     MODIFIEDUSERID=@USERID,  
     MODIFIEDDATE=GETDATE()  
    WHERE POLICYITEMID IN   
     (SELECT POLICYITEMID FROM TBL_PolicyItem   
     WHERE OWNERID IN (SELECT ACCOUNTID FROM @TMP_PR_ACT)  
     AND POLICYLEVEL=300 AND POLICYDIMENSIONID=@POLICYDIMENSIONID  
     AND LOGICALVALUE = @PRE_LOGICALVAL)  
   
    UPDATE TBL_PolicyItem SET LOGICALVALUE=@VAL_LOGICAL  
    WHERE OWNERID IN(SELECT ACCOUNTID FROM @TMP_PR_ACT)  
    AND POLICYDIMENSIONID=@POLICYDIMENSIONID AND LOGICALVALUE = @PRE_LOGICALVAL  
    AND POLICYLEVEL=300      
   END  
   ELSE IF(@DATA_TYPE='NUMERIC')  
   BEGIN  
    --update policy item supplement table  
    UPDATE TBL_POLICYITEM SET   
     MODIFIEDUSERID=@USERID,  
     MODIFIEDDATE=GETDATE()  
    WHERE POLICYITEMID IN   
     (SELECT POLICYITEMID FROM TBL_PolicyItem   
     WHERE OWNERID IN (SELECT ACCOUNTID FROM @TMP_PR_ACT)  
     AND POLICYLEVEL=300 AND POLICYDIMENSIONID=@POLICYDIMENSIONID  
     AND NUMERICVALUE = @PRE_NUMERICVAL)  
  
    UPDATE TBL_PolicyItem SET NUMERICVALUE=@VAL_NUMERIC  
    WHERE  OWNERID IN(SELECT ACCOUNTID FROM @TMP_PR_ACT)  
    AND POLICYDIMENSIONID=@POLICYDIMENSIONID AND NUMERICVALUE = @PRE_NUMERICVAL  
    AND POLICYLEVEL=300      
   END  
   ELSE IF(@DATA_TYPE='TEXT')  
   BEGIN  
    --update policy item supplement table  
    UPDATE TBL_POLICYITEM SET   
     MODIFIEDUSERID=@USERID,  
     MODIFIEDDATE=GETDATE()  
    WHERE POLICYITEMID IN   
     (SELECT POLICYITEMID FROM TBL_PolicyItem   
     WHERE OWNERID IN (SELECT ACCOUNTID FROM @TMP_PR_ACT)  
     AND POLICYLEVEL=300 AND POLICYDIMENSIONID=@POLICYDIMENSIONID  
     AND TEXTVALUE = @PRE_TEXTVAL)  
  
         
    UPDATE TBL_PolicyItem SET TEXTVALUE=@VAL_TEXT  
    WHERE  OWNERID IN(SELECT ACCOUNTID FROM @TMP_PR_ACT)  
    AND POLICYDIMENSIONID=@POLICYDIMENSIONID AND TEXTVALUE = @PRE_TEXTVAL  
    AND POLICYLEVEL=300     
   END    
  
   --update suplement table   
   UPDATE TBL_POLICYITEM  
    SET MODIFIEDUSERID=@USERID,  
    MODIFIEDDATE=GETDATE()  
   WHERE POLICYITEMID=@POLICYITEM_ID  
  
   --UPDATE POLICY ITEM TABLE FOR THIS Program  
   IF(@DATA_TYPE='DATE')  
   BEGIN  
    UPDATE TBL_PolicyItem SET DATEVALUE=@VAL_DATE WHERE POLICYITEMID=@POLICYITEM_ID    
   END  
   ELSE IF(@DATA_TYPE='LIST')  
   BEGIN  
    UPDATE TBL_PolicyItem SET POLICYDROPDOWNID=@VAL_LIST WHERE POLICYITEMID=@POLICYITEM_ID  
   END  
   ELSE IF(@DATA_TYPE='LOGICAL')  
   BEGIN  
    UPDATE TBL_PolicyItem SET LOGICALVALUE=@VAL_LOGICAL WHERE POLICYITEMID=@POLICYITEM_ID  
   END  
   ELSE IF(@DATA_TYPE='NUMERIC')  
   BEGIN  
    UPDATE TBL_PolicyItem SET NUMERICVALUE=@VAL_NUMERIC WHERE POLICYITEMID=@POLICYITEM_ID  
   END  
   ELSE IF(@DATA_TYPE='TEXT')  
   BEGIN  
    UPDATE TBL_PolicyItem SET TEXTVALUE=@VAL_TEXT WHERE POLICYITEMID=@POLICYITEM_ID  
   END   
     
  END  
  ELSE IF(@ENTITY_TYPE='ACCOUNT')  
  BEGIN  
   SELECT @TMP_PRG_ID=Alliancenumber FROM SYN_IT_AccountMaster WHERE Customeraccountnumber=@ENTITY_ID  
   SELECT @TMP_CL_ID =managercode FROM SYN_IT_ContactMaster WHERE Alliancenumber=@TMP_PRG_ID  
   --Check for Program value  
   IF EXISTS(SELECT POLICYITEMID FROM TBL_PolicyItem WHERE OWNERID=@TMP_PRG_ID AND POLICYLEVEL=200 AND POLICYDIMENSIONID=@POLICYDIMENSIONID)  
   BEGIN  
    SELECT   
     @VAL_DATE=DATEVALUE ,  
     @VAL_NUMERIC=NUMERICVALUE ,  
     @VAL_LIST=POLICYDROPDOWNID ,  
     @VAL_LOGICAL=LOGICALVALUE ,  
     @VAL_TEXT=TEXTVALUE   
    FROM TBL_PolicyItem   
    WHERE OWNERID=@TMP_PRG_ID AND POLICYLEVEL=200 AND POLICYDIMENSIONID=@POLICYDIMENSIONID  
   END  
   --Check for Client value  
   ELSE IF EXISTS(SELECT POLICYITEMID FROM TBL_PolicyItem WHERE OWNERID=@TMP_CL_ID AND POLICYLEVEL=100 AND POLICYDIMENSIONID=@POLICYDIMENSIONID)  
   BEGIN  
    SELECT   
     @VAL_DATE=DATEVALUE ,  
     @VAL_NUMERIC=NUMERICVALUE ,  
     @VAL_LIST=POLICYDROPDOWNID ,  
     @VAL_LOGICAL=LOGICALVALUE ,  
     @VAL_TEXT=TEXTVALUE   
    FROM TBL_PolicyItem   
    WHERE OWNERID=@TMP_CL_ID AND POLICYLEVEL=100 AND POLICYDIMENSIONID=@POLICYDIMENSIONID      
   END  
  
   --if no value exists at both levels delete & return  
   ELSE   
   BEGIN  
    --Update for program  
    UPDATE TBL_POLICYITEM   
    SET DELETEDUSERID=@USERID,  
     MODIFIEDDATE=GETDATE()  
    WHERE POLICYITEMID IN(SELECT POLICYITEMID FROM TBL_PolicyItem WHERE OWNERID=@ENTITY_ID AND POLICYLEVEL=300 AND POLICYDIMENSIONID=@POLICYDIMENSIONID)  
  
    --Delete from Policy Item  
    DELETE FROM TBL_POLICYITEM  
    WHERE POLICYITEMID IN(SELECT POLICYITEMID FROM TBL_PolicyItem WHERE OWNERID=@ENTITY_ID AND POLICYLEVEL=300 AND POLICYDIMENSIONID=@POLICYDIMENSIONID)  
      
    DELETE FROM TBL_PolicyItem  
    WHERE OWNERID=@ENTITY_ID AND POLICYLEVEL=300 AND POLICYDIMENSIONID=@POLICYDIMENSIONID   
  
    --ET 6274 Updating Billing Information of TA  
    -- if the Policydimention is 225 (Services start date)  
    -- Added by Saravanan on 18 Mar 2008  
    IF(@POLICYDIMENSIONID = 225)  
      
    --If policy dimension is High Priority and it is being deleted from account level  
    IF(@POLICYDIMENSIONID=@DONOR_BENE_TAX_HIGH_PRIORITY)  
    BEGIN  
     UPDATE TBL_IRS_ProfileTax   
     SET MODIFIED_USER_ID=@USERID,  
      MODIFIED_DATE=GETDATE(),  
      HIGH_PRIORITY=NULL  
      WHERE CustomerAccountNumber=@ENTITY_ID --AND ENTITY_TYPE_ID = 187   
    END  
    RETURN(1)  
   END  
  
   --get policyitem id for selected account  
   SELECT  @POLICYITEM_ID=POLICYITEMID FROM TBL_PolicyItem   
   WHERE OWNERID = @ENTITY_ID AND POLICYLEVEL=300 AND POLICYDIMENSIONID=@POLICYDIMENSIONID  
   --UPDATE POLICY ITEM TABLE FOR THIS ACCOUNT WITH PARENT PROGRAM/Client/Global Value  
  
   --update policy item supplement  
   UPDATE TBL_POLICYITEM  
   SET MODIFIEDUSERID=@USERID,  
    MODIFIEDDATE=GETDATE()  
   WHERE POLICYITEMID=@POLICYITEM_ID   
 
   IF(@DATA_TYPE='DATE')  
   BEGIN  
    UPDATE TBL_PolicyItem SET DATEVALUE=@VAL_DATE WHERE POLICYITEMID=@POLICYITEM_ID  
  
    --If policy dimension is High Priority and it is being updated from account level  
    IF(@POLICYDIMENSIONID=@DONOR_BENE_TAX_HIGH_PRIORITY)  
    BEGIN  
     UPDATE TBL_IRS_ProfileTax   
     SET MODIFIED_USER_ID=@USERID,  
      MODIFIED_DATE=GETDATE(),  
      HIGH_PRIORITY=@VAL_DATE  
      WHERE CustomerAccountNumber=@ENTITY_ID --AND ENTITY_TYPE_ID = 187   
    END  
   END  
   ELSE IF(@DATA_TYPE='LIST')  
   BEGIN  
    UPDATE TBL_PolicyItem SET POLICYDROPDOWNID=@VAL_LIST WHERE POLICYITEMID=@POLICYITEM_ID  
   END  
   ELSE IF(@DATA_TYPE='LOGICAL')  
   BEGIN  
    UPDATE TBL_PolicyItem SET LOGICALVALUE=@VAL_LOGICAL WHERE POLICYITEMID=@POLICYITEM_ID  
   END  
   ELSE IF(@DATA_TYPE='NUMERIC')  
   BEGIN  
    UPDATE TBL_PolicyItem SET NUMERICVALUE=@VAL_NUMERIC WHERE POLICYITEMID=@POLICYITEM_ID  
   END  
   ELSE IF(@DATA_TYPE='TEXT')  
   BEGIN  
    UPDATE TBL_PolicyItem SET TEXTVALUE=@VAL_TEXT WHERE POLICYITEMID=@POLICYITEM_ID  
   END   
     
  END  
  
  --ET 6274 Updating Billing Information of TA  
  -- if the Policydimention is 225 (Services start date)  
  -- Added by Saravanan on 18 Mar 2008  
  DECLARE  @CNT INT  
  DECLARE  @MAX_CNT INT  
  DECLARE @CUR_ACCOUNTID INT,@CUR_DATE DATETIME  
  SET @CNT = 1  
  SELECT  @MAX_CNT  = COUNT(ID) FROM @TMP_ACT_BILL_PROFILE  
  WHILE (@CNT <=  @MAX_CNT)  
  BEGIN  
   BEGIN  
    DECLARE @return_value INT  
  END  
   SET @CNT  = @CNT +1  
  END  
  --End Here  
 END TRY  
 BEGIN CATCH  
 --if(@@error !=0)  
  RAISERROR 1000092 'USP_EX_DelPolicyitemCascade: Cannot update  in TBL_PolicyItem table'              
 END CATCH  
END  



 GO
  IF EXISTS (	SELECT *
			FROM sysobjects
			WHERE type = 'P'
			AND name = 'USP_EX_DelPolicyitemCascade') 
	BEGIN
			PRINT 'CREATED PROCEDURE USP_EX_DelPolicyitemCascade';
	END