//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MGI.Cxn.Fund.FIS.ISOWebSvc {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ISO8583Result", Namespace="http://ISO8583WebSvc.NexxoFinancial.com/")]
    [System.SerializableAttribute()]
    public partial class ISO8583Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DisplayMessageEnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DisplayMessageEsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string DisplayMessageEn {
            get {
                return this.DisplayMessageEnField;
            }
            set {
                if ((object.ReferenceEquals(this.DisplayMessageEnField, value) != true)) {
                    this.DisplayMessageEnField = value;
                    this.RaisePropertyChanged("DisplayMessageEn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string DisplayMessageEs {
            get {
                return this.DisplayMessageEsField;
            }
            set {
                if ((object.ReferenceEquals(this.DisplayMessageEsField, value) != true)) {
                    this.DisplayMessageEsField = value;
                    this.RaisePropertyChanged("DisplayMessageEs");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ISO8583WebSvc.NexxoFinancial.com/", ConfigurationName="ISOWebSvc.ISO8583WebSvcSoap")]
    public interface ISO8583WebSvcSoap {
        
        // CODEGEN: Generating message contract since element name KioskId from namespace http://ISO8583WebSvc.NexxoFinancial.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ISO8583WebSvc.NexxoFinancial.com/ExchangeISOMessage", ReplyAction="*")]
        MGI.Cxn.Fund.FIS.ISOWebSvc.ExchangeISOMessageResponse ExchangeISOMessage(MGI.Cxn.Fund.FIS.ISOWebSvc.ExchangeISOMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ISO8583WebSvc.NexxoFinancial.com/SendEcho", ReplyAction="*")]
        bool SendEcho();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ISO8583WebSvc.NexxoFinancial.com/Ping", ReplyAction="*")]
        int Ping();
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://ISO8583WebSvc.NexxoFinancial.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ISO8583WebSvc.NexxoFinancial.com/HelloWorld", ReplyAction="*")]
        MGI.Cxn.Fund.FIS.ISOWebSvc.HelloWorldResponse HelloWorld(MGI.Cxn.Fund.FIS.ISOWebSvc.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ISO8583WebSvc.NexxoFinancial.com/IsConnected", ReplyAction="*")]
        bool IsConnected();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ISO8583WebSvc.NexxoFinancial.com/GetSystemTimeUTC", ReplyAction="*")]
        System.DateTime GetSystemTimeUTC();
        
        // CODEGEN: Generating message contract since element name AppId from namespace http://ISO8583WebSvc.NexxoFinancial.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ISO8583WebSvc.NexxoFinancial.com/GenericMethod", ReplyAction="*")]
        MGI.Cxn.Fund.FIS.ISOWebSvc.GenericMethodResponse GenericMethod(MGI.Cxn.Fund.FIS.ISOWebSvc.GenericMethodRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExchangeISOMessageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExchangeISOMessage", Namespace="http://ISO8583WebSvc.NexxoFinancial.com/", Order=0)]
        public MGI.Cxn.Fund.FIS.ISOWebSvc.ExchangeISOMessageRequestBody Body;
        
        public ExchangeISOMessageRequest() {
        }
        
        public ExchangeISOMessageRequest(MGI.Cxn.Fund.FIS.ISOWebSvc.ExchangeISOMessageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ISO8583WebSvc.NexxoFinancial.com/")]
    public partial class ExchangeISOMessageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string KioskId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string AppId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int SessionId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int MessageType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string DataElements;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string TerminalWorkingKey;
        
        public ExchangeISOMessageRequestBody() {
        }
        
        public ExchangeISOMessageRequestBody(string KioskId, string AppId, int SessionId, int MessageType, string DataElements, string TerminalWorkingKey) {
            this.KioskId = KioskId;
            this.AppId = AppId;
            this.SessionId = SessionId;
            this.MessageType = MessageType;
            this.DataElements = DataElements;
            this.TerminalWorkingKey = TerminalWorkingKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExchangeISOMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExchangeISOMessageResponse", Namespace="http://ISO8583WebSvc.NexxoFinancial.com/", Order=0)]
        public MGI.Cxn.Fund.FIS.ISOWebSvc.ExchangeISOMessageResponseBody Body;
        
        public ExchangeISOMessageResponse() {
        }
        
        public ExchangeISOMessageResponse(MGI.Cxn.Fund.FIS.ISOWebSvc.ExchangeISOMessageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ISO8583WebSvc.NexxoFinancial.com/")]
    public partial class ExchangeISOMessageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MGI.Cxn.Fund.FIS.ISOWebSvc.ISO8583Result ExchangeISOMessageResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Response;
        
        public ExchangeISOMessageResponseBody() {
        }
        
        public ExchangeISOMessageResponseBody(MGI.Cxn.Fund.FIS.ISOWebSvc.ISO8583Result ExchangeISOMessageResult, string Response) {
            this.ExchangeISOMessageResult = ExchangeISOMessageResult;
            this.Response = Response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://ISO8583WebSvc.NexxoFinancial.com/", Order=0)]
        public MGI.Cxn.Fund.FIS.ISOWebSvc.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(MGI.Cxn.Fund.FIS.ISOWebSvc.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://ISO8583WebSvc.NexxoFinancial.com/", Order=0)]
        public MGI.Cxn.Fund.FIS.ISOWebSvc.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(MGI.Cxn.Fund.FIS.ISOWebSvc.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ISO8583WebSvc.NexxoFinancial.com/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GenericMethodRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GenericMethod", Namespace="http://ISO8583WebSvc.NexxoFinancial.com/", Order=0)]
        public MGI.Cxn.Fund.FIS.ISOWebSvc.GenericMethodRequestBody Body;
        
        public GenericMethodRequest() {
        }
        
        public GenericMethodRequest(MGI.Cxn.Fund.FIS.ISOWebSvc.GenericMethodRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ISO8583WebSvc.NexxoFinancial.com/")]
    public partial class GenericMethodRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AppId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int SessionId;
        
        public GenericMethodRequestBody() {
        }
        
        public GenericMethodRequestBody(string AppId, int SessionId) {
            this.AppId = AppId;
            this.SessionId = SessionId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GenericMethodResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GenericMethodResponse", Namespace="http://ISO8583WebSvc.NexxoFinancial.com/", Order=0)]
        public MGI.Cxn.Fund.FIS.ISOWebSvc.GenericMethodResponseBody Body;
        
        public GenericMethodResponse() {
        }
        
        public GenericMethodResponse(MGI.Cxn.Fund.FIS.ISOWebSvc.GenericMethodResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ISO8583WebSvc.NexxoFinancial.com/")]
    public partial class GenericMethodResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool GenericMethodResult;
        
        public GenericMethodResponseBody() {
        }
        
        public GenericMethodResponseBody(bool GenericMethodResult) {
            this.GenericMethodResult = GenericMethodResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISO8583WebSvcSoapChannel : MGI.Cxn.Fund.FIS.ISOWebSvc.ISO8583WebSvcSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SO8583WebSvcSoapClient : System.ServiceModel.ClientBase<MGI.Cxn.Fund.FIS.ISOWebSvc.ISO8583WebSvcSoap>, MGI.Cxn.Fund.FIS.ISOWebSvc.ISO8583WebSvcSoap {
        
        public SO8583WebSvcSoapClient() {
        }
        
        public SO8583WebSvcSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SO8583WebSvcSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SO8583WebSvcSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SO8583WebSvcSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MGI.Cxn.Fund.FIS.ISOWebSvc.ExchangeISOMessageResponse MGI.Cxn.Fund.FIS.ISOWebSvc.ISO8583WebSvcSoap.ExchangeISOMessage(MGI.Cxn.Fund.FIS.ISOWebSvc.ExchangeISOMessageRequest request) {
            return base.Channel.ExchangeISOMessage(request);
        }
        
        public MGI.Cxn.Fund.FIS.ISOWebSvc.ISO8583Result ExchangeISOMessage(string KioskId, string AppId, int SessionId, int MessageType, string DataElements, string TerminalWorkingKey, out string Response) {
            MGI.Cxn.Fund.FIS.ISOWebSvc.ExchangeISOMessageRequest inValue = new MGI.Cxn.Fund.FIS.ISOWebSvc.ExchangeISOMessageRequest();
            inValue.Body = new MGI.Cxn.Fund.FIS.ISOWebSvc.ExchangeISOMessageRequestBody();
            inValue.Body.KioskId = KioskId;
            inValue.Body.AppId = AppId;
            inValue.Body.SessionId = SessionId;
            inValue.Body.MessageType = MessageType;
            inValue.Body.DataElements = DataElements;
            inValue.Body.TerminalWorkingKey = TerminalWorkingKey;
            MGI.Cxn.Fund.FIS.ISOWebSvc.ExchangeISOMessageResponse retVal = ((MGI.Cxn.Fund.FIS.ISOWebSvc.ISO8583WebSvcSoap)(this)).ExchangeISOMessage(inValue);
            Response = retVal.Body.Response;
            return retVal.Body.ExchangeISOMessageResult;
        }
        
        public bool SendEcho() {
            return base.Channel.SendEcho();
        }
        
        public int Ping() {
            return base.Channel.Ping();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MGI.Cxn.Fund.FIS.ISOWebSvc.HelloWorldResponse MGI.Cxn.Fund.FIS.ISOWebSvc.ISO8583WebSvcSoap.HelloWorld(MGI.Cxn.Fund.FIS.ISOWebSvc.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            MGI.Cxn.Fund.FIS.ISOWebSvc.HelloWorldRequest inValue = new MGI.Cxn.Fund.FIS.ISOWebSvc.HelloWorldRequest();
            inValue.Body = new MGI.Cxn.Fund.FIS.ISOWebSvc.HelloWorldRequestBody();
            MGI.Cxn.Fund.FIS.ISOWebSvc.HelloWorldResponse retVal = ((MGI.Cxn.Fund.FIS.ISOWebSvc.ISO8583WebSvcSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        public bool IsConnected() {
            return base.Channel.IsConnected();
        }
        
        public System.DateTime GetSystemTimeUTC() {
            return base.Channel.GetSystemTimeUTC();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MGI.Cxn.Fund.FIS.ISOWebSvc.GenericMethodResponse MGI.Cxn.Fund.FIS.ISOWebSvc.ISO8583WebSvcSoap.GenericMethod(MGI.Cxn.Fund.FIS.ISOWebSvc.GenericMethodRequest request) {
            return base.Channel.GenericMethod(request);
        }
        
        public bool GenericMethod(string AppId, int SessionId) {
            MGI.Cxn.Fund.FIS.ISOWebSvc.GenericMethodRequest inValue = new MGI.Cxn.Fund.FIS.ISOWebSvc.GenericMethodRequest();
            inValue.Body = new MGI.Cxn.Fund.FIS.ISOWebSvc.GenericMethodRequestBody();
            inValue.Body.AppId = AppId;
            inValue.Body.SessionId = SessionId;
            MGI.Cxn.Fund.FIS.ISOWebSvc.GenericMethodResponse retVal = ((MGI.Cxn.Fund.FIS.ISOWebSvc.ISO8583WebSvcSoap)(this)).GenericMethod(inValue);
            return retVal.Body.GenericMethodResult;
        }
    }
}
