INSERT [dbo].[tFundProcessorCredentials] ([Id], [ServiceUrl], [User], [Password], [Application], [TerminalID], [ProcessorID], [CIAClientID], [SystemExtLogin], [DTCreate]) VALUES (N'ecc735b0-1ead-4a75-bd8d-37c53de82ae7', N'https://firstviewcorp.com/dbbApplications/CoreIssue.aspx', N'FNB Nexxo', N'FirstView2012@', N'appScale4630', N'k00001', 14, N'64034', 1, CAST(0x0000A1B601262265 AS DateTime))

DELETE FROM tBillPayProcessorLogin WHERE SecureKey = 'F194307C-A970-43F0-0A6B-19C618E83AFA' AND TerminalID = 'SC0161'
		AND AgentID = 2393 AND ProcessorID = 0

INSERT INTO tBillPayProcessorLogin
(
 Id,
 ClerkID, 
 SecureKey, 
 TerminalID, 
 ServiceURL, 
 ServiceNamespace, 
 AgentID, 
 ProcessorID
)
VALUES
(
 NEWID(),
 'test', 
 'F194307C-A970-43F0-0A6B-19C618E83AFA', 
 'SC0161', 
 'https://test.link.checkfreepay.com/CFPLink/RealTimePayment23.asmx',
 'http://checkfreepay.com/cfplink23/2009/12/',
 --2393,
100000, 
 --0
 13
)



/* Western Union Related Scripts */
/****** Object:  Table [dbo].[tWesternUnionCities]    Script Date: 05/29/2013 17:33:06 ******/
DELETE FROM [tWesternUnionCities]
GO
/****** Object:  Table [dbo].[tWesternUnionCountries]    Script Date: 05/29/2013 17:33:06 ******/
DELETE FROM [tWesternUnionCountries]
GO
/****** Object:  Table [dbo].[tWesternUnionCountryCurrencies]    Script Date: 05/29/2013 17:33:06 ******/
DELETE FROM [tWesternUnionCountryCurrencies]
GO
/****** Object:  Table [dbo].[tWesternUnionCountryCurrencyDeliveryMethods]    Script Date: 05/29/2013 17:33:06 ******/
DELETE FROM [tWesternUnionCountryCurrencyDeliveryMethods]
GO
/****** Object:  Table [dbo].[tWesternUnionDeliveryOptions]    Script Date: 05/29/2013 17:33:06 ******/
DELETE FROM [tWesternUnionDeliveryOptions]
GO
/****** Object:  Table [dbo].[tWesternUnionStates]    Script Date: 05/29/2013 17:33:06 ******/
DELETE FROM [tWesternUnionStates]
GO

/****** Object:  Table [dbo].[tXPickupMethods]    Script Date: 05/29/2013 17:33:07 ******/
DELETE FROM [tWesternUnionPickupMethods]
GO
/****** Object:  Table [dbo].[tWesternUnionPickupMethods]    Script Date: 05/29/2013 17:33:07 ******/
INSERT [tWesternUnionPickupMethods] ([id], [Name], [DescriptionEN], [DescriptionES], [CurrencyConversionDescriptionEN], [CurrencyConversionDescriptionES]) VALUES (2, N'Cash in US Dollars', N'Cash/Window Pickup in USD', N'Recoger efectivo en ventanilla (USD)', N'USD', N'USD')
INSERT [tWesternUnionPickupMethods] ([id], [Name], [DescriptionEN], [DescriptionES], [CurrencyConversionDescriptionEN], [CurrencyConversionDescriptionES]) VALUES (4, N'Direct Deposit in US Dollars', N'Deposit into Account in USD', N'Deposito en cuenta (USD)', N'USD', N'USD')
INSERT [tWesternUnionPickupMethods] ([id], [Name], [DescriptionEN], [DescriptionES], [CurrencyConversionDescriptionEN], [CurrencyConversionDescriptionES]) VALUES (3, N'Direct Deposit in National Currency', N'Deposit into Account in {Currency}', N'Deposito en cuenta ({Currency})', N'{Currency} per USD', N'{Currency} para USD')
INSERT [tWesternUnionPickupMethods] ([id], [Name], [DescriptionEN], [DescriptionES], [CurrencyConversionDescriptionEN], [CurrencyConversionDescriptionES]) VALUES (5, N'New Account', NULL, NULL, NULL, NULL)
INSERT [tWesternUnionPickupMethods] ([id], [Name], [DescriptionEN], [DescriptionES], [CurrencyConversionDescriptionEN], [CurrencyConversionDescriptionES]) VALUES (1, N'Cash in National Currency', N'Cash/Window Pickup in {Currency}', N'Recoger efectivo en ventanilla ({Currency})', N'{Currency} per USD', N'{Currency} para USD')
/****** Object:  Table [dbo].[tWesternUnionPickupDetails]    Script Date: 05/29/2013 17:33:07 ******/
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'0c721bbb-aee9-4506-8c62-54abac712393', N'e917862b-a6eb-47e0-8e26-6a8a2c704ea3', NULL, NULL, N'610', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CAST(0x00009C78012095CC AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'26de88ad-4569-44c8-80db-6cb2b421099c', N'd146a41d-4d37-43bd-8650-2d04465136e8', N'BBV', N'9350', N'0394', NULL, NULL, N'NDF', N'1289101166825       ', N'NDF', NULL, NULL, NULL, NULL, CAST(0x00009C7900C8BA2F AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'963f7b83-cdad-4430-a67b-00d463793a7d', N'27d26182-5810-4b66-9dae-b05d3fe94842', NULL, NULL, N'0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CAST(0x00009C7900FF9A95 AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'dae674cf-6120-43c5-b492-1b4a412692f5', N'bc6d3e86-4953-4b50-aa8b-7b64040bc569', NULL, NULL, N'0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CAST(0x00009C7A00B8394D AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'7a569a6a-b86e-44a0-a443-d4d570d141f2', N'145fcc97-2ce3-40db-86f4-6aea982cb7e5', N'BANORTE', NULL, N'BANORTE-00875', N'A308332', NULL, N'003', N'02078598.4454764710', NULL, NULL, NULL, NULL, NULL, CAST(0x00009C7D00E00D4A AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'd199b501-bb23-4527-b7fb-31530eda87d0', N'5e1efbab-14ac-4015-bf4b-ef27d635c5a7', NULL, NULL, NULL, NULL, NULL, N'CC', N'012208169', NULL, NULL, NULL, NULL, NULL, CAST(0x00009C8400B6A935 AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'aa35d370-f4cd-419a-a71e-7d7f6610bd33', N'c3791180-dd90-49e3-a1e3-66cf1da0c1fa', NULL, NULL, NULL, NULL, NULL, N' ', N' ', NULL, NULL, NULL, NULL, NULL, CAST(0x00009C850086A8DA AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'1bb74f29-fea5-47fd-899c-87ae48604ec1', N'b4f25fe7-4d95-411a-8bb7-b11951f8244d', N'GCA1', NULL, N'GCA1-0087', N'1422000001', NULL, N'004', N'03528773.2826116142', NULL, NULL, NULL, NULL, NULL, CAST(0x00009CA700739A98 AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'ab248de3-20ff-4d72-829d-1f393e0758d1', N'01218806-a1e3-4c3b-9b0e-03ee0bca1e6e', NULL, NULL, N'0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CAST(0x00009CAA01183702 AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'5f324ccd-1ad2-4831-a092-66851b635202', N'b355cf3e-178d-4b47-a974-551e03be9a84', N'GCA1', NULL, N'GCA1-ABONOS', N'GCA1', NULL, NULL, N'03528773.4373838433', NULL, NULL, NULL, NULL, NULL, CAST(0x00009CB700CE0DE7 AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'f005e509-624c-4be3-a4b4-a7a776c5b4c3', N'7d8ba653-4945-43dd-8c32-a941d693be23', N'GCA1', NULL, N'GCA1-ABONOS', N'GCA1', NULL, NULL, N'03528773.1118588661', NULL, NULL, NULL, NULL, NULL, CAST(0x00009CB70133B29E AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'5c8a0025-bfe2-456f-ba34-c960234c757a', N'8c353429-0746-4644-8ed2-4d3bd3d48442', N'BANORTE', NULL, N'BANORTE-00002', N'Banorte', NULL, N'001', N'04353817.2020507114', NULL, NULL, NULL, NULL, NULL, CAST(0x00009CBD00DA6BF7 AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'7e5f0b49-33d3-4892-a659-3fd387c5f44e', N'5423b459-e526-4660-a696-bba475571a33', NULL, NULL, NULL, NULL, NULL, NULL, N'N/A', NULL, NULL, NULL, NULL, NULL, CAST(0x00009CF700737594 AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'90716d69-bf74-4a3d-a317-18c3f8a1c1cd', N'c400c752-3f53-4062-9dc4-2146e9ba4926', NULL, NULL, NULL, NULL, NULL, NULL, N'N/A', NULL, NULL, NULL, NULL, NULL, CAST(0x00009CFB00C078A2 AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'3e2deb85-703d-41fa-b24c-58303c97aaaa', N'6e588932-061e-40af-8f3a-98166f3e63e3', NULL, NULL, NULL, NULL, NULL, NULL, N'C03 52858', NULL, NULL, NULL, NULL, NULL, CAST(0x00009D0300C7BDD9 AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'370a42a9-4123-41a7-9295-2deaf432f851', N'5e7711f8-ffb2-47dc-967b-bbb9f0be7493', NULL, NULL, N'756', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CAST(0x00009D12009CA6EF AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'0942a73c-895f-4ca1-818c-e1f512f8d237', N'd9fbef32-2374-45ea-ab0e-c96de9c29426', NULL, NULL, N'4292', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CAST(0x00009D12009CA714 AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'a3eda7ca-be99-4934-9146-310ec754315a', N'fea7ab65-7329-4109-881b-8eaf7f1d7f75', NULL, NULL, N'335', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CAST(0x00009D12009CA73A AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'739a7bf6-01b0-4068-bfe5-7bd9e860000b', N'3a84a956-ffde-4816-8396-17ba9acdf478', NULL, NULL, N'626', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CAST(0x00009D12009CA75F AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'509b25e1-14fb-4f2f-951a-cadfb05d14ab', N'32bb72de-6dc8-4e55-bde7-470b5b19b015', NULL, NULL, N'785', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CAST(0x00009D12009CA77B AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'fc72b84b-c007-4cc7-93d0-419a49174c71', N'5d773afb-e037-42ad-a9b5-7b3e99ba0799', NULL, NULL, N'368', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CAST(0x00009D12009CA797 AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'416051cc-7aef-4dfb-9e00-ef0143195886', N'952c8d44-f976-4d98-b227-bca22a4d75c6', NULL, NULL, N'446', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CAST(0x00009D12009CA7CB AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'e70e911e-4a80-4ee9-a4f7-2a000f28163f', N'71a7a583-e945-4f0c-a022-6d0d26cfed94', NULL, NULL, N'82', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CAST(0x00009D340073862B AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'c025a50d-aac1-41db-82d1-74c1159177d7', N'65a9f3b5-1c12-4f99-a027-1d43deeca6af', NULL, NULL, N'4438', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CAST(0x00009D34007387ED AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'8eaddc13-314a-4a18-a63b-68da09333b2c', N'd4aa7215-ebd2-4ffd-a184-c37a5713140e', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CAST(0x00009D3700F4A5E3 AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'80bfdd2b-885d-4b65-969b-e608cb062b29', N'11b1195d-5b61-47ee-9695-c65776942dd7', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CAST(0x00009D3700F76AD1 AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'95a53fbd-15cc-4b1d-b15c-cd0b9f059982', N'f9d885e8-cb5b-4379-b78b-1ea5e379b00b', NULL, NULL, N'4438', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CAST(0x00009D6100735336 AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'c3ec30a1-2e85-4237-810a-e86067721869', N'58be9243-8777-44a5-9b59-76ea20920257', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CAST(0x00009D83009F7538 AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'c4182088-0af1-4cfc-a84c-8625bd339a4d', N'dbc14f71-13d5-42f7-aaf7-c884f2d14c70', N'FAMSA', NULL, N'FAMSA-553', N'ZAPATA VEGA RUTH NABILE', NULL, N'003', N'04667562.6672414073', NULL, NULL, NULL, NULL, NULL, CAST(0x00009DAD00B56B04 AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'e6be6610-520e-4342-83bb-d1d50ff13db6', N'e39873cf-3bb8-4d45-ac78-04f849fda18d', N'FAMSA', NULL, N'FAMSA-388', N'PAREDES ALDANA MARICELA', NULL, N'003', N'04667562.5785751668', NULL, NULL, NULL, NULL, NULL, CAST(0x00009DB200D6587A AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'7d021ea2-3216-4dd1-adc1-7d82b67e48d7', N'd709dd7e-2311-4b59-8acd-7a65f63e3b7a', N'FAMSA', NULL, N'FAMSA-608', N'RODRIGUEZ RAMOS MOISES BALDOMERO', NULL, N'003', N'04667562.6617808824', NULL, NULL, NULL, NULL, NULL, CAST(0x00009DB800A0C790 AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'2289740f-911d-4869-93ff-13b168e178b7', N'ffed46e1-8778-49ef-a174-c8c6434a7869', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CAST(0x00009DE60089D214 AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'9bc2d98f-1d1c-4c8d-a8b6-6c925a19cfcd', N'780665fa-06c6-4019-af19-f27d03f04c5c', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CAST(0x00009DF700738BB7 AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'24951919-1d4c-4ef7-aac1-e96267c7f6fd', N'43b16af4-7537-42ea-9cd9-5ad50f029462', NULL, NULL, NULL, NULL, NULL, NULL, N'IF656464987', NULL, NULL, NULL, NULL, NULL, CAST(0x00009DF900A3961F AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'97cfd216-ab8a-4470-8ad1-de475bb5996a', N'5c846d08-b70c-4756-9a7d-2d3d7f9769f7', NULL, NULL, NULL, NULL, NULL, NULL, N'IF656464987', NULL, NULL, NULL, NULL, NULL, CAST(0x00009DF900A39796 AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'57f66b8a-2f7f-4d00-b412-58d0d232390b', N'75741097-4f64-4519-802d-22cdfc94294d', N'BGB', N'50', N'10', NULL, NULL, N'PAS', N'123456789', N'FED', N'999', N'USA', CAST(0x0000AC8F00000000 AS DateTime), NULL, CAST(0x00009DFB007E5694 AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'13438926-e7d1-490d-9adf-407b8f112da8', N'f15a4e50-4a6f-41bd-b151-ef96c02ffdbe', N'GRY', N'1', N'5981254', NULL, NULL, N'PAS', N'123456789', N'FED', N'999', N'USA', CAST(0x0000AC8F00000000 AS DateTime), NULL, CAST(0x00009DFB007FB741 AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'7b7a7863-9322-4410-a19d-5bdfd25f5c2e', N'56ed53ec-5ee7-4d64-850f-35ea8b4d38ba', N'BTG', N'1', N'6', NULL, NULL, N'PAS', N'123456789', N'FED', N'999', N'USA', CAST(0x0000AC8F00000000 AS DateTime), NULL, CAST(0x00009DFB007FB7F8 AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'da19018d-e1fa-4834-a750-ad3018702d26', N'ceb79071-533f-4ff0-8bb5-f33047345bdf', N'EK1', N'1', N'3741', NULL, NULL, N'PAS', N'123456789', N'FED', N'999', N'USA', CAST(0x0000AC8F00000000 AS DateTime), NULL, CAST(0x00009DFB007FB8AA AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'9e7b58c4-9c41-42d5-93d1-907361814cb1', N'58c3d0b7-cc32-460b-b5d6-b6207eacfb31', N'MMT', N'1', N'5981033', NULL, NULL, N'PAS', N'123456789', N'FED', N'999', N'USA', CAST(0x0000AC8F00000000 AS DateTime), NULL, CAST(0x00009DFB007FB979 AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'72559549-b276-4982-9819-6eeba77c8da3', N'2e60840f-4f21-4ebc-87ef-7ccd9d6a33fc', NULL, NULL, NULL, NULL, NULL, NULL, N'6546546', NULL, NULL, NULL, NULL, NULL, CAST(0x00009DFB00B055DA AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'69d437ab-3dc3-445e-9e92-5257e9466be2', N'a50a2ceb-d762-4920-ba41-64e77f024d10', NULL, NULL, NULL, NULL, NULL, NULL, N'987987', NULL, NULL, NULL, NULL, NULL, CAST(0x00009DFB00B05D2C AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'85f6da9c-df8e-442b-8307-2b1290c4d07b', N'af3af2eb-395d-4855-bb40-6d6cd6490fed', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CAST(0x00009DFB00B06139 AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'7ac8c86b-54f7-4bab-9042-fddb284e415f', N'30dbde6c-46f9-4cf0-97c7-188dec270b37', NULL, NULL, NULL, NULL, NULL, NULL, N'33213', NULL, NULL, NULL, NULL, NULL, CAST(0x00009DFB00B06207 AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'fbbf050b-5c8c-414c-8cc8-7b3e2bdeb9a1', N'f852e669-e644-4ea2-8d69-52f4528ce047', NULL, NULL, NULL, NULL, NULL, NULL, N'3213', NULL, NULL, NULL, NULL, NULL, CAST(0x00009DFB00B0658B AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'd110bde7-7d28-4dd9-a4f3-7b9bfb6a3fd9', N'f4940982-222c-419a-9f7e-67ee27a0b16b', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CAST(0x00009DFB00B0662F AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'9ee019e1-4d27-4ff0-b69a-fb97787ce419', N'0b36401b-9816-4446-a423-fb3ab07d0429', NULL, NULL, NULL, NULL, NULL, NULL, N'987987', NULL, NULL, NULL, NULL, NULL, CAST(0x00009DFB00B066BB AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'32f7ab21-a352-4865-900b-a686be305b27', N'9f349ed5-2149-4135-8647-ef744c1a1f02', NULL, NULL, NULL, NULL, NULL, NULL, N'2324234', NULL, NULL, NULL, NULL, NULL, CAST(0x00009DFB00B06735 AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'c486f1df-4245-4c94-94ef-636b65203da3', N'1d7e2729-accc-4393-8a35-e117048380b6', NULL, NULL, NULL, NULL, NULL, NULL, N'2234', NULL, NULL, NULL, NULL, NULL, CAST(0x00009DFB00B067AF AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'3586ed37-f913-45b3-a6c7-42741610b01d', N'436ab52b-b7ec-4937-acaa-79ad6a9c5032', NULL, NULL, NULL, NULL, NULL, NULL, N'454444', NULL, NULL, NULL, NULL, NULL, CAST(0x00009DFB00B06B3C AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'fb0c0ac3-bcb9-48d5-8b3c-1254234e345e', N'4f717923-0424-498b-baeb-b9714bef6adc', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CAST(0x00009DFB00B06FE8 AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'1756146f-5be9-4598-9cb1-a086623677aa', N'30efa75e-be0d-4b31-a558-5059ec53609f', N'BH1', N'1', N'1', NULL, NULL, N'DUI', N'3100323835', N'FED', N'999', N'DOM', NULL, NULL, CAST(0x00009E0500736DA2 AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'c10fd4ad-1b9b-401f-b97b-f5da3ec90848', N'45d73ed5-f4d8-4709-8a19-50a1fc096593', N'INT', N'05001', N'5', NULL, NULL, N'CDC', N'1128384041', N'STA', N'ANT', N'COL', CAST(0x0000C7FC00000000 AS DateTime), NULL, CAST(0x00009E1500E57CB6 AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'68414da4-a5c1-4703-bbfa-3796b979a20d', N'a6c1c73e-6ced-49d8-a972-01e93989ff78', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CAST(0x00009E1700778452 AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'1384cad2-a7cc-4fca-ade4-b3dd2c9d3089', N'8e9bb5cd-b274-4c5d-87ef-c009bd25e57b', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CAST(0x00009E2300A4F4D3 AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'a150f1d2-8f3f-4ee7-871b-669b806e8987', N'39b2a44d-73d1-470f-91c0-60019fb9b93c', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CAST(0x00009E6801161B0B AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'3fba6078-f2ae-4f0e-bb0f-a79adb79e5f4', N'7298ea11-3463-4427-8b32-bc8e760f1a09', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CAST(0x00009E6801161BD0 AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'56ac4bb2-54b5-411a-8361-3d89983553c5', N'3f2a5f5a-c8cf-4796-a618-4b72439a76ad', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CAST(0x00009E6801161C8B AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'ed753851-2ea6-48ea-98ca-ddd91cdc9046', N'2ca6fb68-3844-46e9-86eb-8c2fa1ced10b', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CAST(0x00009E6801161DD8 AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'd3fc7576-f96e-4f1a-ae94-62bd4713352c', N'bd06cd4e-cc2f-43c9-8463-81f1420f544e', NULL, NULL, NULL, NULL, NULL, NULL, N'03100323835', NULL, NULL, NULL, NULL, NULL, CAST(0x00009E7200BF11F8 AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'a34116d0-3ead-451d-b950-8c1bce44da0b', N'ff2b77b4-39cd-4fcc-ab8d-5b3e9302471b', NULL, NULL, NULL, NULL, NULL, NULL, N'031-0032383-5', NULL, NULL, NULL, NULL, NULL, CAST(0x00009E760098A56C AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'ffb7c10f-970c-40d5-9ecc-0b5828698b0f', N'18ab15ed-b49b-4bcd-ad39-8e9d95a95716', NULL, NULL, NULL, NULL, NULL, N'CC', N'000521501', NULL, NULL, NULL, NULL, NULL, CAST(0x00009EB4009F5CD2 AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'a2f5d1ef-daa6-4664-b25e-ece467724f72', N'b772ea66-5279-4913-beea-198461a800cb', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CAST(0x00009EC500738B44 AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'6e6198bb-84d7-4f79-9006-0b96f49448ac', N'd523f323-218c-4cae-90c0-8afe7e24621d', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CAST(0x00009EC60074E8E9 AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'576cc184-fe5f-446f-ad29-247d15563f07', N'9d73cd55-4f73-4597-b3df-de0793c484c9', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CAST(0x00009ED70073B972 AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'fc97a5ee-9263-483e-aedf-6774621c7857', N'd6fe9fad-9970-4546-a6bf-1a713701edba', NULL, NULL, N'CENTRAL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CAST(0x00009EF501142333 AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'c680a6bf-14b2-4b4b-ad10-339473133c75', N'82abd6ad-8f7c-4f74-8d4e-47ee62d6a8ac', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CAST(0x00009F5200E5C1F8 AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'7bbeac1c-97f4-47ff-b27b-609141f5c1d2', N'985d7e76-d033-4354-b10c-1a9a519b82fc', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CAST(0x00009F980098A5B2 AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'e65fcc7c-7618-4840-ad94-c5d288d7ac5e', N'6fc2844d-cf73-449f-91e1-79cb10ed8908', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CAST(0x00009F980098A5C5 AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'0552424f-c842-4b25-b83e-2d8b6108226e', N'6a62d5f1-feff-483e-a5e0-7000e4cd0310', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CAST(0x00009F980098A5D5 AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'755f79ef-5f40-4ecd-9c8b-6af245260830', N'16c83360-966c-4da8-aec8-24a4a6bbf453', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CAST(0x00009FB900BDB4A5 AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'ea023d16-de4a-4235-957d-94cec0335880', N'82f0510f-ce29-4c8a-94b3-72d2b17d4ddd', N'BSF', N'001', N'001', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CAST(0x0000A054007CEAA2 AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'994e9ffd-d8c0-4026-9509-859d65640376', N'706d09e7-de29-478f-8379-ec72381ecd8c', N'BSF', N'001', N'001', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CAST(0x0000A054007CEC2C AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'2d77a4c0-6b4a-4a0c-89d4-0be7d998cef5', N'983c4f06-e6d4-4897-90d3-77f717f96f4b', N'EK1', N'1', N'3265', NULL, NULL, N'PAS', N'326598748521', N'FED', NULL, N'MEX', CAST(0x00009FB300000000 AS DateTime), NULL, CAST(0x0000A05B010A5B51 AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'657dda37-59a8-4250-b66a-680d86a56d1f', N'dc7911f9-7d94-4e63-a7da-5840bb9a8386', N'EK5', N'7', N'7867', NULL, NULL, N'PAS', N'23455', N'FED', NULL, N'MEX', CAST(0x0000A13900000000 AS DateTime), NULL, CAST(0x0000A05B010A5D6A AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'33a4f445-9d54-42ba-a8cd-4566351dad0d', N'05eeb944-bffd-479c-8736-3088300ee315', N'EK5', N'7', N'7867', NULL, NULL, N'PAS', N'49846456', N'FED', NULL, N'MEX', CAST(0x0000A13900000000 AS DateTime), NULL, CAST(0x0000A05B010A5F56 AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'7309c07f-530a-4852-9c0c-bee431ba3626', N'42bba4b3-599d-4feb-a25d-bd7c59223aa8', N'AGR', N'1', N'001', NULL, NULL, N'PAS', N'123456789', N'FED', N'999', N'USA', CAST(0x0000AC8F00000000 AS DateTime), NULL, CAST(0x0000A05B010A6163 AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'beebaea5-804f-463c-a4e6-7b56afd45054', N'181e33cc-f846-4cb5-9f24-99f8006ce38c', N'GCA1', NULL, N'GCA1-ABONOS', N'GCA1', NULL, NULL, N'03528773.2325113536', NULL, NULL, NULL, NULL, NULL, CAST(0x00009CB7013670F0 AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'2315e955-01e3-4631-8732-06cde5ed9bf5', N'e0064206-6ce6-4835-80b1-01f04c2df027', NULL, NULL, N'84', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CAST(0x00009CE800737E2E AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'61884c43-fe06-40ff-a711-ba3a381389b7', N'e825e572-9c1c-4792-80bf-b7bd93098a95', NULL, NULL, NULL, NULL, NULL, NULL, N'Q18 84211', NULL, NULL, NULL, NULL, NULL, CAST(0x00009D1300CA0BDA AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'644b04f7-8936-464a-8792-5de6fb6949bf', N'c3300e93-149d-41e0-973d-9242e67f9d83', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CAST(0x00009EB701052DB1 AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'fab29c0c-5590-4d9c-96ef-442503546642', N'f18df01c-0b84-40c3-ad11-5af54fd3ff08', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CAST(0x00009EB701052DBD AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'f9b8bfab-0fdb-4b76-bbe4-87c4762d84a1', N'2acfe4e4-202a-4567-bde3-a7a51f9684a8', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CAST(0x00009EBB0099E947 AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'4d4c4fac-ac98-4024-b5a7-f1d5825f7ea2', N'b1ae066a-058c-46e5-b005-ad45fff1a237', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CAST(0x00009ED7007BDAAB AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'41665df5-c946-4d24-9b13-59613b97acd2', N'd523f323-218c-4cae-90c0-8afe7e24621d', NULL, NULL, N'COOP SAN MARTIN MONTEAGUDO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CAST(0x00009EE000B15FD2 AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'7fd233c4-dcbd-44e7-9889-0be788dfbddb', N'a3cde8c6-d8b7-46ed-82be-1eb68f43fa52', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CAST(0x00009F9B00FF909F AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'c3378a04-6729-4a9e-b897-6526e1ff9f3a', N'975481c0-df98-4ebb-a177-d65e3c3f6313', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CAST(0x00009F9B0100EC8C AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'47d51ba9-847b-43c0-ba0d-fc201caea779', N'222dcbc8-5597-4621-a937-5377c0b145c0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CAST(0x00009F9C00B1500B AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'deada6b9-0db8-4f00-b115-050a86cbd19b', N'3386e640-668a-4256-9510-b76dd0f48740', N'TLC', N'7', N'7001', NULL, NULL, N'PAS', N'123456789', N'FED', N'999', N'USA', CAST(0x0000AC8F00000000 AS DateTime), NULL, CAST(0x0000A05B010A657A AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'ed550589-cad6-4520-9b19-673e99c58da3', N'7e032cc9-654b-469a-b9e7-ba13f6e0ca55', N'BBV', N'9', N'3562', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CAST(0x0000A05B010A695A AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'94e2780f-cd0b-4422-abc8-76403a64bddf', N'9b155586-974c-4e7a-932e-4d720679177c', N'EK6', N'SF 11', N'783', NULL, NULL, N'CEL', N'0108029133297', N'FED', NULL, N'MEX', CAST(0x0000A1CF00000000 AS DateTime), NULL, CAST(0x0000A062012309D8 AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'3e6dbc4c-a3d1-43bf-bc8f-89e71c4e3e51', N'f4adbf23-da74-4867-b614-143f74921d43', N'BSF', N'001', N'001', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CAST(0x0000A066007CE003 AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'4b5cd3b6-09d4-4974-b770-2965429d15fe', N'535b4136-c242-4ed0-a01d-97063ab41c0d', N'BSF', N'001', N'001', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CAST(0x0000A06801363AAB AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'33431e18-b59d-4727-af8f-cc3ba925b3d2', N'200f0c83-1f63-45cf-8fac-14ce4d9ce64c', N'BSF', N'DEF', N'DEF', NULL, NULL, N'PAS', N'123456789', N'FED', N'999', N'USA', CAST(0x0000AC8F00000000 AS DateTime), NULL, CAST(0x0000A07E00EC1BB8 AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'0672eebd-59a2-4001-910d-f71d5185ffe8', N'c8b234b7-cc53-42ab-8294-c00ac322df2c', N'BSF', N'001', N'001', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CAST(0x0000A08600734FD2 AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'f6209d8b-c0fb-4f4c-a5dc-d62783346523', N'2a19b4e3-fae7-4d25-8b6a-dd98e4d6f076', N'BSF', N'001', N'001', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CAST(0x0000A08600735982 AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'6a1c8983-4b77-469e-a2dc-74e9d4e3e745', N'3420244e-8f66-4eb1-943f-5a60b7007e69', N'BSF', N'001', N'001', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CAST(0x0000A08600735E52 AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'778c4666-e386-4ee0-8f78-b2aabcd93c3f', N'a8c71768-bfda-4cb4-a67d-e782776bc658', N'BSF', N'001', N'001', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CAST(0x0000A09000D8E18F AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'feceebc9-b68e-41d2-94e5-fcaa87051069', N'0bc25437-7fab-4e82-815d-85b021f89667', N'HSB', N'14', N'162', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CAST(0x0000A09A00FDFBE0 AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'34a11f9b-f89a-4c6a-830d-5139420b2c66', N'68a9bec1-305f-4403-9b99-dacb5f2a5378', N'HSB', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CAST(0x0000A09A00FE0080 AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'e85bc32b-1a72-421d-abb7-ba9a6e863df3', N'9a0d4d80-2c41-4213-85d8-0e22e2d42a97', N'BSF', N'1', N'0100', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CAST(0x0000A0BB00BD6259 AS DateTime), NULL)
GO
print 'Processed 100 total records'
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'5e24f38e-5c0a-49ce-be0c-2cae3ffcadbc', N'5ef77f39-a008-4253-a141-d353bc983278', N'EK6', N'SF 5', N'1753', NULL, NULL, N'PAS', N'123456789', N'FED', N'999', N'USA', CAST(0x0000AC8F00000000 AS DateTime), NULL, CAST(0x0000A06100DA452B AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'4afb478c-8b2e-4698-91ea-21981c45f4fa', N'6912d0bb-29e1-4621-b3a8-03591c82cf10', N'BSF', N'001', N'001', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CAST(0x0000A0680130BD12 AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'8a62028b-d49a-40e3-970f-9ac4f178a94f', N'a077a927-2836-44c4-b18d-13bd1830ca68', NULL, NULL, N'84', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CAST(0x00009CEA00739C57 AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'7ac8d199-2671-4982-889c-8d73ab4b6a4c', N'f7c06e3a-5bc3-4881-855e-ebbb95ca2826', NULL, NULL, N'48999631', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CAST(0x00009CEA00739CB5 AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'e240509e-d822-4d41-8df8-1335d62fa6a2', N'54876ae7-8920-483d-a9ba-ea9f8b2cf49c', NULL, NULL, N'626', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CAST(0x00009D1700738CE8 AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'37cccf0d-1257-4260-a5ea-5f8078dc23eb', N'05986aa7-57d6-4adf-b6c8-784f1fa87d79', NULL, NULL, N'368', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CAST(0x00009D1700738D1C AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'66f8681a-1753-40ca-9a1a-e3fe0e8f1771', N'4a33e482-6260-4b0d-9ffe-5935309c1daa', NULL, NULL, N'785', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CAST(0x00009D1700738D4F AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'f5bd5dbc-ef50-4e98-958a-760774883008', N'e43e90d1-5396-4386-84cc-a5d1c39e8ab5', NULL, NULL, N'466', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CAST(0x00009D1700738D79 AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'deaafca3-606b-418b-9b36-939a4391b199', N'58fc1a21-c042-4e7c-9cd0-58537e4f4f96', NULL, NULL, N'358', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CAST(0x00009D1700738DCE AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'ad1f36d1-1b47-4023-a5ef-f5637eabbd62', N'71c46872-579e-47c5-8ef4-81dc558d6f35', NULL, NULL, N'466', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CAST(0x00009D1700738DFD AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'f892569f-2c1c-4f65-acb1-ecb1e0d7f4fa', N'21e8fbea-a2b1-45d7-a8e1-832205d0e918', NULL, NULL, N'466', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CAST(0x00009D1700738E27 AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'b33e2a4b-0002-4c61-80dd-c00593d3fe9e', N'e3dc60df-eab4-4023-86ca-28173ae1862f', NULL, NULL, N'626', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CAST(0x00009D1700738E6D AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'cf15104b-4409-4003-b342-d3d306a142d3', N'f5ec15fd-8b10-498f-b184-d60bf28738d2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CAST(0x00009D3D009E275D AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'28537fea-20e6-4621-9cac-8e58530311b6', N'b4e79d75-4d9c-454f-b074-d2824a9cee15', NULL, NULL, N'466', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CAST(0x00009D1000740CC0 AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'df6198b9-e8d7-4e48-a9eb-28166b861689', N'3c8a5fb2-51bb-4cc1-aa51-d077b2205a75', NULL, NULL, N'358', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CAST(0x00009D1000740CF4 AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'ea02eeb0-e253-4f23-97ea-ebf96ea43679', N'e825e572-9c1c-4792-80bf-b7bd93098a95', NULL, NULL, NULL, NULL, NULL, NULL, N'Q18 84211', NULL, NULL, NULL, NULL, NULL, CAST(0x00009D1000740F89 AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'4b221c50-d24a-4363-a06e-cbead3556992', N'e1df593c-6a39-4aac-823c-01ebe3162f99', NULL, NULL, N'785', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CAST(0x00009D1800738114 AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'8df4a6f7-3e82-49f2-a3e8-bd34f426810b', N'9e143aec-6457-4ba1-8ccb-0b56daf05a16', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CAST(0x00009D5300878719 AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'ff48bc9c-2d16-466c-b543-16fc939e2a24', N'e90624c7-1632-4c8d-ba29-e5ec99e760af', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CAST(0x00009D53008978C2 AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'35839185-61ed-4973-b836-d89b75e62263', N'96e451bf-f6ff-48da-ba67-4f4273296cfb', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CAST(0x00009D5300897A2B AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'c4312bc5-4f81-4b44-8f00-64c7bfa40aef', N'74638476-bae6-4288-906b-84c7b30c435f', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CAST(0x00009D5300897AAF AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'2d57c8da-0faa-45c1-872b-701caec91db1', N'e31c9d58-72a0-45a7-8186-ab0a844b0509', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CAST(0x00009D5300897B28 AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'0798525f-e12a-48b0-a280-8c635887439f', N'7f2233a9-2e96-4dad-86a1-8a04c970c8fa', N'FAMSA', NULL, N'FAMSA-388', N'PAREDES ALDANA MARICELA', NULL, N'003', N'04667562.8021636314', NULL, NULL, NULL, NULL, NULL, CAST(0x00009DB100B9AB36 AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'afc36571-c791-42ca-b07d-fd99c4eebe93', N'9c532709-4f54-4740-87db-66e233345de1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CAST(0x00009EB800EAEF01 AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'fbea0fdc-5869-45eb-a3f1-46e419bded48', N'dfeed486-3b19-45fb-bab4-7b593c084198', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CAST(0x00009EED00EF2EAD AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'ed8ea3b0-873b-46af-88da-d26b1e2b613e', N'2a077e61-532e-478c-9854-8e004f095319', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CAST(0x00009EED00EF2EBA AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'7c550bcb-597b-40bd-9a4c-0a3e3d10ab6d', N'8442cd34-e859-4f31-8fc6-85f8cd53e08b', N'GCA1', NULL, N'GCA1-ABONOS', N'GCA1', NULL, NULL, N'03528773.6762187630', NULL, NULL, NULL, NULL, NULL, CAST(0x00009D1F011C6145 AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'8b071c48-1d6b-42bf-bf12-5870cd3b67f8', N'26944a3e-24dc-4737-b6e7-588e7e737929', N'GCA1', NULL, N'GCA1-ABONOS', N'GCA1', NULL, NULL, N'03528773.4718208235', NULL, NULL, NULL, NULL, NULL, CAST(0x00009D1F011C61DB AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'6b5d5929-7ca1-42be-b295-5a79ccec1b0d', N'1318be77-32e2-4846-8f69-b15b638ae8eb', NULL, NULL, N'626', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CAST(0x00009D200073B315 AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'9be6abc6-92bb-43f8-9e41-4331bfa189e4', N'1a66957a-9a5a-4f6a-b755-82a5010e5069', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CAST(0x00009D2D00E6CF87 AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'fd1e07cd-0723-4666-9b7e-8c708e0bb07c', N'8541f89c-85ad-4b7e-a342-0e7823ccd814', NULL, NULL, N'1039', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CAST(0x00009D2F00737AC7 AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'8241ae86-eae4-475a-8d9b-8c18a7d2ba5e', N'9c45407f-745d-4c48-935b-510431de0145', NULL, NULL, N'82', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CAST(0x00009D3E00A3305A AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'b57dce63-8127-4f1e-b3cc-c721a04ef5e3', N'd3bb8faf-5b3a-4dc2-af18-c2d87d5fbc1c', NULL, NULL, N'82', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CAST(0x00009D3E00A335C6 AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'b2b30b0f-3483-4dc6-bb25-c8480312e201', N'bb800f09-095c-46e3-b049-f65da8b6a2a3', NULL, NULL, N'CENTRAL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CAST(0x00009EE200C8AD21 AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'150460a2-d9bf-49db-911e-12d69cb51e0a', N'689b7a63-2e6a-48c5-b6f6-bfbdd2003e3d', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CAST(0x00009F9B0100EC9B AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'617855e6-d397-45b8-a85a-c428d2d15315', N'93192c59-fb41-41ce-8f4a-38ae43344bec', N'BCP', N'001', N'0487', NULL, NULL, N'PAS', N'123456789', N'FED', N'999', N'USA', CAST(0x0000AC8F00000000 AS DateTime), NULL, CAST(0x0000A06100D8E835 AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'c0e0e425-7ce2-4a58-9627-803ff8a70189', N'14364253-2c02-4dd7-9226-f7b57e4c745f', N'BCP', N'001', N'0283', NULL, NULL, N'PAS', N'123456789', N'FED', N'999', N'USA', CAST(0x0000AC8F00000000 AS DateTime), NULL, CAST(0x0000A06100B7FBFB AS DateTime), NULL)
INSERT [tWesternUnionPickupDetails] ([id], [xid], [PickupPoPName], [PickupPoPRegion], [PickupPoPBranch], [PickupPoPBranchOperator], [PickupPoPReferenceNumber], [BeneficiaryGovernmentIDType], [BeneficiaryGovernmentIDNumber], [BeneficiaryGovernmentIDIssuer], [BeneficiaryGovernmentIDIssuerState], [BeneficiaryGovernmentIDIssuerCountry], [BeneficiaryGovernmentIDExpirationDate], [BeneficiaryName], [DTCreate], [DTLastMod]) VALUES (N'aecf4b2c-1151-4cf9-9df5-890beeac9afe', N'1c0c7664-5e56-4cb3-bff4-ca37ced9b034', N'BCP', N'001', N'0333', NULL, NULL, N'CEL', N'0111091131723', N'FED', N'JAL', N'MEX', CAST(0x0000A06900000000 AS DateTime), NULL, CAST(0x0000A06A00944336 AS DateTime), NULL)
/****** Object:  Table [dbo].[tWesternUnionStates]    Script Date: 05/29/2013 17:33:06 ******/
INSERT [tWesternUnionStates] ([StateCode], [Name], [ISOCountryCode]) VALUES (N'CA', N'CALIFORNIA', N'US')
INSERT [tWesternUnionStates] ([StateCode], [Name], [ISOCountryCode]) VALUES (N'HI', N'HINTON', N'CN')
INSERT [tWesternUnionStates] ([StateCode], [Name], [ISOCountryCode]) VALUES (N'KA', N'KARNATAKA', N'IN')
INSERT [tWesternUnionStates] ([StateCode], [Name], [ISOCountryCode]) VALUES (N'SI', N'SINALOA ', N'MX')
INSERT [tWesternUnionStates] ([StateCode], [Name], [ISOCountryCode]) VALUES (N'TL', N'TOLUCA', N'MX')
/****** Object:  Table [dbo].[tWesternUnionDeliveryOptions]    Script Date: 05/29/2013 17:33:06 ******/
SET IDENTITY_INSERT [tWesternUnionDeliveryOptions] ON
INSERT [tWesternUnionDeliveryOptions] ([Id], [PRODUCT], [CATEGORY], [T_INDEX], [DESCRIPTION]) VALUES (1, N'DLVSVCS_UNIVERSAL H2H', N'2030', N'000', N'0; ; 0; ; ;ADDRESS REQUIRED; 0;')
SET IDENTITY_INSERT [tWesternUnionDeliveryOptions] OFF

/****** Object:  Table [dbo].[tWesternUnionCountryCurrencyDeliveryMethods]    Script Date: 05/29/2013 17:33:06 ******/
INSERT [tWesternUnionCountryCurrencyDeliveryMethods] ([CountryCode], [CurrencyCode], [SVC_CODE], [SVC_NAME], [ROUTE], [BANNER], [DESCRIPTION], [TEMPLT], [CTRY_VIEW_FILTER], [EXCL_FLAGS], [SOURCE_MIN_CURRENCY], [SOURCE_MAX_CURRENCY], [SOURCE_CURRENCY_INCR], [DEST_MIN_CURRENCY], [DEST_MAX_CURRENCY], [DEST_CURRENCY_INCR]) VALUES (N'US', NULL, N'000', N'MONEY IN MINUTES', N'62000000', N'', N'Money In Minutes is available when  sending money', N'0000', N'SVC', N'00', 50.0000, 1000.0000, 10.0000, 50.0000, 1000.0000, 10.0000)
/****** Object:  Table [dbo].[tWesternUnionCountryCurrencies]    Script Date: 05/29/2013 17:33:06 ******/
INSERT [tWesternUnionCountryCurrencies] ([CountryCode], [CurrencyCode]) VALUES (N'AF', N'AFN')
INSERT [tWesternUnionCountryCurrencies] ([CountryCode], [CurrencyCode]) VALUES (N'AU', N'AUD')
INSERT [tWesternUnionCountryCurrencies] ([CountryCode], [CurrencyCode]) VALUES (N'CN', N'CAD')
INSERT [tWesternUnionCountryCurrencies] ([CountryCode], [CurrencyCode]) VALUES (N'IN', N'INR')
INSERT [tWesternUnionCountryCurrencies] ([CountryCode], [CurrencyCode]) VALUES (N'MX', N'MXN')
INSERT [tWesternUnionCountryCurrencies] ([CountryCode], [CurrencyCode]) VALUES (N'US', N'USD')
/****** Object:  Table [dbo].[tWesternUnionCountries]    Script Date: 05/29/2013 17:33:06 ******/
INSERT [tWesternUnionCountries] ([ISOCountryCode], [Name]) VALUES (N'AF', N'AFGHANISTHAN')
INSERT [tWesternUnionCountries] ([ISOCountryCode], [Name]) VALUES (N'CN', N'CANADA')
INSERT [tWesternUnionCountries] ([ISOCountryCode], [Name]) VALUES (N'IN', N'INDIA')
INSERT [tWesternUnionCountries] ([ISOCountryCode], [Name]) VALUES (N'MX', N'MEXICO')
INSERT [tWesternUnionCountries] ([ISOCountryCode], [Name]) VALUES (N'US', N'UNITED STATES')
/****** Object:  Table [dbo].[tWesternUnionCities]    Script Date: 05/29/2013 17:33:06 ******/
SET IDENTITY_INSERT [tWesternUnionCities] ON
INSERT [tWesternUnionCities] ([CityId], [Name], [StateCode]) VALUES (1, N'BANGALORE', N'KA')
INSERT [tWesternUnionCities] ([CityId], [Name], [StateCode]) VALUES (2, N'SAN FRANCISCO', N'CA')
INSERT [tWesternUnionCities] ([CityId], [Name], [StateCode]) VALUES (4, N'TOLUCA', N'TL')
INSERT [tWesternUnionCities] ([CityId], [Name], [StateCode]) VALUES (5, N'ALBERTA', N'HI')
INSERT [tWesternUnionCities] ([CityId], [Name], [StateCode]) VALUES (6, N'GARDEN STATE', N'VI')
INSERT [tWesternUnionCities] ([CityId], [Name], [StateCode]) VALUES (7, N'ALTAMURA', N'SI')
SET IDENTITY_INSERT [tWesternUnionCities] OFF
/****** Object:  Table [dbo].[tPaymentMethods]    Script Date: 05/29/2013 17:33:06 ******/

/****** Object:  Table [dbo].[tRelationships]    Script Date: 05/28/2013 18:38:44 ******/
INSERT [dbo].[tRelationships] ([Name]) VALUES (N'')
INSERT [dbo].[tRelationships] ([Name]) VALUES (N'AUNT')
INSERT [dbo].[tRelationships] ([Name]) VALUES (N'BOYFRIEND')
INSERT [dbo].[tRelationships] ([Name]) VALUES (N'BROTHER')
INSERT [dbo].[tRelationships] ([Name]) VALUES (N'BROTHER-IN-LAW')
INSERT [dbo].[tRelationships] ([Name]) VALUES (N'COUSIN')
INSERT [dbo].[tRelationships] ([Name]) VALUES (N'DAUGHTER')
INSERT [dbo].[tRelationships] ([Name]) VALUES (N'DAUGHTER-IN-LAW')
INSERT [dbo].[tRelationships] ([Name]) VALUES (N'FATHER')
INSERT [dbo].[tRelationships] ([Name]) VALUES (N'FATHER-IN-LAW')
INSERT [dbo].[tRelationships] ([Name]) VALUES (N'FRIEND')
INSERT [dbo].[tRelationships] ([Name]) VALUES (N'GIRLFRIEND')
INSERT [dbo].[tRelationships] ([Name]) VALUES (N'GRANDFATHER')
INSERT [dbo].[tRelationships] ([Name]) VALUES (N'GRANDMOTHER')
INSERT [dbo].[tRelationships] ([Name]) VALUES (N'HUSBAND')
INSERT [dbo].[tRelationships] ([Name]) VALUES (N'MOTHER')
INSERT [dbo].[tRelationships] ([Name]) VALUES (N'MOTHER-IN-LAW')
INSERT [dbo].[tRelationships] ([Name]) VALUES (N'NEPHEW')
INSERT [dbo].[tRelationships] ([Name]) VALUES (N'NIECE')
INSERT [dbo].[tRelationships] ([Name]) VALUES (N'OTHER')
INSERT [dbo].[tRelationships] ([Name]) VALUES (N'SISTER')
INSERT [dbo].[tRelationships] ([Name]) VALUES (N'SISTER-IN-LAW')
INSERT [dbo].[tRelationships] ([Name]) VALUES (N'SON')
INSERT [dbo].[tRelationships] ([Name]) VALUES (N'SON-IN-LAW')
INSERT [dbo].[tRelationships] ([Name]) VALUES (N'UNCLE')
INSERT [dbo].[tRelationships] ([Name]) VALUES (N'WIFE')
