
IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE Name = N'TellerUserId' and OBJECT_ID = OBJECT_ID(N'tCustomer'))
BEGIN
	ALTER TABLE dbo.tCustomer 
	ADD TellerUserId NVARCHAR(100) NULL
END
GO 
IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE Name = N'TellerUserName' and OBJECT_ID = OBJECT_ID(N'tCustomer'))
BEGIN
	ALTER TABLE dbo.tCustomer 
	ADD TellerUserName NVARCHAR(100) NULL
END
GO 
IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE Name = N'LocationId' and OBJECT_ID = OBJECT_ID(N'tCustomer'))
BEGIN
	ALTER TABLE dbo.tCustomer 
	ADD LocationId NVARCHAR(100) NULL
END
GO 
IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE Name = N'LocationName' and OBJECT_ID = OBJECT_ID(N'tCustomer'))
BEGIN
	ALTER TABLE dbo.tCustomer 
	ADD LocationName NVARCHAR(100) NULL
END
GO 
IF NOT EXISTS(SELECT * FROM SYS.COLUMNS WHERE Name = N'CustomerStatus' and OBJECT_ID = OBJECT_ID(N'tCustomer'))
BEGIN
	ALTER TABLE dbo.tCustomer 
	ADD CustomerStatus NVARCHAR(100) NULL
END
GO 
