SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

ALTER TABLE [tFISConnectsDb]
ALTER COLUMN [LastName] varchar(40) NULL 
ALTER TABLE [tFISConnectsDb] ALTER COLUMN[FirstName] varchar(40) NULL 
ALTER TABLE [tFISConnectsDb] ALTER COLUMN [MiddleName] varchar(20) NULL 
ALTER TABLE [tFISConnectsDb] ALTER COLUMN [MiddleName2] varchar(16) NULL 
ALTER TABLE [tFISConnectsDb] ALTER COLUMN [Gender] varchar(6) NULL

ALTER TABLE tFISConnectsDb 
ADD [ProgramId] varchar(10) NULL, [DTCreate] [datetime] NOT NULL CONSTRAINT DF_MyTable_CreateDate_GETDATE DEFAULT GETDATE()

GO

SET ANSI_PADDING OFF
GO