//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCF.Zeo.Cxn.Customer.TCF.EWSScanning {
    using System.Runtime.Serialization;
    using System;

    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="cpsCustomerRequestRecord", Namespace="http://teller.tcfbank.com")]
    [System.SerializableAttribute()]
    public partial class cpsCustomerRequestRecord : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cpsBankNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cpsBranchNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cpsTellerNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cpsLawsonIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cpsPersonalNonpersonalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cpsExistingNewField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cpsFullLegalNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cpsStreetAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cpsAddressSupplementField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cpsCityCountryCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cpsCityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cpsStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cpsZipCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cpsTaxIDNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cpsDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cpsGenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cpsPhone1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cpsPhone2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cpsIDNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cpsIDTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cpsIssueByStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cpsIssueByCountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cpsIssueDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cpsExpirationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cpsInquiryNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cpsVersionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string cpsBankNumber {
            get {
                return this.cpsBankNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.cpsBankNumberField, value) != true)) {
                    this.cpsBankNumberField = value;
                    this.RaisePropertyChanged("cpsBankNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string cpsBranchNumber {
            get {
                return this.cpsBranchNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.cpsBranchNumberField, value) != true)) {
                    this.cpsBranchNumberField = value;
                    this.RaisePropertyChanged("cpsBranchNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string cpsTellerNumber {
            get {
                return this.cpsTellerNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.cpsTellerNumberField, value) != true)) {
                    this.cpsTellerNumberField = value;
                    this.RaisePropertyChanged("cpsTellerNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string cpsLawsonID {
            get {
                return this.cpsLawsonIDField;
            }
            set {
                if ((object.ReferenceEquals(this.cpsLawsonIDField, value) != true)) {
                    this.cpsLawsonIDField = value;
                    this.RaisePropertyChanged("cpsLawsonID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string cpsPersonalNonpersonal {
            get {
                return this.cpsPersonalNonpersonalField;
            }
            set {
                if ((object.ReferenceEquals(this.cpsPersonalNonpersonalField, value) != true)) {
                    this.cpsPersonalNonpersonalField = value;
                    this.RaisePropertyChanged("cpsPersonalNonpersonal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string cpsExistingNew {
            get {
                return this.cpsExistingNewField;
            }
            set {
                if ((object.ReferenceEquals(this.cpsExistingNewField, value) != true)) {
                    this.cpsExistingNewField = value;
                    this.RaisePropertyChanged("cpsExistingNew");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string cpsFullLegalName {
            get {
                return this.cpsFullLegalNameField;
            }
            set {
                if ((object.ReferenceEquals(this.cpsFullLegalNameField, value) != true)) {
                    this.cpsFullLegalNameField = value;
                    this.RaisePropertyChanged("cpsFullLegalName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string cpsStreetAddress {
            get {
                return this.cpsStreetAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.cpsStreetAddressField, value) != true)) {
                    this.cpsStreetAddressField = value;
                    this.RaisePropertyChanged("cpsStreetAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string cpsAddressSupplement {
            get {
                return this.cpsAddressSupplementField;
            }
            set {
                if ((object.ReferenceEquals(this.cpsAddressSupplementField, value) != true)) {
                    this.cpsAddressSupplementField = value;
                    this.RaisePropertyChanged("cpsAddressSupplement");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string cpsCityCountryCode {
            get {
                return this.cpsCityCountryCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.cpsCityCountryCodeField, value) != true)) {
                    this.cpsCityCountryCodeField = value;
                    this.RaisePropertyChanged("cpsCityCountryCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string cpsCity {
            get {
                return this.cpsCityField;
            }
            set {
                if ((object.ReferenceEquals(this.cpsCityField, value) != true)) {
                    this.cpsCityField = value;
                    this.RaisePropertyChanged("cpsCity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string cpsState {
            get {
                return this.cpsStateField;
            }
            set {
                if ((object.ReferenceEquals(this.cpsStateField, value) != true)) {
                    this.cpsStateField = value;
                    this.RaisePropertyChanged("cpsState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string cpsZipCode {
            get {
                return this.cpsZipCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.cpsZipCodeField, value) != true)) {
                    this.cpsZipCodeField = value;
                    this.RaisePropertyChanged("cpsZipCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string cpsTaxIDNumber {
            get {
                return this.cpsTaxIDNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.cpsTaxIDNumberField, value) != true)) {
                    this.cpsTaxIDNumberField = value;
                    this.RaisePropertyChanged("cpsTaxIDNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string cpsDate {
            get {
                return this.cpsDateField;
            }
            set {
                if ((object.ReferenceEquals(this.cpsDateField, value) != true)) {
                    this.cpsDateField = value;
                    this.RaisePropertyChanged("cpsDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string cpsGender {
            get {
                return this.cpsGenderField;
            }
            set {
                if ((object.ReferenceEquals(this.cpsGenderField, value) != true)) {
                    this.cpsGenderField = value;
                    this.RaisePropertyChanged("cpsGender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string cpsPhone1 {
            get {
                return this.cpsPhone1Field;
            }
            set {
                if ((object.ReferenceEquals(this.cpsPhone1Field, value) != true)) {
                    this.cpsPhone1Field = value;
                    this.RaisePropertyChanged("cpsPhone1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string cpsPhone2 {
            get {
                return this.cpsPhone2Field;
            }
            set {
                if ((object.ReferenceEquals(this.cpsPhone2Field, value) != true)) {
                    this.cpsPhone2Field = value;
                    this.RaisePropertyChanged("cpsPhone2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string cpsIDNumber {
            get {
                return this.cpsIDNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.cpsIDNumberField, value) != true)) {
                    this.cpsIDNumberField = value;
                    this.RaisePropertyChanged("cpsIDNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public string cpsIDType {
            get {
                return this.cpsIDTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.cpsIDTypeField, value) != true)) {
                    this.cpsIDTypeField = value;
                    this.RaisePropertyChanged("cpsIDType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=20)]
        public string cpsIssueByState {
            get {
                return this.cpsIssueByStateField;
            }
            set {
                if ((object.ReferenceEquals(this.cpsIssueByStateField, value) != true)) {
                    this.cpsIssueByStateField = value;
                    this.RaisePropertyChanged("cpsIssueByState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=21)]
        public string cpsIssueByCountry {
            get {
                return this.cpsIssueByCountryField;
            }
            set {
                if ((object.ReferenceEquals(this.cpsIssueByCountryField, value) != true)) {
                    this.cpsIssueByCountryField = value;
                    this.RaisePropertyChanged("cpsIssueByCountry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=22)]
        public string cpsIssueDate {
            get {
                return this.cpsIssueDateField;
            }
            set {
                if ((object.ReferenceEquals(this.cpsIssueDateField, value) != true)) {
                    this.cpsIssueDateField = value;
                    this.RaisePropertyChanged("cpsIssueDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=23)]
        public string cpsExpirationDate {
            get {
                return this.cpsExpirationDateField;
            }
            set {
                if ((object.ReferenceEquals(this.cpsExpirationDateField, value) != true)) {
                    this.cpsExpirationDateField = value;
                    this.RaisePropertyChanged("cpsExpirationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=24)]
        public string cpsInquiryNumber {
            get {
                return this.cpsInquiryNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.cpsInquiryNumberField, value) != true)) {
                    this.cpsInquiryNumberField = value;
                    this.RaisePropertyChanged("cpsInquiryNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=25)]
        public string cpsVersion {
            get {
                return this.cpsVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.cpsVersionField, value) != true)) {
                    this.cpsVersionField = value;
                    this.RaisePropertyChanged("cpsVersion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="cpsCustomerResponseRecord", Namespace="http://teller.tcfbank.com")]
    [System.SerializableAttribute()]
    public partial class cpsCustomerResponseRecord : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cpsSuccessIndicatorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cpsStatusFlagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cpsInquiryNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cpsErrorMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string cpsSuccessIndicator {
            get {
                return this.cpsSuccessIndicatorField;
            }
            set {
                if ((object.ReferenceEquals(this.cpsSuccessIndicatorField, value) != true)) {
                    this.cpsSuccessIndicatorField = value;
                    this.RaisePropertyChanged("cpsSuccessIndicator");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string cpsStatusFlag {
            get {
                return this.cpsStatusFlagField;
            }
            set {
                if ((object.ReferenceEquals(this.cpsStatusFlagField, value) != true)) {
                    this.cpsStatusFlagField = value;
                    this.RaisePropertyChanged("cpsStatusFlag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string cpsInquiryNumber {
            get {
                return this.cpsInquiryNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.cpsInquiryNumberField, value) != true)) {
                    this.cpsInquiryNumberField = value;
                    this.RaisePropertyChanged("cpsInquiryNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string cpsErrorMessage {
            get {
                return this.cpsErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.cpsErrorMessageField, value) != true)) {
                    this.cpsErrorMessageField = value;
                    this.RaisePropertyChanged("cpsErrorMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://teller.tcfbank.com", ConfigurationName="EWSScanning.CustomerWSSoap")]
    public interface CustomerWSSoap {
        
        // CODEGEN: Generating message contract since element name cpsRequest from namespace http://teller.tcfbank.com is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://teller.tcfbank.com/PreScreen", ReplyAction="*")]
        EWSScanning.PreScreenResponse PreScreen(EWSScanning.PreScreenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://teller.tcfbank.com/PreScreen", ReplyAction="*")]
        System.Threading.Tasks.Task<EWSScanning.PreScreenResponse> PreScreenAsync(EWSScanning.PreScreenRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PreScreenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PreScreen", Namespace="http://teller.tcfbank.com", Order=0)]
        public TCF.EWSScanning.PreScreenRequestBody Body;
        
        public PreScreenRequest() {
        }
        
        public PreScreenRequest(EWSScanning.PreScreenRequestBody Body) {   
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://teller.tcfbank.com")]
    public partial class PreScreenRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public EWSScanning.cpsCustomerRequestRecord cpsRequest;
        
        public PreScreenRequestBody() {
        }
        
        public PreScreenRequestBody(EWSScanning.cpsCustomerRequestRecord cpsRequest) {
            this.cpsRequest = cpsRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PreScreenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PreScreenResponse", Namespace="http://teller.tcfbank.com", Order=0)]
        public EWSScanning.PreScreenResponseBody Body;
        
        public PreScreenResponse() {
        }
        
        public PreScreenResponse(EWSScanning.PreScreenResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://teller.tcfbank.com")]
    public partial class PreScreenResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public EWSScanning.cpsCustomerResponseRecord PreScreenResult;
        
        public PreScreenResponseBody() {
        }
        
        public PreScreenResponseBody(EWSScanning.cpsCustomerResponseRecord PreScreenResult) {
            this.PreScreenResult = PreScreenResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CustomerWSSoapChannel : EWSScanning.CustomerWSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CustomerWSSoapClient : System.ServiceModel.ClientBase<EWSScanning.CustomerWSSoap>, EWSScanning.CustomerWSSoap {
        
        public CustomerWSSoapClient() {
        }
        
        public CustomerWSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CustomerWSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerWSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EWSScanning.PreScreenResponse EWSScanning.CustomerWSSoap.PreScreen(EWSScanning.PreScreenRequest request) {
            return base.Channel.PreScreen(request);
        }
        
        public EWSScanning.cpsCustomerResponseRecord PreScreen(EWSScanning.cpsCustomerRequestRecord cpsRequest) {
            EWSScanning.PreScreenRequest inValue = new EWSScanning.PreScreenRequest();
            inValue.Body = new EWSScanning.PreScreenRequestBody();
            inValue.Body.cpsRequest = cpsRequest;
            EWSScanning.PreScreenResponse retVal = ((EWSScanning.CustomerWSSoap)(this)).PreScreen(inValue);
            return retVal.Body.PreScreenResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EWSScanning.PreScreenResponse> EWSScanning.CustomerWSSoap.PreScreenAsync(EWSScanning.PreScreenRequest request) {
            return base.Channel.PreScreenAsync(request);
        }
        
        public System.Threading.Tasks.Task<EWSScanning.PreScreenResponse> PreScreenAsync(EWSScanning.cpsCustomerRequestRecord cpsRequest) {
            EWSScanning.PreScreenRequest inValue = new EWSScanning.PreScreenRequest();
            inValue.Body = new EWSScanning.PreScreenRequestBody();
            inValue.Body.cpsRequest = cpsRequest;
            return ((EWSScanning.CustomerWSSoap)(this)).PreScreenAsync(inValue);
        }
    }
}
