-- ============================================================
-- Author:		<Pamila>
-- Create date: <26/09/2014>
-- Description:	<BillerDenominations insertion. Script created based on data from MGI biller denomination file> 
-- Rally ID:	<US2046>
-- ============================================================

INSERT INTO [tMGram_BillerDenomination] ([rowguid],[BillerLimitPK],[DenominationAmount])VALUES(NEWID(),(SELECT ROWGUID FROM tMGram_BillerLimit WHERE ReceiveCode = '1193'),5)
INSERT INTO [tMGram_BillerDenomination] ([rowguid],[BillerLimitPK],[DenominationAmount])VALUES(NEWID(),(SELECT ROWGUID FROM tMGram_BillerLimit WHERE ReceiveCode = '7938'),10)
INSERT INTO [tMGram_BillerDenomination] ([rowguid],[BillerLimitPK],[DenominationAmount])VALUES(NEWID(),(SELECT ROWGUID FROM tMGram_BillerLimit WHERE ReceiveCode = '7938'),15)
INSERT INTO [tMGram_BillerDenomination] ([rowguid],[BillerLimitPK],[DenominationAmount])VALUES(NEWID(),(SELECT ROWGUID FROM tMGram_BillerLimit WHERE ReceiveCode = '7938'),20)
INSERT INTO [tMGram_BillerDenomination] ([rowguid],[BillerLimitPK],[DenominationAmount])VALUES(NEWID(),(SELECT ROWGUID FROM tMGram_BillerLimit WHERE ReceiveCode = '7938'),30)
INSERT INTO [tMGram_BillerDenomination] ([rowguid],[BillerLimitPK],[DenominationAmount])VALUES(NEWID(),(SELECT ROWGUID FROM tMGram_BillerLimit WHERE ReceiveCode = '7938'),50)
INSERT INTO [tMGram_BillerDenomination] ([rowguid],[BillerLimitPK],[DenominationAmount])VALUES(NEWID(),(SELECT ROWGUID FROM tMGram_BillerLimit WHERE ReceiveCode = '7942'),10)
INSERT INTO [tMGram_BillerDenomination] ([rowguid],[BillerLimitPK],[DenominationAmount])VALUES(NEWID(),(SELECT ROWGUID FROM tMGram_BillerLimit WHERE ReceiveCode = '7942'),15)
INSERT INTO [tMGram_BillerDenomination] ([rowguid],[BillerLimitPK],[DenominationAmount])VALUES(NEWID(),(SELECT ROWGUID FROM tMGram_BillerLimit WHERE ReceiveCode = '7942'),20)
INSERT INTO [tMGram_BillerDenomination] ([rowguid],[BillerLimitPK],[DenominationAmount])VALUES(NEWID(),(SELECT ROWGUID FROM tMGram_BillerLimit WHERE ReceiveCode = '7942'),30)
INSERT INTO [tMGram_BillerDenomination] ([rowguid],[BillerLimitPK],[DenominationAmount])VALUES(NEWID(),(SELECT ROWGUID FROM tMGram_BillerLimit WHERE ReceiveCode = '7942'),50)
INSERT INTO [tMGram_BillerDenomination] ([rowguid],[BillerLimitPK],[DenominationAmount])VALUES(NEWID(),(SELECT ROWGUID FROM tMGram_BillerLimit WHERE ReceiveCode = '7944'),10)
INSERT INTO [tMGram_BillerDenomination] ([rowguid],[BillerLimitPK],[DenominationAmount])VALUES(NEWID(),(SELECT ROWGUID FROM tMGram_BillerLimit WHERE ReceiveCode = '7944'),15)
INSERT INTO [tMGram_BillerDenomination] ([rowguid],[BillerLimitPK],[DenominationAmount])VALUES(NEWID(),(SELECT ROWGUID FROM tMGram_BillerLimit WHERE ReceiveCode = '7944'),20)
INSERT INTO [tMGram_BillerDenomination] ([rowguid],[BillerLimitPK],[DenominationAmount])VALUES(NEWID(),(SELECT ROWGUID FROM tMGram_BillerLimit WHERE ReceiveCode = '7944'),30)
INSERT INTO [tMGram_BillerDenomination] ([rowguid],[BillerLimitPK],[DenominationAmount])VALUES(NEWID(),(SELECT ROWGUID FROM tMGram_BillerLimit WHERE ReceiveCode = '7944'),50)
INSERT INTO [tMGram_BillerDenomination] ([rowguid],[BillerLimitPK],[DenominationAmount])VALUES(NEWID(),(SELECT ROWGUID FROM tMGram_BillerLimit WHERE ReceiveCode = '7967'),10)
INSERT INTO [tMGram_BillerDenomination] ([rowguid],[BillerLimitPK],[DenominationAmount])VALUES(NEWID(),(SELECT ROWGUID FROM tMGram_BillerLimit WHERE ReceiveCode = '7967'),15)
INSERT INTO [tMGram_BillerDenomination] ([rowguid],[BillerLimitPK],[DenominationAmount])VALUES(NEWID(),(SELECT ROWGUID FROM tMGram_BillerLimit WHERE ReceiveCode = '7967'),20)
INSERT INTO [tMGram_BillerDenomination] ([rowguid],[BillerLimitPK],[DenominationAmount])VALUES(NEWID(),(SELECT ROWGUID FROM tMGram_BillerLimit WHERE ReceiveCode = '7967'),30)
INSERT INTO [tMGram_BillerDenomination] ([rowguid],[BillerLimitPK],[DenominationAmount])VALUES(NEWID(),(SELECT ROWGUID FROM tMGram_BillerLimit WHERE ReceiveCode = '7967'),50)
INSERT INTO [tMGram_BillerDenomination] ([rowguid],[BillerLimitPK],[DenominationAmount])VALUES(NEWID(),(SELECT ROWGUID FROM tMGram_BillerLimit WHERE ReceiveCode = '7673'),15)
INSERT INTO [tMGram_BillerDenomination] ([rowguid],[BillerLimitPK],[DenominationAmount])VALUES(NEWID(),(SELECT ROWGUID FROM tMGram_BillerLimit WHERE ReceiveCode = '7673'),25)
INSERT INTO [tMGram_BillerDenomination] ([rowguid],[BillerLimitPK],[DenominationAmount])VALUES(NEWID(),(SELECT ROWGUID FROM tMGram_BillerLimit WHERE ReceiveCode = '7673'),50)
INSERT INTO [tMGram_BillerDenomination] ([rowguid],[BillerLimitPK],[DenominationAmount])VALUES(NEWID(),(SELECT ROWGUID FROM tMGram_BillerLimit WHERE ReceiveCode = '7673'),60)
INSERT INTO [tMGram_BillerDenomination] ([rowguid],[BillerLimitPK],[DenominationAmount])VALUES(NEWID(),(SELECT ROWGUID FROM tMGram_BillerLimit WHERE ReceiveCode = '7673'),90)
INSERT INTO [tMGram_BillerDenomination] ([rowguid],[BillerLimitPK],[DenominationAmount])VALUES(NEWID(),(SELECT ROWGUID FROM tMGram_BillerLimit WHERE ReceiveCode = '7575'),25)
INSERT INTO [tMGram_BillerDenomination] ([rowguid],[BillerLimitPK],[DenominationAmount])VALUES(NEWID(),(SELECT ROWGUID FROM tMGram_BillerLimit WHERE ReceiveCode = '7575'),40)
INSERT INTO [tMGram_BillerDenomination] ([rowguid],[BillerLimitPK],[DenominationAmount])VALUES(NEWID(),(SELECT ROWGUID FROM tMGram_BillerLimit WHERE ReceiveCode = '7575'),45)
INSERT INTO [tMGram_BillerDenomination] ([rowguid],[BillerLimitPK],[DenominationAmount])VALUES(NEWID(),(SELECT ROWGUID FROM tMGram_BillerLimit WHERE ReceiveCode = '7575'),50)
INSERT INTO [tMGram_BillerDenomination] ([rowguid],[BillerLimitPK],[DenominationAmount])VALUES(NEWID(),(SELECT ROWGUID FROM tMGram_BillerLimit WHERE ReceiveCode = '7575'),60)
INSERT INTO [tMGram_BillerDenomination] ([rowguid],[BillerLimitPK],[DenominationAmount])VALUES(NEWID(),(SELECT ROWGUID FROM tMGram_BillerLimit WHERE ReceiveCode = '3941'),25)
INSERT INTO [tMGram_BillerDenomination] ([rowguid],[BillerLimitPK],[DenominationAmount])VALUES(NEWID(),(SELECT ROWGUID FROM tMGram_BillerLimit WHERE ReceiveCode = '3941'),50)
INSERT INTO [tMGram_BillerDenomination] ([rowguid],[BillerLimitPK],[DenominationAmount])VALUES(NEWID(),(SELECT ROWGUID FROM tMGram_BillerLimit WHERE ReceiveCode = '3941'),75)
INSERT INTO [tMGram_BillerDenomination] ([rowguid],[BillerLimitPK],[DenominationAmount])VALUES(NEWID(),(SELECT ROWGUID FROM tMGram_BillerLimit WHERE ReceiveCode = '3941'),100)
INSERT INTO [tMGram_BillerDenomination] ([rowguid],[BillerLimitPK],[DenominationAmount])VALUES(NEWID(),(SELECT ROWGUID FROM tMGram_BillerLimit WHERE ReceiveCode = '7272'),25)
INSERT INTO [tMGram_BillerDenomination] ([rowguid],[BillerLimitPK],[DenominationAmount])VALUES(NEWID(),(SELECT ROWGUID FROM tMGram_BillerLimit WHERE ReceiveCode = '7272'),50)
INSERT INTO [tMGram_BillerDenomination] ([rowguid],[BillerLimitPK],[DenominationAmount])VALUES(NEWID(),(SELECT ROWGUID FROM tMGram_BillerLimit WHERE ReceiveCode = '7272'),100)
INSERT INTO [tMGram_BillerDenomination] ([rowguid],[BillerLimitPK],[DenominationAmount])VALUES(NEWID(),(SELECT ROWGUID FROM tMGram_BillerLimit WHERE ReceiveCode = '7272'),30)
INSERT INTO [tMGram_BillerDenomination] ([rowguid],[BillerLimitPK],[DenominationAmount])VALUES(NEWID(),(SELECT ROWGUID FROM tMGram_BillerLimit WHERE ReceiveCode = '7272'),70)
INSERT INTO [tMGram_BillerDenomination] ([rowguid],[BillerLimitPK],[DenominationAmount])VALUES(NEWID(),(SELECT ROWGUID FROM tMGram_BillerLimit WHERE ReceiveCode = '7272'),15)
INSERT INTO [tMGram_BillerDenomination] ([rowguid],[BillerLimitPK],[DenominationAmount])VALUES(NEWID(),(SELECT ROWGUID FROM tMGram_BillerLimit WHERE ReceiveCode = '7272'),60)
INSERT INTO [tMGram_BillerDenomination] ([rowguid],[BillerLimitPK],[DenominationAmount])VALUES(NEWID(),(SELECT ROWGUID FROM tMGram_BillerLimit WHERE ReceiveCode = '7272'),80)
INSERT INTO [tMGram_BillerDenomination] ([rowguid],[BillerLimitPK],[DenominationAmount])VALUES(NEWID(),(SELECT ROWGUID FROM tMGram_BillerLimit WHERE ReceiveCode = '7936'),5)
INSERT INTO [tMGram_BillerDenomination] ([rowguid],[BillerLimitPK],[DenominationAmount])VALUES(NEWID(),(SELECT ROWGUID FROM tMGram_BillerLimit WHERE ReceiveCode = '7936'),10)
INSERT INTO [tMGram_BillerDenomination] ([rowguid],[BillerLimitPK],[DenominationAmount])VALUES(NEWID(),(SELECT ROWGUID FROM tMGram_BillerLimit WHERE ReceiveCode = '7936'),20)
INSERT INTO [tMGram_BillerDenomination] ([rowguid],[BillerLimitPK],[DenominationAmount])VALUES(NEWID(),(SELECT ROWGUID FROM tMGram_BillerLimit WHERE ReceiveCode = '7936'),30)
INSERT INTO [tMGram_BillerDenomination] ([rowguid],[BillerLimitPK],[DenominationAmount])VALUES(NEWID(),(SELECT ROWGUID FROM tMGram_BillerLimit WHERE ReceiveCode = '7941'),5)
INSERT INTO [tMGram_BillerDenomination] ([rowguid],[BillerLimitPK],[DenominationAmount])VALUES(NEWID(),(SELECT ROWGUID FROM tMGram_BillerLimit WHERE ReceiveCode = '7941'),10)
INSERT INTO [tMGram_BillerDenomination] ([rowguid],[BillerLimitPK],[DenominationAmount])VALUES(NEWID(),(SELECT ROWGUID FROM tMGram_BillerLimit WHERE ReceiveCode = '7941'),20)
INSERT INTO [tMGram_BillerDenomination] ([rowguid],[BillerLimitPK],[DenominationAmount])VALUES(NEWID(),(SELECT ROWGUID FROM tMGram_BillerLimit WHERE ReceiveCode = '7941'),30)
INSERT INTO [tMGram_BillerDenomination] ([rowguid],[BillerLimitPK],[DenominationAmount])VALUES(NEWID(),(SELECT ROWGUID FROM tMGram_BillerLimit WHERE ReceiveCode = '7946'),5)
INSERT INTO [tMGram_BillerDenomination] ([rowguid],[BillerLimitPK],[DenominationAmount])VALUES(NEWID(),(SELECT ROWGUID FROM tMGram_BillerLimit WHERE ReceiveCode = '7946'),10)
INSERT INTO [tMGram_BillerDenomination] ([rowguid],[BillerLimitPK],[DenominationAmount])VALUES(NEWID(),(SELECT ROWGUID FROM tMGram_BillerLimit WHERE ReceiveCode = '7946'),20)
INSERT INTO [tMGram_BillerDenomination] ([rowguid],[BillerLimitPK],[DenominationAmount])VALUES(NEWID(),(SELECT ROWGUID FROM tMGram_BillerLimit WHERE ReceiveCode = '7946'),30)
INSERT INTO [tMGram_BillerDenomination] ([rowguid],[BillerLimitPK],[DenominationAmount])VALUES(NEWID(),(SELECT ROWGUID FROM tMGram_BillerLimit WHERE ReceiveCode = '7962'),5)
INSERT INTO [tMGram_BillerDenomination] ([rowguid],[BillerLimitPK],[DenominationAmount])VALUES(NEWID(),(SELECT ROWGUID FROM tMGram_BillerLimit WHERE ReceiveCode = '7962'),10)
INSERT INTO [tMGram_BillerDenomination] ([rowguid],[BillerLimitPK],[DenominationAmount])VALUES(NEWID(),(SELECT ROWGUID FROM tMGram_BillerLimit WHERE ReceiveCode = '7962'),20)
INSERT INTO [tMGram_BillerDenomination] ([rowguid],[BillerLimitPK],[DenominationAmount])VALUES(NEWID(),(SELECT ROWGUID FROM tMGram_BillerLimit WHERE ReceiveCode = '7962'),30)
INSERT INTO [tMGram_BillerDenomination] ([rowguid],[BillerLimitPK],[DenominationAmount])VALUES(NEWID(),(SELECT ROWGUID FROM tMGram_BillerLimit WHERE ReceiveCode = '7870'),5)
INSERT INTO [tMGram_BillerDenomination] ([rowguid],[BillerLimitPK],[DenominationAmount])VALUES(NEWID(),(SELECT ROWGUID FROM tMGram_BillerLimit WHERE ReceiveCode = '7870'),10)
INSERT INTO [tMGram_BillerDenomination] ([rowguid],[BillerLimitPK],[DenominationAmount])VALUES(NEWID(),(SELECT ROWGUID FROM tMGram_BillerLimit WHERE ReceiveCode = '7870'),20)
INSERT INTO [tMGram_BillerDenomination] ([rowguid],[BillerLimitPK],[DenominationAmount])VALUES(NEWID(),(SELECT ROWGUID FROM tMGram_BillerLimit WHERE ReceiveCode = '7870'),30)
INSERT INTO [tMGram_BillerDenomination] ([rowguid],[BillerLimitPK],[DenominationAmount])VALUES(NEWID(),(SELECT ROWGUID FROM tMGram_BillerLimit WHERE ReceiveCode = '7870'),50)
INSERT INTO [tMGram_BillerDenomination] ([rowguid],[BillerLimitPK],[DenominationAmount])VALUES(NEWID(),(SELECT ROWGUID FROM tMGram_BillerLimit WHERE ReceiveCode = '7592'),50)
INSERT INTO [tMGram_BillerDenomination] ([rowguid],[BillerLimitPK],[DenominationAmount])VALUES(NEWID(),(SELECT ROWGUID FROM tMGram_BillerLimit WHERE ReceiveCode = '7592'),70)


GO