USE [master]
GO

/****** Object:  Database [Compliance]    Script Date: 07/03/2013 12:05:33 ******/
CREATE DATABASE [Compliance] ON  PRIMARY 
( NAME = N'Compliance', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MDOWD\MSSQL\DATA\Compliance.mdf' , SIZE = 2048KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Compliance_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MDOWD\MSSQL\DATA\Compliance_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Compliance] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Compliance].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Compliance] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Compliance] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Compliance] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Compliance] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Compliance] SET ARITHABORT OFF 
GO

ALTER DATABASE [Compliance] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Compliance] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [Compliance] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Compliance] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Compliance] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Compliance] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Compliance] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Compliance] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Compliance] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Compliance] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Compliance] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Compliance] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Compliance] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Compliance] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Compliance] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Compliance] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Compliance] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Compliance] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Compliance] SET  READ_WRITE 
GO

ALTER DATABASE [Compliance] SET RECOVERY FULL 
GO

ALTER DATABASE [Compliance] SET  MULTI_USER 
GO

ALTER DATABASE [Compliance] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Compliance] SET DB_CHAINING OFF 
GO


